"""Necessary raised-slider geometry curriculum; explicit synthetic initial sensor only."""
import json,copy,subprocess,hashlib,shutil,xml.etree.ElementTree as ET
from pathlib import Path
import numpy as np
from scripts.adapt_wuji_two_stage_initial_geometry import adapt_two_stage
from scripts.project_wuji_initial_motor_preload import project as project_self
from scripts.project_wuji_estimated_table_preload import project_all
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');D=Path('research/antirotation-grasp-20261004');O=B/'height-geometry-bank8-v1';O.mkdir(exist_ok=False);F=Path('assets/objects/knife_wuji_antirotation_height_20261004');F.mkdir(exist_ok=False);PY='/home/agiuser/miniconda3/envs/artgym/bin/python';scene=json.loads((D/'actual-table-lower-side-scene-v2.json').read_text());op0=json.loads((B/'continuous-plans-v6/lower-side-calibrated/settled-operation-grasp.json').read_text());ref0=json.loads((B/'continuous-plans-v6/lower-side-calibrated/reference-v1.json').read_text());loc=json.loads((B/'pickup-plans-v1/opposed/localization.json').read_text());rng=np.random.default_rng(2026100461);records=[];ids=[];outcomes=[];registry=[]
for i,(base,height,axial,lateral) in enumerate([('t0000',.002,.005,-.001),('t0000',.004,-.005,.001),('t0001',.004,None,None),('t0002',.002,None,None)]):
 source=Path('assets/objects/knife_wuji_dense_under_20261003')/base;sid='b%04d'%i;dest=F/sid;dest.mkdir();params=json.loads((source/'parameters.json').read_text());tree=ET.parse(source/'mobility.urdf');shutil.copy2(source/'slider-shoulder.obj',dest/'slider-shoulder.obj');origin=np.array(params['slider_origin']);origin[1]+=(height-.003)/2
 if axial is not None:origin[2]=.010624586881962734+axial
 if lateral is not None:origin[0]=lateral
 tree.find('./joint/origin').set('xyz',' '.join(map(str,origin)))
 for mesh in tree.findall("./link[@name='link_1']/visual/geometry/mesh")+tree.findall("./link[@name='link_1']/collision/geometry/mesh"):mesh.set('scale','1 %g 1'%(height/.003))
 mass=.006*height/.003;inert=tree.find("./link[@name='link_1']/inertial");inert.find('mass').set('value',str(mass));size=np.array([.01,height,.03]);diag=mass/12*np.array([size[1]**2+size[2]**2,size[0]**2+size[2]**2,size[0]**2+size[1]**2])
 for k,v in zip(['ixx','iyy','izz'],diag):inert.find('inertia').set(k,str(v))
 tree.write(dest/'mobility.urdf',encoding='utf-8',xml_declaration=True);params.update(id=sid,split='train-height',slider_origin=origin.tolist(),slider_size=size.tolist(),slider_initial_center=(origin+[0,0,params['joint_lower']]).tolist(),masses=[params['masses'][0],mass],urdf_sha256=hashlib.sha256((dest/'mobility.urdf').read_bytes()).hexdigest(),scope='Originalslider mesh Y scaling2--4mm plus authored mass/inertia scaling, declared engineering morphology challenge; not measuredreal mass/inertia. Physicalmetadata only sensor generator/simulator, no controllerID.');(dest/'parameters.json').write_text(json.dumps(params,indent=2));registry.append({'instance':sid,'directory':str(dest),'split':'train'})
 for j in range(2):
  out=O/('%s-observation%d'%(sid,j));out.mkdir();observed=np.array(params['handle_size'])+rng.uniform(-1,1,3)*[.00025,.00025,.0005];delta=origin-np.array([0,.0075,.010624586881962734]);delta[1]-=(params['handle_size'][1]-.012)/2;delta[1]+=(height-.003)/2;delta+=rng.uniform(-.00025,.00025,3)
  estimate={'handle_size_WTL_m':observed.tolist(),'slider_size_WTL_m':[.01,height+float(rng.uniform(-.0001,.0001)),.03],'slider_contact_shift_m':delta.tolist(),'initial_object_center_shift_knife_m':[0,float((observed[1]-.012)/2),0],'uncertainty_m':.00025,'source':'Labelled synthetic noisy onceinitial size/raisedslider contact observation; physicalmetadata only sensor generator, no connected vision or physicalID planner/actor input'};(out/'estimate.json').write_text(json.dumps(estimate,indent=2));record('height_initial_estimate_target_preparation_started',config={'estimate':estimate,'scope':'Necessaryheight/axial/lateral morphology train-only; shared common planner frozenbehavior rules, no force feedback'},evidence=str(out),next='Original boundedself/table/wholethumbgeometry gates before physicaltraining')
  adapted=adapt_two_stage(estimate,scene['plan'],op0,ref0);motor=project_self(adapted['motor_plan']);motor=project_all(motor,loc) if motor['initial_motor_self_projection']['passed'] else motor;(out/'motor-plan.json').write_text(json.dumps(motor,indent=2));valid=motor['initial_motor_self_projection']['passed'] and motor.get('common_initial_table_projection',{}).get('passed',False);checks=[]
  if valid:
   operating=copy.deepcopy(op0);operating.update(close_q=motor['post_lift_close_q'],initial_geometry_estimate=estimate);(out/'operating-plan.json').write_text(json.dumps(operating,indent=2))
   commands=[('acquisition',['-m','scripts.audit_wuji_actual_acquisition_motor','--plan',str(out/'motor-plan.json'),'--acquisition',str(B/'pickup-plans-v1/opposed/lateral-acquisition/acquisition-path.json'),'--output',str(out/'acquisition-audit.json')]),('transfer',['-m','scripts.audit_wuji_pickup_preload','--plan',str(out/'motor-plan.json'),'--localization',str(B/'pickup-plans-v1/opposed/localization.json'),'--output',str(out/'transfer-audit.json')]),('thumbplan',['-m','scripts.plan_g2_direct_thumb_motor_stroke','--plan',str(out/'operating-plan.json'),'--output',str(out/'reference.json')]),('thumbdense',['-m','scripts.audit_g2_anchored_thumb_motor','--reference',str(out/'reference.json'),'--motor-plan',str(out/'motor-plan.json'),'--knife-spec','research/robust-knife-family-20261003/real-knife-asset-spec.json','--samples','161','--output',str(out/'motor-audit.json')])]
   for label,args in commands:
    code=subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name','height-%s-obs%d-%s-v1'%(sid,j,label),'--',PY]+args).returncode;checks.append({'stage':label,'exit_code':code})
    if code:valid=False;break
  if valid:records.append({'estimate':estimate,'motor_plan':motor,'support_target_q':motor['post_lift_close_q'],'thumb_reference':json.loads((out/'reference.json').read_text())});ids.append(sid)
  outcomes.append({'instance_physics_only':sid,'observation':j,'passed':valid,'checks':checks,'output':str(out)});(O/'records.json').write_text(json.dumps(records,indent=2));(O/'outcomes.json').write_text(json.dumps(outcomes,indent=2));(O/'physical-schedule-templates.json').write_text(json.dumps({'instances':ids},indent=2));(O/'registry.json').write_text(json.dumps({'entries':registry},indent=2));record('height_initial_estimate_target_preparation_closed',config={'passed':valid,'qualified_so_far':len(records)},evidence=str(out),next='Retain failedgeometryevidence, no geometricrelaxation; continue necessarymorphology trainpreparation')
record('height_geometry_bank_preparation_completed',config={'attempted':8,'passed':len(records),'scope':'Preparation only, no actualbehavior or independentgeneralization'},evidence=str(O),next='Combineoriginal16 andheight-qualified templates for common actualqualification/newclosure curriculum; disclose unsupported cases')
