"""Once-loaded offline nominal prior from previous development; no online truth."""
import json,hashlib,numpy as np
from pathlib import Path
from scipy.spatial.transform import Rotation
from scripts.g2_contact_geometry import DigitGeometry
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');trial=B/'continuous/actual-table-lower-side-direct-2cycles-v11';t=np.load(trial/'trace.npz');i=abs(t['time']-15.9).argmin()
def mat(p):
 m=np.eye(4);m[:3,:3]=Rotation.from_quat(p[3:7]).as_matrix();m[:3,3]=p[:3];return m
obj=mat(t['object'][i]);wrist=mat(t['wrist'][i]);wtk=np.linalg.inv(obj)@wrist;op=json.loads((B/'continuous-plans-v5/table-lower-side-index/operating-motor-plan-v1.json').read_text());op.update(wrist_in_knife=wtk.tolist(),touch_q=t['q'][i].tolist(),planning_slider_m=float(t['slider'][i]),offline_measured_operation_only=True);g=DigitGeometry(knife_spec="research/robust-knife-family-20261003/real-knife-asset-spec.json");slide=np.eye(4);slide[:3,3]=g.knife_geometry.joint_xyz+np.array([0,0,float(t['slider'][i])]);source=dict(trace=str(trial/'trace.npz'),sha256=hashlib.sha256((trial/'trace.npz').read_bytes()).hexdigest(),time_s=float(t['time'][i]),scope='Previousdevelopment nominalgrip, loadedoncebeforefutureepisode; no currentobject/slider/contacttruth. Not realcamera calibration.');cal=dict(object_in_wrist=(np.linalg.inv(wrist)@obj).tolist(),slider_in_wrist=(np.linalg.inv(wrist)@obj@slide).tolist(),scope=source);d=B/'continuous-plans-v6/lower-side-calibrated';d.mkdir(parents=True,exist_ok=False);(d/'settled-operation-grasp.json').write_text(json.dumps(op,indent=2));(d/'nominal-calibration.json').write_text(json.dumps(cal,indent=2));old=np.array(json.loads((B/'continuous-plans-v1/opposed-table-strong/settled-operation-grasp.json').read_text())['wrist_in_knife']);delta=np.linalg.inv(old)@wtk;info=dict(translation_change_m=delta[:3,3].tolist(),rotation_change_rad=float(Rotation.from_matrix(delta[:3,:3]).magnitude()),source=source);(d/'prior-change.json').write_text(json.dumps(info,indent=2));print(json.dumps(info));record('new_lower_side_nominal_operation_prior_prepared',evidence=str(d),config=info,next='Fitdirectfullmotor trajectory in actualnewnominalgripframe; freshactualtablepickup experiment, never currenttruth online')
