"""Four predeclared fresh physical joint challenges; no rollout before actor freeze."""
import copy,hashlib,json,shutil,subprocess,xml.etree.ElementTree as ET
from pathlib import Path
import numpy as np
from scripts.record_wuji_antirotation_goal import record
from scripts.adapt_wuji_two_stage_initial_geometry import adapt_two_stage
from scripts.project_wuji_initial_motor_preload import project as project_self
from scripts.project_wuji_estimated_table_preload import project_all
B=Path('runs/antirotation-grasp-20261004');D=Path('research/antirotation-grasp-20261004');O=B/'fresh-joint-challenges4-v1';O.mkdir(exist_ok=False);F=Path('assets/objects/knife_wuji_antirotation_fresh_20261004');F.mkdir(exist_ok=False);base=Path('assets/objects/knife_wuji_real_size_20261002/000');meta=json.loads((base/'parameters.json').read_text());rng=np.random.default_rng(2026100467);scene=json.loads((D/'actual-table-lower-side-scene-v2.json').read_text());op0=json.loads((B/'continuous-plans-v6/lower-side-calibrated/settled-operation-grasp.json').read_text());ref0=json.loads((B/'continuous-plans-v6/lower-side-calibrated/reference-v1.json').read_text());loc=json.loads((B/'pickup-plans-v1/opposed/localization.json').read_text());PY='/home/agiuser/miniconda3/envs/artgym/bin/python';conditions=[{'load':.2,'detent':.2,'profile':'constant','frequency':1.7,'delay':0,'noise':.001,'bias':.001},{'load':.5,'detent':.5,'profile':'triangular','frequency':1.7,'delay':1,'noise':.001,'bias':.001},{'load':.35,'detent':.4,'profile':'pulse','frequency':1.9,'delay':0,'noise':.001,'bias':.0012},{'load':.6,'detent':.5,'profile':'sinusoidal','frequency':1.5,'delay':1,'noise':.001,'bias':.001}];prereg={'seed':2026100467,'count':4,'conditions':conditions,'scope':'Fresh current-round joint morphology/load/sensor/delay challenge, originalmeshmorphology, not unseenmodel/category/realhardware. Exactly four draws, no reroll/repeat-to-pass. Commonplanner fixed beforebehavior; actor chosen/frozen fromdevelopment only before openingchallenge rollouts. Planning failures counted, no targetrelaxation.','actor_selection':'Select a new jointlytrained actor only after actual nominal+thin development functionalcriteria bothpass; otherwise retain unchanged750. No candidate selected by thesechallenge results.','criterion':'Unchanged predeclared functional-criterion-v1 and separate originallegacy0.25rad'};(D/'FRESH-JOINT-CHALLENGE-PREREGISTRATION.json').write_text(json.dumps(prereg,indent=2)+'\n');record('fresh_four_joint_challenges_preregistered',config=prereg,evidence=str(D/'FRESH-JOINT-CHALLENGE-PREREGISTRATION.json'),next='Generate allfour assets/noisyobservations andcommon originalgeometry plans without physics/actoroutcome access')
prior_hashes={hashlib.sha256(p.read_bytes()).hexdigest() for family in ['knife_wuji_dense_under_20261003','knife_wuji_antirotation_train_20261004','knife_wuji_antirotation_height_20261004'] for p in (Path('assets/objects')/family).glob('*/mobility.urdf')};rows=[]
for i,condition in enumerate(conditions):
 sid='f%04d'%i;dest=F/sid;dest.mkdir();size=rng.uniform([.014,.010,.130],[.018,.014,.140]);height=float(rng.uniform(.002,.004));origin=np.array([rng.uniform(-.001,.001),size[1]/2+height/2,.010624586881962734+rng.uniform(-.005,.005)]);tree=ET.parse(base/'mobility.urdf');shutil.copy2(base/'slider-shoulder.obj',dest/'slider-shoulder.obj')
 for box in tree.findall("./link[@name='link_0']/visual/geometry/box")+tree.findall("./link[@name='link_0']/collision/geometry/box"):box.set('size',' '.join(map(str,size)))
 tree.find('./joint/origin').set('xyz',' '.join(map(str,origin)))
 for mesh in tree.findall("./link[@name='link_1']/visual/geometry/mesh")+tree.findall("./link[@name='link_1']/collision/geometry/mesh"):mesh.set('scale','1 %g 1'%(height/.003))
 masses=[.029*float(np.prod(size)/np.prod([.016,.012,.135])),.006*height/.003]
 for link,dim,mass in [('link_0',size,masses[0]),('link_1',np.array([.01,height,.03]),masses[1])]:
  inert=tree.find("./link[@name='%s']/inertial"%link);inert.find('mass').set('value',str(mass));diag=mass/12*np.array([dim[1]**2+dim[2]**2,dim[0]**2+dim[2]**2,dim[0]**2+dim[1]**2])
  for k,v in zip(['ixx','iyy','izz'],diag):inert.find('inertia').set(k,str(v))
 tree.write(dest/'mobility.urdf',encoding='utf-8',xml_declaration=True);sha=hashlib.sha256((dest/'mobility.urdf').read_bytes()).hexdigest();assert sha not in prior_hashes;params=dict(meta,id=sid,split='fresh-joint-validation',handle_size=size.tolist(),slider_size=[.01,height,.03],slider_origin=origin.tolist(),slider_initial_center=(origin+[0,0,meta['joint_lower']]).tolist(),masses=masses,urdf_sha256=sha,generation_seed=2026100467,scope='Freshphysicalchallenge; authored constantdensity cuboidmass/inertia approximation, notrealmeasurements. ExistingmeshYscaled for2--4mm height. Physicalmetadata only sensor generator/simulator, not actor.');(dest/'parameters.json').write_text(json.dumps(params,indent=2));out=O/sid;out.mkdir();observed=size+rng.uniform(-1,1,3)*[.00025,.00025,.0005];delta=origin-[0,.0075,.010624586881962734];delta[1]-=(size[1]-.012)/2;delta[1]+=(height-.003)/2;delta+=rng.uniform(-.00025,.00025,3);estimate={'handle_size_WTL_m':observed.tolist(),'slider_size_WTL_m':[.01,height+float(rng.uniform(-.0001,.0001)),.03],'slider_contact_shift_m':delta.tolist(),'initial_object_center_shift_knife_m':[0,float((observed[1]-.012)/2),0],'uncertainty_m':.00025,'source':'Labelled noisy simulated onceinitial size/contact observation, no connectedrealvision; privatephysicalmetadata used only sensor generator, no planner/actorID'};(out/'estimate.json').write_text(json.dumps(estimate,indent=2));adapted=adapt_two_stage(estimate,scene['plan'],op0,ref0);motor=project_self(adapted['motor_plan']);motor=project_all(motor,loc) if motor['initial_motor_self_projection']['passed'] else motor;(out/'motor-plan.json').write_text(json.dumps(motor,indent=2));valid=motor['initial_motor_self_projection']['passed'] and motor.get('common_initial_table_projection',{}).get('passed',False);checks=[]
 if valid:
  op=copy.deepcopy(op0);op.update(close_q=motor['post_lift_close_q'],initial_geometry_estimate=estimate);(out/'operating-plan.json').write_text(json.dumps(op,indent=2));commands=[('acquisition',['-m','scripts.audit_wuji_actual_acquisition_motor','--plan',str(out/'motor-plan.json'),'--acquisition',str(B/'pickup-plans-v1/opposed/lateral-acquisition/acquisition-path.json'),'--output',str(out/'acquisition-audit.json')]),('transfer',['-m','scripts.audit_wuji_pickup_preload','--plan',str(out/'motor-plan.json'),'--localization',str(B/'pickup-plans-v1/opposed/localization.json'),'--output',str(out/'transfer-audit.json')]),('thumbplan',['-m','scripts.plan_g2_direct_thumb_motor_stroke','--plan',str(out/'operating-plan.json'),'--output',str(out/'reference.json')]),('thumbdense',['-m','scripts.audit_g2_anchored_thumb_motor','--reference',str(out/'reference.json'),'--motor-plan',str(out/'motor-plan.json'),'--knife-spec','research/robust-knife-family-20261003/real-knife-asset-spec.json','--samples','161','--output',str(out/'motor-audit.json')])]
  for label,args in commands:
   code=subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name','fresh-%s-%s-v1'%(sid,label),'--',PY]+args).returncode;checks.append({'stage':label,'exit_code':code})
   if code:valid=False;break
 row={'instance_physics_only':sid,'asset':str(dest/'mobility.urdf'),'asset_sha256':sha,'estimate':estimate,'condition':condition,'geometry_passed':valid,'checks':checks,'directory':str(out)};rows.append(row);(O/'manifest.json').write_text(json.dumps({'preregistration':prereg,'rows':rows,'scope':'Preparation only; no actorrollout opened'},indent=2));record('fresh_joint_challenge_geometry_prepared',config={'asset_sha256':sha,'geometry_passed':valid,'condition':condition},evidence=str(out),next='Keepallfour cases; freezecandidate before anyphysicalvalidation, no replanning based onoutcome')
record('fresh_joint_challenges4_preparation_completed',config={'cases':4,'geometry_passed':sum(r['geometry_passed'] for r in rows)},evidence=str(O/'manifest.json'),next='Freeze finalselectedcandidate fromdevelopment only, thenexecuteexact4 jointchallenge conditions/countallfailures')
