"""Pure lateral index contact candidate, same original actual pickup and thumb path."""
import json,subprocess
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');P=B/'continuous-plans-v3/table-index-side';PY='/home/agiuser/miniconda3/envs/artgym/bin/python'
base=json.loads((B/'pickup-plans-v1/opposed/table-support-projected-motor-plan-v6-retry1.json').read_text());op=json.loads((P/'operating-motor-plan-v1.json').read_text());assert op['equilibrium_audit']['original_motor_self_geometry_passed'];base.update(post_lift_close_q=op['close_q'],post_lift_preload_seconds=[12,14],post_lift_hand_height_m=.10,post_lift_preparation_scope='Knownpostlift purelateral indexnormal .4Nnominalhypothesis; otherfinger targets unchanged, not measuredforce/currentobjectfeedback');plan=P/'continuous-motor-plan-v1.json';assert not plan.exists();plan.write_text(json.dumps(base,indent=2))
def run(name,args):subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--',PY]+args,check=True)
run('actual-table-index-side-preparation-audit-v1',['-m','scripts.audit_wuji_pickup_preload','--plan',str(plan),'--localization',str(B/'pickup-plans-v1/opposed/localization.json'),'--output',str(P/'preparation-audit-v1.json')])
run('actual-table-index-side-full-thumb-motor-audit-v1',['-m','scripts.audit_g2_anchored_thumb_motor','--reference',str(B/'continuous-plans-v1/opposed-table-strong/interpolation-repaired-reference-v5.json'),'--motor-plan',str(plan),'--knife-spec','research/robust-knife-family-20261003/real-knife-asset-spec.json','--samples','81','--output',str(P/'full-thumb-motor-audit-v1.json')])
a=json.loads((B/'jobs/opposed-table-strong-continuous-2cycles-v4/identity.json').read_text())['command'][1:];trial=B/'continuous/actual-table-index-side-2cycles-v6';a[a.index('--output')+1]=str(trial);a[a.index('--grasp-plan')+1]=str(plan);run('actual-table-index-side-continuous-2cycles-v6',a);run('actual-table-index-side-functional-evaluation-v6',['-m','scripts.evaluate_wuji_antirotation','--trial',str(trial)]);record('actual_table_index_side_candidate_completed',evidence=str(trial),next='Inspectactualcontact/endpoints, no unchangedsidepressure extension iffails; directtangential motorpath diagnosis maincontrolpriority')
