"""Substantively new fullclosure/knownsupport curriculum, long interaction horizon.
Geometric bank prepared before physical qualification; no best-test selection.
"""
import json,time,subprocess,os,signal,hashlib
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');D=Path('research/antirotation-grasp-20261004');G=B/'common-geometry-bank16-v1';C=B/'strict-geometry-learned-prefix-v1';PY='/home/agiuser/miniconda3/envs/artgym/bin/python'
while not (G/'outcomes.json').exists() or len(json.loads((G/'outcomes.json').read_text()))<16:time.sleep(5)
results=json.loads((G/'outcomes.json').read_text());assert all(r['passed'] for r in results),'Do not silently remove any necessarybank shape; inspect rejection'
C.mkdir(exist_ok=False);scene=json.loads((D/'projected-real-nominal-training-scene-v3.json').read_text());records=json.loads((G/'records.json').read_text());ids=json.loads((G/'physical-schedule-templates.json').read_text())['instances'];scene.update(initial_estimated_plans=records,repeat_initial_estimate_templates=True,resample_initial_estimates=True,scheduled_support_anchor=True,learned_acquisition_prefix=True);(C/'scene16.json').write_text(json.dumps(scene,indent=2));registry=json.loads((D/'PHYSICAL-TRAIN-GEOMETRY.json').read_text());(C/'registry.json').write_text(json.dumps(registry,indent=2))
for n in [16,1024]:(C/('schedule%d.json'%n)).write_text(json.dumps({'instances':ids*(n//16),'scope':'Physicaltrain loading only, no actorID'},indent=2))
name='strict16-known-prefix-zero-residual-compatibility-v17';out=C/'zero-residual-qualification';args=['-m','scripts.probe_wuji_antirotation_module','--scene',str(C/'scene16.json'),'--reference',str(B/'initial-geometry-v2/projected-00/reference-v1.json'),'--asset-registry',str(C/'registry.json'),'--geometry-schedule',str(C/'schedule16.json'),'--envs','16','--takeover-seconds','5','--output',str(out)]
record('strict_geometry_prefix_physical_qualification_started',config={'templates':16,'physical_geometries':8,'takeover_s':5,'controller':'Zero boundedresidual/fullknownclosure andhandoff, originalassets/physics','scope':'Trainqualification, not independentvalidation'},evidence=str(C),next='Require genuineactualnominal/thin/thick support across originaldensequalifiedtemplates before newPPO')
subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--',PY]+args,check=True);rows=json.loads((out/'report.json').read_text())['episodes'];summary={'n':len(rows),'pickup':sum(r['pickup_valid'] for r in rows),'fall':sum(r['fall'] for r in rows)};(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');record('strict_geometry_prefix_physical_qualification_closed',config=summary,evidence=str(out),next='Retainallqualifiedphysicalcases/failures; no scene filtering by score')
assert all(any(r['instance']==sid and r['pickup_valid'] and not r['fall'] for r in rows) for sid in ['t0000','t0001','t0002']), 'Rejectlayout if nominal/thin/thick neveractuallysupport; no unchanged training'
name='strict16-learned-closure-longhorizon-reset750-v6';args=json.loads((B/'jobs/actual-three-geometry-retain750-curriculum-v5/identity.json').read_text())['command'];values={'--output':str(B/'train'/name),'--envs':'1024','--updates':'100','--horizon':'512','--initial-estimate-scene':str(C/'scene16.json'),'--training-geometry-schedule':str(C/'schedule1024.json'),'--training-asset-registry':str(C/'registry.json'),'--takeover-seconds':'5','--seed':'2026100463'}
for k,v in values.items():args[args.index(k)+1]=v
args+=['--reset-residual-head','--gae-lambda','.995'];record('strict_geometry_learned_closure_new_pilot_started',config={'envs':1024,'horizon':512,'max_updates':100,'freeze_check':50,'scope':'New 5s actualclosure and reachable knownhandoff, 8physicalgeometries/16noisyestimates, long17s interaction horizon and .995GAE, zerohead around knowngeometry. No unchanged failed16s extension, no currenttruth actorinput.'},evidence=str(B/'train'/name),next='Frozen50 actualnominal/thin fullcontinuous trials; stop safely if both remain nonfunctional; heightcasesprepared separately')
train=subprocess.Popen([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--']+args);weight=B/'train'/name/'update_000050.pth'
while not weight.exists():
 assert train.poll() is None,'Training stoppedbeforefrozen50';time.sleep(5)
time.sleep(2);evaluated=[]
for source,label,version in [('actual-table-projected-grasp-frozen750-load2-v17','nominal','v28'),('actual-table-thin-allcontact-frozen750-load2-v24','thin','v29')]:
 name2='actual-table-'+label+'-learned-prefix-frozen50-load2-'+version;trial=B/'continuous'/name2;cmd=json.loads((B/'jobs'/source/'identity.json').read_text())['command'];cmd[cmd.index('--output')+1]=str(trial);cmd[cmd.index('--residual-checkpoint')+1]=str(weight);cmd+=['--takeover-seconds','5']
 subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name2,'--']+cmd,check=True);subprocess.run([PY,'-m','scripts.evaluate_wuji_antirotation','--trial',str(trial)],check=True);evaluated.append(json.loads((trial/'functional-evaluation.json').read_text()))
if not any(r['continuous_pickup_demo_pass'] for r in evaluated):
 identity=json.loads((B/'jobs'/name/'identity.json').read_text());os.kill(identity['pid'],signal.SIGTERM);record('new_closure_geometry_frozen50_no_functional_improvement_stop',config={'pid':identity['pid'],'signal':'SIGTERM boundary model/Adam/RNG save','scope':'No unchangedextension after actualnominal/thin checks; endpoint decimalsnotoptimized'},evidence=str(C),next='Use mechanism/failure evidence for heightdevelopment ordeliverblocking; retain V17 frozen750 bestnominal')
code=train.wait();assert code==0;record('strict_geometry_learned_closure_pilot_closed',evidence=str(B/'train'/name),next='Inspect completedcheckpoint/hash andactualbehavior; jointheightchallenge notcanceled orclaimedsolved')
