"""Matched newprefix range contrast with phase-correct legal onceinitial priors."""
import json,subprocess,time,hashlib
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');old=B/'strict-geometry-learned-prefix-v1';C=B/'strict-geometry-table-prior-prefix-v2';C.mkdir(exist_ok=False);PY='/home/agiuser/miniconda3/envs/artgym/bin/python';scene=json.loads((old/'scene16.json').read_text());scene['table_initial_prior_from_measured_arm']=True;(C/'scene16.json').write_text(json.dumps(scene,indent=2));name='correct-table-prior-zero-residual-qualification16-v19';cmd=json.loads((B/'jobs/strict16-known-prefix-zero-residual-compatibility-v17/identity.json').read_text())['command'];cmd[cmd.index('--scene')+1]=str(C/'scene16.json');cmd[cmd.index('--output')+1]=str(C/'qualification');record('correct_table_prior_prefix_physical_qualification_started',config={'scope':'One16 fullphysicalscene qualification plus recorded legalinitialpose estimates; knownworldtable/once noisyshape/measuredarmFK only, no liveobject/slider input. Old heldprior16s mode unchanged.'},evidence=str(C),next='Check inputshapes/trueprefix andphase-coordinate parity before matched50 training')
subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--']+cmd,check=True);rows=json.loads((C/'qualification/report.json').read_text())['episodes'];assert all(any(r['instance']==sid and r['pickup_valid'] and not r['fall'] for r in rows) for sid in ['t0000','t0001','t0002']);record('correct_table_prior_prefix_physical_qualification_closed',config={'n':len(rows),'pickup':sum(r['pickup_valid'] for r in rows),'fall':sum(r['fall'] for r in rows)},evidence=str(C/'qualification'),next='Matched50 support-range pilot with phase-correct initialfeatures, newmodel/Adam/RNG; no unchanged oldprior extension')
trains=[]
for span,scale,version in [('.04','.025','v8'),('.12','.1','v9')]:
 label='range04' if span=='.04' else 'range12';name='strict16-table-prior-closure-longhorizon-'+label+'-reset750-'+version;a=json.loads((B/'jobs/strict16-learned-closure-longhorizon-reset750-v6/identity.json').read_text())['command'];values={'--output':str(B/'train'/name),'--updates':'50','--initial-estimate-scene':str(C/'scene16.json'),'--known-support-span':span,'--support-residual-scale':scale}
 for k,v in values.items():a[a.index(k)+1]=v
 record('phase_correct_prefix_range_matched_pilot_started',config={'label':label,'envs':1024,'horizon':512,'updates':50,'transitionbudget':26214400,'seed':2026100463,'initialization':'750backbone/critic, residualheadzero, freshAdam','scope':'Two supporttarget range/rate contrasts on same originalphys/commongeometry/material/sensor/delay/passiveresistance and correctonceinitialtableframe. No identicalRL/filler or constantforce; no liveobjectinput.'},evidence=str(B/'train'/name),next='Freeze50 actualnominal/thin fullcontinuousbehavior, no smaller-angle/endpoint tuning; all oldstartup-assumption pilots preserved')
 train=subprocess.Popen([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--']+a);trains.append((label,name,train))
for label,name,train in trains:
 code=train.wait();assert code==0;weight=B/'train'/name/'update_000050.pth';assert weight.exists()
 for source,kind,version in [('actual-table-projected-grasp-frozen750-load2-v17','nominal','v32' if label=='range04' else 'v34'),('actual-table-thin-allcontact-frozen750-load2-v24','thin','v33' if label=='range04' else 'v35')]:
  name2='actual-table-'+kind+'-table-prior-'+label+'-frozen50-load2-'+version;trial=B/'continuous'/name2;cmd=json.loads((B/'jobs'/source/'identity.json').read_text())['command'];cmd[cmd.index('--output')+1]=str(trial);cmd[cmd.index('--residual-checkpoint')+1]=str(weight);cmd+=['--takeover-seconds','5'];subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name2,'--']+cmd,check=True);subprocess.run([PY,'-m','scripts.evaluate_wuji_antirotation','--trial',str(trial)],check=True)
 record('phase_correct_prefix_range_matched_pilot_closed',config={'label':label,'weight_sha256':hashlib.sha256(weight.read_bytes()).hexdigest(),'scope':'Training andtwo developmentchecks only; independent4 challenges remainunopened'},evidence=str(B/'train'/name),next='Use paireddevelopment functionalbehavior toselectone frozencandidate before exactfreshjointchallenges; retain old750 ifneitherqualifies')
record('correct_table_prior_range_pair_pipeline_closed',evidence=str(C),next='Necessaryraisedslider development/freshjointvalidation and genuineweights/code/video Release, no realrobot actions')
