"""Actual lower lateral lever plus complete tangential motor path, original physics."""
import json,subprocess
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');P=B/'continuous-plans-v5/table-lower-side-index';PY='/home/agiuser/miniconda3/envs/artgym/bin/python';ref=B/'continuous-plans-v4/direct-tangential/reference-v1-retry1.json'
base=json.loads((B/'pickup-plans-v1/opposed/table-support-projected-motor-plan-v6-retry1.json').read_text());op=json.loads((P/'operating-motor-plan-v1.json').read_text());assert op['equilibrium_audit']['original_motor_self_geometry_passed'];base.update(post_lift_close_q=op['close_q'],post_lift_preload_seconds=[12,14],post_lift_hand_height_m=.10,post_lift_preparation_scope='Knownpostlift lower-side lateral index contact, nominal .8N hypothesis, increased4.5mm knife-long-axis roll lever; otherfinger targets unchanged. Actualforce andstability unverified, no runtime object/contact trigger');plan=P/'continuous-motor-plan-v1.json';assert not plan.exists();plan.write_text(json.dumps(base,indent=2))
def run(name,args):subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--',PY]+args,check=True)
run('actual-table-lower-side-preparation-audit-v1',['-m','scripts.audit_wuji_pickup_preload','--plan',str(plan),'--localization',str(B/'pickup-plans-v1/opposed/localization.json'),'--output',str(P/'preparation-audit-v1.json')])
run('actual-table-lower-side-direct-full-motor-audit-v1',['-m','scripts.audit_g2_anchored_thumb_motor','--reference',str(ref),'--motor-plan',str(plan),'--knife-spec','research/robust-knife-family-20261003/real-knife-asset-spec.json','--samples','81','--output',str(P/'full-thumb-motor-audit-v1.json')])
a=json.loads((B/'jobs/actual-table-direct-motor-continuous-2cycles-v7/identity.json').read_text())['command'][1:];trial=B/'continuous/actual-table-lower-side-direct-2cycles-v11';a[a.index('--output')+1]=str(trial);a[a.index('--grasp-plan')+1]=str(plan);assert a[a.index('--thumb-script')+1]==str(ref);run('actual-table-lower-side-direct-continuous-2cycles-v11',a);run('actual-table-lower-side-direct-functional-evaluation-v11',['-m','scripts.evaluate_wuji_antirotation','--trial',str(trial)]);record('actual_table_lower_side_direct_candidate_completed',evidence=str(trial),next='Readactualnormalcontact, cumulativeZroll andtwo-cycle endpoints; necessarygen/loadedretraction stillrequires evidence, no pass fromgeometry')
