"""One actual new-prefix legal replay and one material checkpoint resume update."""
import hashlib,json,subprocess,time
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');PY='/home/agiuser/miniconda3/envs/artgym/bin/python';name='strict16-table-prior-closure-longhorizon-range04-reset750-v8';weight=B/'train'/name/'update_000050.pth';trial=B/'continuous/actual-table-nominal-table-prior-range04-frozen50-load2-v32';out=B/'newprefix-recovery-v1';out.mkdir(exist_ok=False)
while not (trial/'functional-evaluation.json').exists():time.sleep(5)
# Interface replay is valid evidence even if the policy fails the task.
plan=B/'initial-geometry-v2/projected-00/motor-plan.json';export=out/'legal-export';replay=out/'replayed'
for label,cmd in [('export',[PY,'-m','scripts.export_wuji_legal_replay','--trial',str(trial),'--motor-plan',str(plan),'--output',str(export),'--takeover-seconds','5']),('replay',[PY,'-m','research.antirotation-grasp-20261004.profile_prewarmed_replay','--timing-output',str(out/'timing.json'),'--input',str(export/'legal-input.npz'),'--estimate',str(export/'estimate.json'),'--motor-prefix-plan',str(export/'motor-plan.json'),'--calibration',str(B/'continuous-plans-v6/lower-side-calibrated/nominal-calibration.json'),'--reference',str(B/'initial-geometry-v2/projected-00/reference-v1.json'),'--checkpoint',str(weight),'--output',str(replay),'--takeover-seconds','5','--prewarm-iterations','8'])]:
    code=subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name','newprefix-recovery-'+label+'-v1','--']+cmd).returncode
    if code:raise RuntimeError('Recovery '+label+' failed; preserve log and diagnose before command equivalence claim')
r=json.loads((replay/'report.json').read_text());record('newprefix_actual_legal_replay_closed',config={'frames':r['command_frames'],'maximum_command_difference_rad':r['max_target_difference_from_recorded_rad'],'checkpoint_sha256':r['checkpoint_sha256'],'scope':'Actual5s native measured/issued trace replay with separate knownplan reference. No successor SDK claim.'},evidence=str(replay),next='Requirecommanddifference<=2e-6rad; diagnose interface if failed, then one actualmaterialresume update')
assert r['max_target_difference_from_recorded_rad']<2e-6
cmd=json.loads((B/'jobs'/name/'identity.json').read_text())['command'];cmd[cmd.index('--output')+1]=str(out/'resumed');cmd[cmd.index('--updates')+1]='51';i=cmd.index('--initialize-model-from');del cmd[i:i+2];cmd.remove('--reset-residual-head');cmd+=['--resume',str(weight)]
record('newprefix_material_checkpoint_resume_started',config={'checkpoint_sha256':hashlib.sha256(weight.read_bytes()).hexdigest(),'updates':'50->51','scope':'Actual same1024/horizon512 oneupdate with model/Adam/CPU-CUDA-NumPy/per-scene RNG restoration and newphysicalepisodes; not bitwise solver continuation or additional trainingpromotion'},evidence=str(out/'resumed'),next='Check actual51weight/checkpointmetadata; preserve allrecoverylogs')
subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name','newprefix-material-resume-update51-v1','--']+cmd,check=True)
new=out/'resumed/update_000051.pth';assert new.exists();receipt={'input_checkpoint':str(weight),'input_sha256':hashlib.sha256(weight.read_bytes()).hexdigest(),'output_checkpoint':str(new),'output_sha256':hashlib.sha256(new.read_bytes()).hexdigest(),'scope':'One actual trainingupdate resumes material optimizer/RNG, begins new episodes; frozen50candidate remainsunchanged,51neverpromotedbyrecovery.'};(out/'resume-receipt.json').write_text(json.dumps(receipt,indent=2));record('newprefix_material_checkpoint_resume_closed',config=receipt,evidence=str(out/'resume-receipt.json'),state_updates={'newprefix_recovery_pipeline_pid':None},next='Deliver recoverable50weight/config/commands and interface limits withouttruehardwareclaim')
