"""Matched first50 adaptation for physicallyqualified larger software support range."""
import json,time,subprocess
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');C=B/'strict-geometry-learned-prefix-v1';PY='/home/agiuser/miniconda3/envs/artgym/bin/python';r=json.loads((C/'span12-zero-residual-qualification/report.json').read_text())['episodes'];assert all(any(x['instance']==sid and x['pickup_valid'] and not x['fall'] for x in r) for sid in ['t0000','t0001','t0002']);name='strict16-learned-closure-longhorizon-span12-reset750-v7';a=json.loads((B/'jobs/strict16-learned-closure-longhorizon-reset750-v6/identity.json').read_text())['command'];a[a.index('--output')+1]=str(B/'train'/name);a[a.index('--updates')+1]='50';a[a.index('--known-support-span')+1]='.12';a[a.index('--support-residual-scale')+1]='.1'
record('larger_support_newprefix_matched_pilot_started',config={'envs':1024,'horizon':512,'updates':50,'physicaltemplates':16,'support_span_rad':.12,'support_residual_scale_rad':.1,'support_step_rad':.025,'scope':'Same first50 transitionbudget/seed/headinitialization/load/sensor/geometry as .04range control, originalphysical PD/torque/gravity. Change softwaretarget range/rate only. No identicalRL/filler and no constantforceclaim.'},evidence=str(B/'train'/name),next='Frozen50 actualnominal/thin fullcontinuous check; stop atpredeclared50 regardless, no finer range sweep')
subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--']+a,check=True);weight=B/'train'/name/'update_000050.pth'
for source,label,version in [('actual-table-projected-grasp-frozen750-load2-v17','nominal','v30'),('actual-table-thin-allcontact-frozen750-load2-v24','thin','v31')]:
 name2='actual-table-'+label+'-learned-prefix-span12-frozen50-load2-'+version;trial=B/'continuous'/name2;cmd=json.loads((B/'jobs'/source/'identity.json').read_text())['command'];cmd[cmd.index('--output')+1]=str(trial);cmd[cmd.index('--residual-checkpoint')+1]=str(weight);cmd+=['--takeover-seconds','5'];subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name2,'--']+cmd,check=True);subprocess.run([PY,'-m','scripts.evaluate_wuji_antirotation','--trial',str(trial)],check=True)
record('larger_support_newprefix_matched_pilot_closed',evidence=str(B/'train'/name),next='Compare completefunctionalbehavior/mechanics with equalbudget control, no angle/endpoint decimalsoptimization. Jointheight challenge remains explicit.')
