"""One structurally different ring-brace candidate, original gates before physics."""
import copy,hashlib,json,subprocess
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');C=B/'postlift-ring-brace-v1';PY='/home/agiuser/miniconda3/envs/artgym/bin/python';raw=json.loads((C/'motor-plan.json').read_text());original=json.loads((B/'initial-geometry-v2/projected-00/motor-plan.json').read_text())
# Stage metadata only, derived new file preserves solver output/actual targets.
plan=copy.deepcopy(raw);plan['active_fingers']=original['active_fingers'];plan['excluded_fingers']=original.get('excluded_fingers',['ring']);plan['post_lift_active_fingers']=['thumb','index','middle','ring','pinky'];plan['post_lift_ring_contact_point_knife_m']=plan['post_lift_ring_brace']['touch_point_knife_m'];(C/'motor-plan-staged.json').write_text(json.dumps(plan,indent=2))
for key in ['open_q','touch_q','close_q','close_waypoints','wrist_in_knife']:assert plan[key]==original[key]
record('distinct_postlift_ring_geometry_endpoint_passed',config={'geometry':json.loads((C/'geometry-audit.json').read_text()),'pickup_original_plan_sha256':hashlib.sha256((B/'initial-geometry-v2/projected-00/motor-plan.json').read_bytes()).hexdigest(),'unchanged_pickup_targets':['open_q','touch_q','close_q','close_waypoints','wrist_in_knife'],'scope':'Original73pickupgeometry certificate reused onlyforbyte-equivalentinitialtargets. Newring enters12--14afterlift; metadata corrected inderivedfile, rawsolveroutput retained.'},evidence=str(C/'motor-plan-staged.json'),next='Changedtransfer21 andfullthumb161 originalgates, no physicalcommandifreject')
commands=[('transfer',[PY,'-m','scripts.audit_wuji_pickup_preload','--plan',str(C/'motor-plan-staged.json'),'--localization',str(B/'pickup-plans-v1/opposed/localization.json'),'--output',str(C/'transfer-audit.json')]),('fullstroke',[PY,'-m','scripts.audit_g2_anchored_thumb_motor','--reference',str(B/'initial-geometry-v2/projected-00/reference-v1.json'),'--motor-plan',str(C/'motor-plan-staged.json'),'--knife-spec','research/robust-knife-family-20261003/real-knife-asset-spec.json','--samples','161','--output',str(C/'fullstroke-audit.json')])]
for label,cmd in commands:
    code=subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name','postlift-ring-brace-'+label+'-v1','--']+cmd).returncode
    if code:
        record('distinct_postlift_ring_brace_candidate_rejected',config={'stage':label,'scope':'Onefixedtopology/path failsoriginalgeometry, no relax/reroll/physicalrun orparametergrid'},evidence=str(C),state_updates={'postlift_ring_brace_pipeline_pid':None},next='Retainrejection andstopcandidate; complete pairedfreeze/freshcases/Release');raise SystemExit(0)
name='actual-table-postlift-ring-brace-frozen750-load5-v36';cmd=json.loads((B/'jobs/actual-table-projected-grasp-frozen750-load5-v18/identity.json').read_text())['command'];cmd[cmd.index('--grasp-plan')+1]=str(C/'motor-plan-staged.json');cmd[cmd.index('--output')+1]=str(B/'continuous'/name)
record('distinct_postlift_ring_brace_physical_comparison_started',config={'actor':'unchanged750','load':.5,'detent':.5,'scope':'Onepairedsame-V18geometry/estimate/seed/material/passivecapacity/PD/gravity actual36s; onlyoppositeloweredge ringbrace known12--14reference changes. Allcontacts/freeobject realphysical, no liveforce/pose input, no fixedfreshselector modification.'},evidence=str(B/'continuous'/name),next='Fulltwo-cyclebehavior andexactring/sliderpairforce evidence; no nominalsuccessrate/gain sweep')
code=subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--']+cmd).returncode
if code==0:code=subprocess.run([PY,'-m','scripts.evaluate_wuji_antirotation','--trial',str(B/'continuous'/name)]).returncode
result=json.loads((B/'continuous'/name/'functional-evaluation.json').read_text()) if code==0 else {'execution_failed':True};record('distinct_postlift_ring_brace_physical_comparison_closed',config=result,evidence=str(B/'continuous'/name),state_updates={'postlift_ring_brace_pipeline_pid':None},next='Ifnomeaningfulbenefitstop; ifphysicalimprovementcheckcommononceestimatedmorphology beforeanypromotion. Existingfresh4actor/mechanicsfreeze remainsunchanged.')
