"""One capped50 actual-contact-direction comparison on the new mechanics."""
import json,subprocess,time
from pathlib import Path
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');PY='/home/agiuser/miniconda3/envs/artgym/bin/python';joint='actual-lower-side-fullmotor-joint-reset750-v2';name='actual-lower-side-fullmotor-contactnormal-reset750-v3';result=B/'jobs'/joint/'result.json'
while not result.exists():time.sleep(5)
assert json.loads(result.read_text())['exit_code']==0
a=json.loads((B/'jobs'/joint/'identity.json').read_text())['command'][1:];a[a.index('--output')+1]=str(B/'train'/name);a[a.index('--updates')+1]='50';a+=['--support-delta-coordinates','contact-normal'];record('new_actual_contact_direction_pilot_started',config={'name':name,'max_updates':50,'change':'Explicit index side inwardX vs middle/pinky bottom inwardY in onceestimatedknife frame; same new actualpickup/fullmotor/contact topology, no old frozen supportprior, no currenttruth'},next='One frozen50 actualcontinuous behavior check; do not extend without behavior change');subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',name,'--',PY]+a,check=True)
a=json.loads((B/'jobs/actual-table-lower-side-calibrated-direct-continuous-2cycles-v12/identity.json').read_text())['command'][1:];trial=B/'continuous/actual-lower-side-fullmotor-contactnormal-frozen50-nominal-v3';i=a.index('--thumb-script');a[i:i+2]=['--residual-checkpoint',str(B/'train'/name/'update_000050.pth')];a[a.index('--output')+1]=str(trial);subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',trial.name,'--',PY]+a,check=True);subprocess.run([PY,'-m','scripts.run_wuji_antirotation_job','--name',trial.name+'-functional','--',PY,'-m','scripts.evaluate_wuji_antirotation','--trial',str(trial)],check=True);record('new_contact_direction_pilot_and_frozen_behavior_completed',evidence=str(trial),state_updates={'contact_normal_pipeline_pid':None},next='Mechanical/common noisy initial geometry vs learned corrections from actual behavior; no automatic unchanged extension')
