"""Immutable newpilot weights and compact frozen50 developmental behavior."""
import json,hashlib
from pathlib import Path
from scripts.evaluate_wuji_antirotation import evaluate
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');rows=[]
for variant in ['span04-reset750','span12-reset750','span12-retain750','span12-fresh']:
 name='actual-table-loaded-'+variant+'-v1';train=B/'train'/name;job=json.loads((B/'jobs'/name/'result.json').read_text());assert job['exit_code']==0;learning=[json.loads(x) for x in (train/'learning.jsonl').read_text().splitlines()];last=learning[-1];hashes={}
 for update in [50,100]:
  f=train/('update_%06d.pth'%update);sha=hashlib.sha256(f.read_bytes()).hexdigest();assert sha==f.with_suffix('.sha256').read_text().strip();hashes[str(update)]=sha
 frozen=name.replace('-v1','-frozen50-nominal-v1');result=json.loads((B/'jobs'/frozen/'result.json').read_text());assert result['exit_code']==0;trial=B/'continuous'/frozen;ev=evaluate(trial);(trial/'functional-evaluation.json').write_text(json.dumps(ev,indent=2));report=json.loads((trial/'report.json').read_text());row=dict(variant=variant,checkpoint_sha256=hashes,final_update=last['update'],training_transitions=last['transitions'],training_episodes=last['episodes'],training_full_complete_count=last['all_complete_count'],frozen50_functional=ev,frozen50_pressure=report['pair_pressure']);rows.append(row)
 record('remote_actual_workflow_training_completed',closed_job={'machine':'remote','name':name},evidence=[str(train),str(B/'jobs'/name/'result.json')],config={'updates':last['update'],'transitions':last['transitions'],'weight_sha256':hashes},conclusion='Finite100updates completed. Trainingonly fitting, nofullcomplete episodes; do notextendunchanged. Fulloptimizer/RNG checkpoint retained.',next='Use firstcycle directmotor+support progress to fix cumulative rotation geometry; newreference training onlyafteractualphysicalmechanism improves')
 record('remote_actual_frozen50_native_completed',closed_job={'machine':'remote','name':frozen},evidence=str(trial),config={'checkpoint_sha256':hashes['50'],'endpoints_m':ev['slider_endpoints_m'],'functional_pass':ev['functional_behavior_pass'],'thumb_contact_fraction':ev['thumb_contact_substep_fraction']},conclusion='Actual36s frozennominaldevelopment check; all maintaincontact/hold, nofullfunctionalpass becauseextension~21mm. Retain750 returns~5mm, a realreturn benefitbutnotnecessarygeneralization.',next='No unchangedlongtraining; use newfunctional geometry anddirectmotor pathmechanism')
out=B/'actual-table-training-v1/frozen50-comparison.json';out.write_text(json.dumps(dict(scope='Newactualcontinuouspilot fitting andfrozennominaldevelopment checks; never independentgen orrealrobot',rows=rows),indent=2));print(json.dumps([{k:r[k] for k in ['variant','final_update','training_transitions','checkpoint_sha256']} for r in rows]));record('new_actual_workflow_pilot_comparison_persisted',evidence=str(out),state_updates={'actual_table_integration_pipeline_pid':None},next='Lower-side rolllever contact anddirectfullmotor trajectory physicalintegration; retain100weights/recovery butno unchangedextension')
