"""Known native schedule versus vector reference, original target memory."""
from isaacgym import gymapi
import json,hashlib,numpy as np,torch
from pathlib import Path
from scripts.wuji_scheduled_thumb_reference import ScheduledThumbReference
from scripts.wuji_known_controller import KnownWujiController
from scripts.g2_contact_geometry import DigitGeometry
from scripts.record_wuji_antirotation_goal import record
B=Path('runs/antirotation-grasp-20261004');D=B/'bidirectional-motor-preload-v1';audit=json.loads((D/'dense-blend-audit-v1.json').read_text());assert audit['all_passed'];spec=json.loads((D/'reference-v1.json').read_text());spec['reverse_motor_preload'].update(geometry_passed=True,geometry_audit=str(D/'dense-blend-audit-v1.json'),geometry_audit_sha256=hashlib.sha256((D/'dense-blend-audit-v1.json').read_bytes()).hexdigest());out=D/'certified-reference-v2.json';assert not out.exists();out.write_text(json.dumps(spec,indent=2));g=DigitGeometry();plan=json.loads((B/'initial-geometry-v2/projected-00/motor-plan.json').read_text());q=torch.tensor([plan['post_lift_close_q']]*2,dtype=torch.float32);known=KnownWujiController(torch.tensor(g.w.lower,dtype=torch.float32),torch.tensor(g.w.upper,dtype=torch.float32),2);known.reset(torch.tensor([0,1]),q);r=ScheduledThumbReference(spec,2,'cpu');r.reset(torch.tensor([0,1]),clock_s=16.);shifts=np.array([x['shift_m'] for x in spec['rows']]);f=np.array([x['q_thumb'] for x in spec['rows']]);back=np.array([x['q_thumb'] for x in spec['reverse_rows']]);errors=[];peak=0.;commands=[]
def smooth(u):return u**3*(10-15*u+6*u*u)
for i in range(600):
 phase=i//150;t=i/30;elapsed=(i%150)/30;goal=.04 if phase%2==0 else 0.;a=r.action(known.initial,known.issued,torch.tensor([[goal],[goal]]),clock_s=16+t);u=smooth(min(elapsed/4,1));shift=.04*(u if phase%2==0 else 1-u);progress=smooth(min(elapsed/.75,1));weight=(progress if phase%2 else 1-progress) if phase else 0.;expected=np.array([np.interp(shift,shifts,f[:,j]) for j in range(4)])*(1-weight)+np.array([np.interp(shift,shifts,back[:,j]) for j in range(4)])*weight;expected+=q[0,16:].numpy()-f[0];errors.append(float(abs(r.last_target[0,16:].numpy()-expected).max()));assert (r.last_target[0]-r.last_target[1]).abs().max()<1e-7
 before=known.issued.clone();issued=known.step(a);peak=max(peak,float((issued[:,16:]-before[:,16:]).abs().max()));assert (issued>=known.lower-1e-7).all() and (issued<=known.upper+1e-7).all();assert peak<.025002;commands.append(issued[0].numpy().copy())
assert max(errors)<3e-6,max(errors);previous=r.reverse_weight[0].clone();r.reset(torch.tensor([1]),clock_s=16.);assert r.reverse_weight[0]==previous and r.reverse_weight[1]==0;np.savez_compressed(D/'offline-issued-command-check.npz',issued=np.array(commands));result=dict(scope='Offline common direction schedule/native-equivalent target and actual original bounded command memory only; no physics/force success',maximum_native_vector_reference_difference_rad=max(errors),maximum_actual_thumb_step_rad=peak,partial_reference_reset_passed=True,certified_reference_sha256=hashlib.sha256(out.read_bytes()).hexdigest());(D/'offline-command-check.json').write_text(json.dumps(result,indent=2));print(json.dumps(result));record('bidirectional_known_schedule_original_command_check_passed',evidence=str(D),config=result,next='Fresh actual table/roll loaded two-cycle physics, samecriteria and originalgravity/rail; no forcecontrol or currenttruth')
