defaults:
  - artmanipSAPGPrivLSTMPPO
  - _self_
params:
  config:
    learning_rate: 0.0002
    expl_coef_block_size: 1024
    minibatch_size: 10240
    horizon_length: 16
    seq_length: 16
    managed_checkpoints: true
    save_frequency: 100
    checkpoint_first_epoch: 20
    checkpoint_keep_recent: 8
    checkpoint_milestone_frequency: 500
    evaluation_frequency: 100
