import json
import numpy as np
from scipy.spatial.transform import Rotation
from scripts.record_wuji_press_goal import R,D,record
base=R/'runs/real-knife-press-resistance-20261002/eval';a=dict(np.load(base/'pilot-zero/trace.npz'));b=dict(np.load(base/'pilot-native/trace.npz'));parity={k:float(np.max(np.abs(a[k].astype(float)-b[k].astype(float)))) for k in ['q','target','slider','object_pos','object_rot','action']};assert max(parity.values())<2e-6
out={};hand=Rotation.from_rotvec([0,-np.pi/2,0])*Rotation.from_rotvec([np.pi/2,0,0])
for p in base.glob('*/press-report.json'):
 j=json.loads(p.read_text());tr=dict(np.load(p.parent/'trace.npz'));rot=hand*Rotation.from_quat(tr['object_rot'].reshape(-1,4));normal=rot.apply(np.tile([0,1,0],(len(rot),1))).reshape(tr['object_rot'].shape[:2]+(3,));force=np.maximum(0,(tr['contact_force'][:,:,0]*normal).sum(-1));valid=tr['active'];rows=j['records'];out[p.parent.name]=dict(K20=j['K20'],S5=j['S5'],n=j['n'],by_source={str(s):dict(n=sum(r['source']==s for r in rows),K20=sum(r['K20'] for r in rows if r['source']==s),ordered=sum(r['ordered_open_close'] for r in rows if r['source']==s),stable=sum(r['body_stable'] for r in rows if r['source']==s)) for s in [0,3]},mean_normal_net_proxy_N=float(force[valid].mean()),contact_fraction=float(tr['contact'][:,:,0][valid].mean()),mean_resistance_N=float(np.mean([r['force_mean_abs_N'] for r in rows])))
(D/'PILOT_SUMMARY.json').write_text(json.dumps(dict(zero_path_max_abs=parity,results=out,diagnostic_correction='Pilot saved normal/slip projections mixed hand/world axes. Correct force projection recomputed from raw contacts and recorded object quaternion plus fixed hand-base rotation; original scalar slip summary excluded. No policy/physics change.'),indent=2)+'\n');record('pilot_zero_path_and_operability_results',evidence='research/real-knife-press-resistance-20261002/PILOT_SUMMARY.json',next='Fix diagnostic projection only; freeze3x3levels and compareheldoutvariableload beforetraining decision');print(json.dumps(out,indent=2))
