"""Reuse existing episode scorers and intervals for this small paired experiment."""
import csv,json,datetime
import numpy as np
from scipy.spatial.transform import Rotation
from scripts.record_wuji_press_goal import R,D,record
from scripts.wuji_timed_command_metrics import score_timed_trace
from scripts.summarize_wuji_unified import wilson
from scripts.analyze_wuji_geometry import paired_ci
from scripts.wuji_width_contract import sha
base=R/'runs/real-knife-press-resistance-20261002';hand=Rotation.from_rotvec([0,-np.pi/2,0])*Rotation.from_rotvec([np.pi/2,0,0]);episodes=[];cells=[]
for p in sorted((base/'eval').glob('*/press-report.json')):
 j=json.loads(p.read_text());t=dict(np.load(p.parent/'trace.npz'));diag=dict(np.load(p.parent/'diagnostics.npz'));s5=score_timed_trace(t,150,9,600);k3=score_timed_trace(t,150,3,600)
 normal=(hand*Rotation.from_quat(t['object_rot'].reshape(-1,4))).apply(np.tile([0,1,0],(t['object_rot'].shape[0]*t['object_rot'].shape[1],1))).reshape(t['object_rot'].shape[:2]+(3,));force=np.maximum(0,(t['contact_force'][:,:,0]*normal).sum(-1))
 assert np.max(diag['resistance_force_N']*diag['resistance_input_velocity_mps'])<=1e-8
 for i,r in enumerate(j['records']):
  valid=t['active'][:,i]&~t['fall'][:,i]&~t['invalid'][:,i];stable=valid&(t['drift'][:,i]<.01)&(t['rotation'][:,i]<.25);full=len(valid)==600 and bool(stable.all());st=k3['records'][i]['stages_attained'];ordered=any(st[o] and st[c] for o in [0,2] for c in [1,3] if c>o);K=bool(ordered and full);S=bool(s5['records'][i]['stable_full_all_endpoints']);assert K==r['K20'] and S==r['S5'];active=t['active'][:,i];bad=np.flatnonzero(~stable)
  row=dict(run=p.parent.name,source=r['source'],row=i,model=j['model'],press_mm=j['press']['press_mm'],resistance_n=j['press']['resistance_n'],profile=j['press']['profile'],profile_seed=j['press']['profile_seed'],K20=K,S5=S,ordered_open_close=ordered,body_stable=full,first_breach_s=float((bad[0]+1)/30) if len(bad) else None,max_drift_mm=float(t['drift'][active,i].max()*1000),max_rotation_rad=float(t['rotation'][active,i].max()),endpoint_error_mm=r['endpoint_error_mm'],normal_net_proxy_mean_N=float(force[active,i].mean()),normal_net_proxy_first3s_N=float(force[:90,i][active[:90]].mean()),contact_fraction=r['contact_fraction'],pd_saturation_proxy=r['pd_saturation_proxy'],force_mean_abs_N=r['force_mean_abs_N']);episodes.append(row)
 for source in [0,3,'all']:
  rows=[r for r in episodes if r['run']==p.parent.name and (source=='all' or r['source']==source)];n=len(rows)
  cell=dict(run=p.parent.name,source=source,n=n,model=j['model'],press_mm=j['press']['press_mm'],resistance_n=j['press']['resistance_n'],profile=j['press']['profile'])
  for metric in ['K20','S5','body_stable','ordered_open_close']:
   k=sum(r[metric] for r in rows);cell[metric]=dict(k=k,n=n,wilson95=wilson(k,n))
  for metric in ['normal_net_proxy_mean_N','normal_net_proxy_first3s_N','contact_fraction','pd_saturation_proxy','max_drift_mm','force_mean_abs_N']:cell[metric]=float(np.mean([r[metric] for r in rows]))
  cells.append(cell)
pairs=[]
for profile,load in [('constant',0),('constant',.05),('variable',.05)]:
 left='confirm-'+profile+'-r'+str(load)+'-p0';right='confirm-'+profile+'-r'+str(load)+'-p0.5'
 for source in [0,3,'all']:
  l=[r for r in episodes if r['run']==left and (source=='all' or r['source']==source)];r=[r for r in episodes if r['run']==right and (source=='all' or r['source']==source)];assert [x['row'] for x in l]==[x['row'] for x in r] and l
  for metric in ['K20','S5']:
   a=np.array([x[metric] for x in l],int);b=np.array([x[metric] for x in r],int);n=len(a);discord=int((a!=b).sum());pairs.append(dict(left=left,right=right,source=source,metric=metric,n=n,both_success=int(((a==1)&(b==1)).sum()),left_only=int(((a==1)&(b==0)).sum()),right_only=int(((a==0)&(b==1)).sum()),both_fail=int(((a==0)&(b==0)).sum()),observed_difference=float((b-a).mean()),paired_bootstrap95=paired_ci(b-a),discordance_wilson95=wilson(discord,n),zero_discordance_effect_uncertainty_bound=[-wilson(0,n)[1],wilson(0,n)[1]] if discord==0 else None))
assert len([r for r in episodes if r['run'].startswith('confirm-')])==192
out=base/'analysis';out.mkdir(exist_ok=True)
with (out/'episodes.csv').open('w') as h:w=csv.DictWriter(h,fieldnames=list(episodes[0]));w.writeheader();w.writerows(episodes)
(out/'summary.json').write_text(json.dumps(dict(cells=cells,paired=pairs,raw_rescore_matches=True,episode_records=len(episodes),confirmation_unique_states=32,confirmation_reused_across6conditions=True),indent=2)+'\n')
resources=json.loads((D/'STATE.json').read_text());lines=['# 实物近似刀持续按压与阻力实验','', '**结论：当前C3200在135×16×12mm主体近似几何上尚不能稳定操作；0.5/1.5mm持续位置偏置未扩大可用阻力范围。** 独立确认中，零偏置与0.5mm偏置在零新增阻力、0.05N平滑阻力上限、独立变化阻力profile下均为K20=0/32、S5=0/32。每格0/32的Wilson95区间为[0,10.7%]；没有观测差异不能证明总体效应恰为零，也不支持宣称真实恒力按压无效。','', '位置偏置不是恒力控制：pilot和dev未显示偏置能稳定增加净法向接触力代理，当前主要瓶颈包含持刀失稳与接触/支撑不匹配。按本Goal负结果分支不训练，新增Adam更新0。零阻力teacher仅来源3可行（K20 7/8，来源0 0/8），0.05N上限下总计2/16；这些是开发参考，不是独立确认的teacher可靠性认证。未扩扫模型/抓姿/载荷，没有第二套final。','', '## 物理近似与范围','', '| 参数 | 数值与依据 |','|---|---|','| 刀柄主体L/W/T | 135/16/12mm，用户确认；12mm不含滑块 |','| 滑块 | 10/3/30mm包围盒，含不对称轴向斜坡/肩部的凸mesh；估计 |','| 导轨 | 轴URDF+Z，50mm机械行程；沿用估计，外部指令行程40mm |','| 质量/有效惯量 | 29g主体+6g滑块及旧实测仿真惯量沿用；非实物测量 |','| 摩擦/执行器 | 原手/物接触摩擦、关节摩擦与0.3Ns/m导轨阻尼、全手Kp/限位保持 |','| 照片与视频 | 本会话给出的文件名未在可用目录找到，未声称看过 |','', '无向下解锁机构。导轨新增阻力是关节反向effort， articulation承受刀柄反作用：F=-Fmax·tanh(v/0.02m/s)，每个物理步更新。施加时F·v≤0，零路径与原控制的q/target/slider/object/action最大差见PILOT_SUMMARY。Fmax是力上限，不是所有时刻实际恒定载荷；零新增阻力仍保留旧阻尼/摩擦。该平滑模型不重建静态锁止/卡槽，主模型也未包含按压提高导轨阻力的耦合；已无收益，追加该耦合不改变当前决策，故不扫描。','', '按压由初始校准法向与合法关节FK计算拇指有界joint offset（每关节≤0.15rad），0.5秒平滑上升。每步先去除上步实际施加的偏置，再执行原递推，再加本步偏置；最终issued target同步给SC-real的已知controller。运行中没有物体/slider真值纠正policy动作，输入仍2000历史+55初始校准+21controller。世界坐标真值只进入被动力学和诊断。接触力是拇指pad刚体净接触力投影，不能视为孤立拇指—滑块接触对力；相对速度和PD饱和也仅为代理。','', '## 数据与结果','', '仅来源0/3，初始配方导致约2mm中间指节网格穿入、pilot无有效状态；一次几何局部适配后降至约0.65mm，接触点变化<0.06mm，阈值未变。所有条件共享该配方。pilot/dev/confirm分别4/16/32个新有效初态，固定顺序接受；原失败尝试保留，不按policy结果筛选。confirm每来源16、总32；同状态的6种条件不是192个独立初态。','', 'K20：20秒内按5秒固定外部指令依序开关，误差<2mm连续3点，且全程有效、位移<10mm、旋转<0.25rad。S5在同一轨迹检查每阶段末9点，不另跑S2/F40。','', '| dev条件（16初态） | K20来源0/3 | S5来源0/3 | 平均法向净力代理N | 拇指接触比例 | 实际反向力绝对均值N |','|---|---|---|---:|---:|---:|']
for name in ['operability-C']+[t['name'] for t in json.loads((D/'MAIN_DEV.json').read_text())['tasks']]:
 c=next(x for x in cells if x['run']==name and x['source']=='all');sub=[next(x for x in cells if x['run']==name and x['source']==s) for s in [0,3]];lines.append('| '+name+' | '+' / '.join(str(x['K20']['k'])+'/8' for x in sub)+' | '+' / '.join(str(x['S5']['k'])+'/8' for x in sub)+' | %.3f | %.3f | %.4f |'%(c['normal_net_proxy_mean_N'],c['contact_fraction'],c['force_mean_abs_N']))
lines+=['', '按有效活动帧统计力/接触代理；不同存活时长会影响均值，不能单凭均值归因。原pilot/零负载参考曾混用坐标系做诊断投影；summary从原始世界接触力和记录姿态统一重算，policy与物理未改。原错误标量滑移代理不用于结论。','', '| 独立确认条件 | 零偏置K20/S5 | 0.5mm偏置K20/S5 | 来源0/3（每臂） |','|---|---|---|---|','| 0新增N | 0/32 / 0/32 | 0/32 / 0/32 | 均0/16、0/16 |','| 常量上限0.05N | 0/32 / 0/32 | 0/32 / 0/32 | 均0/16、0/16 |','| 变化上限0.05N | 0/32 / 0/32 | 0/32 / 0/32 | 均0/16、0/16 |','', '变化规则Fmax(t)=0.05·(0.25+0.75sin²(2πt/3.7+phase))N；dev seed2026100233，独立confirm2026100243。确认后不再调参。所有配对均为0单臂成功/32双失败；bootstrap差值区间退化为[0,0]，不能作无差异证明。零不一致对的Wilson上界约10.7%，保守展示真实差值仍可能在±10.7个百分点内；这不会改变优先修复接触/持刀的行动，不扩样。','', '逐episode CSV、配对四格/区间、完整主轨迹及配置随Release保存；同一模型/初态只按所属条件计一次。teacher在名义条件的成功说明来源3并非完全不可操作，但student/按压失败不能证明纯proprioception不可能或某个训练方法永远无效。','', '## 决策与交付','', '下一步唯一优先事项：先让部署可用的接触压紧/支撑控制在该厚刀几何上稳定成立，观察相同初态早期持刀失稳和偏置为何没有形成持续更大接触；之后再考虑单一受控短训练。当前证据不足以把失败归为单纯轴向力不足，盲目蒸馏有限载荷下不可靠teacher标签不会回答本轮按压问题。','', '新增训练0。必要视频仅1组：同一预定来源3dev首有效初态、变化阻力下0与0.5mm对比，沿用RTX4090相机重仿真，保留失败，不替代H200统计；非真机。资源以STATE及作业收据为准；失败与渲染均计费，历史54.640988924736625GPUh未重置。']
(D/'REPORT.md').write_text('\n'.join(lines)+'\n');record('independent_small_confirmation_rescored_and_reported',evidence='research/real-knife-press-resistance-20261002/REPORT.md',state_updates=dict(confirmation_complete=True,confirmation_closed=True,optimizer_updates=0),next='Completeonepairedvideo andsmallrelease; no extra experiments or training');print(json.dumps(dict(records=len(episodes),confirmation=192,cells=len(cells))))
