"""Small independent physical/input definitions fixed before final policy selection; no evaluation or training access."""
import pathlib,json,hashlib,shutil,xml.etree.ElementTree as ET,numpy as np
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';src=R/'assets/objects/knife_wuji_real_size_20261002/000';base=json.loads((src/'parameters.json').read_text());out=R/'assets/objects/knife_wuji_support_independent_20261003';out.mkdir(exist_ok=False);rng=np.random.default_rng(2026100462)
definitions=[([.016,.012,.135],[0,0,0]),([.0163,.0136,.1364],[-.00035,.00015,.0012]),([.0157,.0121,.1342],[.00025,.0007,-.0014]),([.0162,.0123,.1358],[-.0002,.0002,.001]) ]
labels=['nominal-new-observation','thick13p6-new-joint','raised0p7-new-joint','highload0p6-new-joint']
entries=[]
for i,(size,offset) in enumerate(definitions):
    name='h%04d'%i;folder=out/name;folder.mkdir();shutil.copy2(src/'slider-shoulder.obj',folder/'slider-shoulder.obj');size=np.asarray(size);offset=np.asarray(offset);origin=np.asarray(base['slider_origin'])+offset;origin[1]+=(size[1]-.012)/2;tree=ET.parse(src/'mobility.urdf')
    for node in tree.findall("./link[@name='link_0']/visual/geometry/box")+tree.findall("./link[@name='link_0']/collision/geometry/box"):node.set('size',' '.join(map(str,size)))
    tree.find('./joint/origin').set('xyz',' '.join(map(str,origin)));mass=.029*np.prod(size)/np.prod([.016,.012,.135]);node=tree.find("./link[@name='link_0']/inertial");node.find('mass').set('value',str(mass));diagonal=mass/12*np.array([size[1]**2+size[2]**2,size[0]**2+size[2]**2,size[0]**2+size[1]**2])
    for k,v in zip(['ixx','iyy','izz'],diagonal):node.find('inertia').set(k,str(v))
    tree.write(folder/'mobility.urdf',encoding='utf-8',xml_declaration=True)
    parameters=dict(base,handle_size=size.tolist(),slider_origin=origin.tolist(),slider_initial_center=(origin+[0,0,base['joint_lower']]).tolist(),masses=[float(mass),.006],total_size_lwt=[float(size[2]),float(size[0]),float(size[1]+.003+offset[1])],round='support-pressure-20261003',label=name,split='independent',slider_relative_offset_m=offset.tolist(),mass_inertia_mode='Constant nominal handle density; cuboid inertia recomputed, fixed authored slider mass/inertia; engineering assumptions',scope='Jointphysicaltraining asset only; no actor/currenttruth geometry selection')
    parameters['urdf_sha256']=hashlib.sha256((folder/'mobility.urdf').read_bytes()).hexdigest();(folder/'parameters.json').write_text(json.dumps(parameters,indent=2));entries.append(dict(instance=name,split='independent',directory=str(folder.relative_to(R)),parameters=parameters,label=labels[i],load_N=.6 if i==3 else .2,detent_N=.5 if i==3 else .2,load_profile=['triangular','sinusoidal','pulse','triangular'][i],load_frequency_rad_s=1.63+.11*i,sensor_seed=2026100463+i,actuation_delay_frames=1 if i==1 else 0,estimate=dict(handle_size_WTL_m=(size+rng.uniform(-1,1,3)*[.0006,.0006,.0012]).tolist(),slider_contact_shift_m=(offset+rng.uniform(-.0006,.0006,3)).tolist(),initial_object_center_shift_knife_m=[0,(size[1]-.012)/2,0],uncertainty_m=.0006,source='New independent onceinitial synthetic observation drawn before finalfreeze; physicaldefinition never fedtoactor/controller, no evaluation usedforselection.')))
train=json.loads((D/'joint-training-registry-v26.json').read_text())['entries'];known={r['parameters']['urdf_sha256'] for r in train}
assert all(r['parameters']['urdf_sha256'] not in known for r in entries[1:])
manifest=dict(seed=2026100462,entries=entries,policy_selection_access=False,scope='Exactly four newindependent continuousattempts afterfreeze. Nominal physicaldimensions repeat necessarycenter but observation/profile/seed are new; other3 jointgeometries have disjoint URDF hashes vs training64. No allfamily coverageclaim or statisticalsuccessrate.')
(D/'new-independent-definitions-v120.json').write_text(json.dumps(manifest,indent=2))
from scripts.record_wuji_support_goal import record
record('new_independent_definitions_v120_fixed_before_freeze',evidence='research/support-pressure-20261003/new-independent-definitions-v120.json',config={'cases':4,'seed':2026100462,'results_read_for_selection':False},conclusion='Fournew smallcheckdefinitions; runonlyafterpolicy/controlfreeze. No old332conditions/massmatrix replay. Every actualpickup failure included.',next='Do notevaluate independentconditions until candidatefreeze')
