"""Three physical-only development geometries; never used to select policy."""
import pathlib,json,xml.etree.ElementTree as ET,shutil,hashlib,numpy as np
R=pathlib.Path(__file__).resolve().parents[2];src=R/'assets/objects/knife_wuji_real_size_20261002/000';base=json.loads((src/'parameters.json').read_text());out=R/'assets/objects/knife_wuji_support_dev_20261003';out.mkdir(exist_ok=False);rows=[]
for name,size,offset in [('thick14',[.016,.014,.135],[0,0,0]),('raised1',[.016,.012,.135],[0,.001,0]),('forward5',[.016,.012,.135],[0,0,.005])]:
 d=out/name;d.mkdir();shutil.copy2(src/'slider-shoulder.obj',d/'slider-shoulder.obj');tree=ET.parse(src/'mobility.urdf');size=np.array(size);origin=np.array(base['slider_origin'])+offset;origin[1]+=(size[1]-.012)/2
 for node in tree.findall("./link[@name='link_0']/visual/geometry/box")+tree.findall("./link[@name='link_0']/collision/geometry/box"):node.set('size',' '.join(map(str,size)))
 tree.find('./joint/origin').set('xyz',' '.join(map(str,origin)));mass=.029*np.prod(size)/np.prod([.016,.012,.135]);node=tree.find("./link[@name='link_0']/inertial");node.find('mass').set('value',str(mass));diagonal=mass/12*np.array([size[1]**2+size[2]**2,size[0]**2+size[2]**2,size[0]**2+size[1]**2])
 for k,v in zip(['ixx','iyy','izz'],diagonal):node.find('inertia').set(k,str(v))
 tree.write(d/'mobility.urdf',encoding='utf-8',xml_declaration=True);j=dict(base,handle_size=size.tolist(),slider_origin=origin.tolist(),slider_initial_center=(origin+[0,0,base['joint_lower']]).tolist(),masses=[float(mass),.006],total_size_lwt=[float(size[2]),float(size[0]),float(size[1]+.003+offset[1])],round='support-pressure-20261003',label=name,scope='Physicaldevelopmentasset only; doesnotflowtoactor/control. Explicit stress, notnewindependentvalidation.');j['urdf_sha256']=hashlib.sha256((d/'mobility.urdf').read_bytes()).hexdigest();(d/'parameters.json').write_text(json.dumps(j,indent=2));rows.append(dict(name=name,path=str(d.relative_to(R)),parameters=j))
(R/'research/support-pressure-20261003/development-variants-v15.json').write_text(json.dumps(rows,indent=2));print(json.dumps([{k:v for k,v in x.items() if k!='parameters'} for x in rows]))
