"""Training-only jointly varying near-real knife assets; no heldout generated."""
import pathlib,json,hashlib,shutil,xml.etree.ElementTree as ET,numpy as np
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';src=R/'assets/objects/knife_wuji_real_size_20261002/000';base=json.loads((src/'parameters.json').read_text());out=R/'assets/objects/knife_wuji_support_train_20261003';out.mkdir(exist_ok=False);rng=np.random.default_rng(2026100376)
definitions=[([.016,.012,.135],[0,0,0]),([.016,.014,.135],[0,0,0]),([.016,.012,.135],[0,.001,0]),([.016,.012,.135],[0,-.001,0]),([.016,.012,.135],[.001,0,0]),([.014,.010,.130],[0,0,0]),([.018,.014,.140],[0,.001,0]),([.017,.0135,.137],[-.001,.0008,.005])]
for _ in range(56):definitions.append((rng.uniform([.014,.010,.130],[.018,.014,.140]).tolist(),rng.uniform([-.001,-.001,-.005],[.001,.001,.005]).tolist()))
entries=[]
for i,(size,offset) in enumerate(definitions):
    name='s%04d'%i;folder=out/name;folder.mkdir();shutil.copy2(src/'slider-shoulder.obj',folder/'slider-shoulder.obj');size=np.asarray(size);offset=np.asarray(offset);origin=np.asarray(base['slider_origin'])+offset;origin[1]+=(size[1]-.012)/2;tree=ET.parse(src/'mobility.urdf')
    for node in tree.findall("./link[@name='link_0']/visual/geometry/box")+tree.findall("./link[@name='link_0']/collision/geometry/box"):node.set('size',' '.join(map(str,size)))
    tree.find('./joint/origin').set('xyz',' '.join(map(str,origin)));mass=.029*np.prod(size)/np.prod([.016,.012,.135]);node=tree.find("./link[@name='link_0']/inertial");node.find('mass').set('value',str(mass));diagonal=mass/12*np.array([size[1]**2+size[2]**2,size[0]**2+size[2]**2,size[0]**2+size[1]**2])
    for k,v in zip(['ixx','iyy','izz'],diagonal):node.find('inertia').set(k,str(v))
    tree.write(folder/'mobility.urdf',encoding='utf-8',xml_declaration=True)
    parameters=dict(base,handle_size=size.tolist(),slider_origin=origin.tolist(),slider_initial_center=(origin+[0,0,base['joint_lower']]).tolist(),masses=[float(mass),.006],total_size_lwt=[float(size[2]),float(size[0]),float(size[1]+.003+offset[1])],round='support-pressure-20261003',label=name,split='train',slider_relative_offset_m=offset.tolist(),mass_inertia_mode='Constant nominal handle density; cuboid inertia recomputed, fixed authored slider mass/inertia; engineering assumptions',scope='Jointphysicaltraining asset only; no actor/currenttruth geometry selection')
    parameters['urdf_sha256']=hashlib.sha256((folder/'mobility.urdf').read_bytes()).hexdigest();(folder/'parameters.json').write_text(json.dumps(parameters,indent=2));entries.append(dict(instance=name,split='train',directory=str(folder.relative_to(R)),parameters=parameters))
(D/'joint-training-registry-v26.json').write_text(json.dumps(dict(seed=2026100376,entries=entries,actor_scope='Physicalinstance IDs select only simulator assets; never features or controller lookup',heldout_count=0),indent=2));(D/'joint-training-schedule256-v26.json').write_text(json.dumps({'instances':[row['instance'] for row in entries]*4},indent=2));print(json.dumps({'assets':len(entries),'env_slots':256,'range_WTL_m':[[.014,.018],[.010,.014],[.130,.140]],'slider_offset_xyz_m':[[-.001,.001],[-.001,.001],[-.005,.005]]}))
from scripts.record_wuji_support_goal import record
record('joint_physical_training_family_prepared',evidence=['research/support-pressure-20261003/joint-training-registry-v26.json','research/support-pressure-20261003/joint-training-schedule256-v26.json'],config={'train_assets':64,'slots':256,'seed':2026100376,'heldout_generated':False},next='Common noisy initial estimator-to-IK plans, then shortbroadjointlearning beforelongextension')
