"""Two useful actualG2 development pilots,8s vs16s learned takeover."""
import argparse,subprocess,pathlib,datetime,json,hashlib,os,time
p=argparse.ArgumentParser();p.add_argument('--gpu',type=int,required=True);p.add_argument('--takeover',type=int,choices=[8,16],required=True);a=p.parse_args()
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';name='passive-offset-takeover%d-v10'%a.takeover;job=R/'runs/support-pressure-20261003/jobs'/name;job.mkdir(parents=True,exist_ok=False)
py='/home/wangjiarui/artgym-runtime/bin/python';env=dict(os.environ,PATH='/home/wangjiarui/artgym-runtime/bin:/usr/bin:/bin',LD_LIBRARY_PATH='/home/wangjiarui/artgym-runtime/lib',PYTHONUTF8='1',PYTHONNOUSERSITE='1',PYTHONPATH='.:rl_games',CUDA_VISIBLE_DEVICES=str(a.gpu),TORCH_EXTENSIONS_DIR='/tmp/wuji-width-torch-extensions',OMP_NUM_THREADS='4',MKL_NUM_THREADS='4',MAX_JOBS='2',PYTHONUNBUFFERED='1')
cmd=[py,'-m','scripts.train_wuji_robust_residual','--output','runs/support-pressure-20261003/train/'+name,'--scene','g2','--envs','128','--updates','100','--horizon','32','--seed','2026100362','--randomization-scale','.5','--load-min','.1','--load-max','.5','--detent-min','.1','--detent-max','.5','--load-profile','mixed','--resistance-integration','solver-brake','--takeover-seconds',str(a.takeover),'--base-mode','geometric','--thumb-reference','research/robust-knife-family-20261003/functional-side-edge-under-support-v6/continuous-thumb-v2.json','--support-residual-scale','.025','--thumb-residual-scale','.12','--action-parameterization','bounded-motor-offset','--initialize-model-from','runs/robust-knife-family-20261003/train/geometric-P1/update_000050.pth','--training-geometry-schedule','research/support-pressure-20261003/bounded-offset-pilot-geometry-v1.json','--functional-thumb-reward','--active-kl-stop','--bounded-actor-update']
j=dict(start_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),command=cmd,gpu=a.gpu,launcher_pid=os.getpid(),source_sha256={x:hashlib.sha256((R/x).read_bytes()).hexdigest() for x in ['scripts/train_wuji_robust_residual.py','scripts/g2_continuous_scene.py','scripts/wuji_scheduled_thumb_reference.py','scripts/wuji_bounded_motor_residual.py','scripts/wuji_passive_solver_brake.py']},initialize_sha256=hashlib.sha256((R/'runs/robust-knife-family-20261003/train/geometric-P1/update_000050.pth').read_bytes()).hexdigest());(job/'identity.json').write_text(json.dumps(j,indent=2));t=time.monotonic()
with (job/'output.log').open('w') as f:
 child=subprocess.Popen(cmd,cwd=R,env=env,stdout=f,stderr=subprocess.STDOUT);j['child_pid']=child.pid;(job/'identity.json').write_text(json.dumps(j,indent=2));child.wait()
j.update(end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),wall_seconds=time.monotonic()-t,exit_code=child.returncode);(job/'result.json').write_text(json.dumps(j,indent=2));print(json.dumps(j),flush=True)
