"""Three fixed full loaded episodes on one training-machine GPU; no score sweep."""
import pathlib,subprocess,datetime,json,hashlib,os,time
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';out=R/'runs/support-pressure-20261003';py='/home/agiuser/miniconda3/envs/artgym/bin/python';env=dict(os.environ,PATH='/home/agiuser/miniconda3/envs/artgym/bin:/usr/bin:/bin',PYTHONUTF8='1',PYTHONNOUSERSITE='1',PYTHONPATH='.:rl_games',CUDA_VISIBLE_DEVICES='0',LD_LIBRARY_PATH='/home/agiuser/miniconda3/envs/artgym/lib',TORCH_EXTENSIONS_DIR='/tmp/wuji-width-torch-extensions',OMP_NUM_THREADS='4',MKL_NUM_THREADS='4',MAX_JOBS='2',PYTHONUNBUFFERED='1');weight=R/'runs/robust-knife-family-20261003/train/geometric-P1/update_000050.pth';sha=hashlib.sha256(weight.read_bytes()).hexdigest()
common=['--seconds','36','--dx=-.1985','--dy=.05','--yaw=0','--slider-face','up','--grasp-plan','research/robust-knife-family-20261003/functional-side-edge-under-support-equilibrium-v6/motor-plan.json','--table-calibration','research/robust-knife-family-20261003/functional-side-edge-under-support-v6/localization.json','--acquisition-path','research/robust-knife-family-20261003/functional-side-edge-under-support-lateral-v3/acquisition-path.json','--handover-calibration','research/robust-knife-family-20261003/handover-from-v25-v1.json','--residual-checkpoint','runs/robust-knife-family-20261003/train/geometric-P1/update_000050.pth','--load','.2','--detent','.2','--load-profile','pulse','--load-frequency','2.9','--hand-friction','.8','--knife-friction','2.4','--observation-noise','.002','--observation-bias','.006','--seed','2026100358','--pair-force-measurement','--video']
for label,spec in [('baseline-pressure-film','four-finger-baseline-v1.json')]:
 job=out/'jobs'/('local-'+label+'-v7');job.mkdir(parents=True,exist_ok=False);output='runs/support-pressure-20261003/demo/'+label+'-v7';cmd=[py,'-m','scripts.run_g2_robust_demo','--output',output,'--support-pressure-config','research/support-pressure-20261003/'+spec,*common];start=datetime.datetime.now(datetime.timezone.utc);j={'start_utc':start.isoformat(),'command':cmd,'gpu':0,'checkpoint_sha256':sha,'output':output,'config':spec,'pid':os.getpid()};(job/'identity.json').write_text(json.dumps(j,indent=2));t=time.monotonic()
 with (job/'output.log').open('w') as f:
  p=subprocess.Popen(cmd,cwd=R,env=env,stdout=f,stderr=subprocess.STDOUT);j['child_pid']=p.pid;(job/'identity.json').write_text(json.dumps(j,indent=2));p.wait()
 j.update(end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),exit_code=p.returncode,wall_seconds=time.monotonic()-t);(job/'result.json').write_text(json.dumps(j,indent=2));print(json.dumps(j),flush=True)
 from scripts.record_wuji_support_goal import record
 record('local_pressure_video_job_closed',evidence=str(job.relative_to(R)/'result.json'),config=j,next='Inspect continuous video and total added-load work, then evaluate new learned position offsets')
 if p.returncode:break
