"""Eight necessary native development checks, never independent validation."""
import pathlib,json,hashlib,os,datetime,subprocess,time,numpy as np
from scripts.plan_wuji_initial_geometry import adapt
from scripts.record_wuji_support_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';out=R/'runs/support-pressure-20261003';old=R/'research/robust-knife-family-20261003';rng=np.random.default_rng(2026100380)
plan=json.loads((old/'functional-side-edge-under-support-equilibrium-v6/motor-plan.json').read_text());support=json.loads((D/'coordinated-preload-moderate-v6.json').read_text());reference=json.loads((old/'functional-side-edge-under-support-v6/continuous-thumb-v2.json').read_text());registry=json.loads((D/'joint-training-registry-v26.json').read_text())['entries']
py='/home/agiuser/miniconda3/envs/artgym/bin/python';env=dict(os.environ,PATH='/home/agiuser/miniconda3/envs/artgym/bin:/usr/bin:/bin',LD_LIBRARY_PATH='/home/agiuser/miniconda3/envs/artgym/lib',PYTHONNOUSERSITE='1',PYTHONUTF8='1',PYTHONPATH='.:rl_games',TORCH_EXTENSIONS_DIR='/tmp/wuji-width-torch-extensions',OMP_NUM_THREADS='4',MKL_NUM_THREADS='4',CUDA_VISIBLE_DEVICES='0',PYTHONUNBUFFERED='1')
common=['--seconds','36','--dx=-.1985','--dy=.05','--yaw=0','--slider-face','up','--table-calibration','research/robust-knife-family-20261003/functional-side-edge-under-support-v6/localization.json','--acquisition-path','research/robust-knife-family-20261003/functional-side-edge-under-support-lateral-v3/acquisition-path.json','--handover-calibration','research/robust-knife-family-20261003/handover-from-v25-v1.json','--load','.2','--detent','.2','--load-profile','pulse','--load-frequency','2.9','--hand-friction','.8','--knife-friction','2.4','--observation-noise','.002','--observation-bias','.006','--seed','2026100358','--pair-force-measurement','--resistance-integration','solver-brake']
for i,label in [(3,'lower1'),(4,'lateral1'),(5,'thin-small'),(6,'wide-thick-high')]:
    definition=registry[i];truth=definition['parameters'];size=np.asarray(truth['handle_size'])+rng.uniform(-1,1,3)*[.00025,.00025,.0005];shift=np.asarray(truth['slider_relative_offset_m'])+rng.uniform(-.00025,.00025,3)
    estimate=dict(handle_size_WTL_m=size.tolist(),slider_contact_shift_m=shift.tolist(),initial_object_center_shift_knife_m=[0,(size[1]-.012)/2,0],uncertainty_m=.00025,source='New synthetic onceinitial development observation; known training geometry, not finalheldout. Same common IK from noisy estimates, no physicalID planner/actor.')
    folder=out/'corner-config-v29'/label;folder.mkdir(parents=True,exist_ok=False);values=adapt(estimate,plan,support,reference)
    for name,value in zip(['motor-plan.json','support.json','reference.json','audit.json'],values):(folder/name).write_text(json.dumps(value,indent=2))
    for policy,weight in [('P50','runs/robust-knife-family-20261003/train/geometric-P1/update_000050.pth'),('E100','runs/support-pressure-20261003/train/estimated-offset-takeover16-v23/update_000100.pth')]:
        name=label+'-'+policy+'-v29';output=out/'demo'/name;job=out/'jobs'/name;job.mkdir(parents=True,exist_ok=False)
        cmd=[py,'-m','scripts.run_g2_robust_demo','--output',str(output.relative_to(R)),'--grasp-plan',str((folder/'motor-plan.json').relative_to(R)),'--support-pressure-config',str((folder/'support.json').relative_to(R)),'--thumb-reference-override',str((folder/'reference.json').relative_to(R)),'--knife-asset',definition['directory']+'/mobility.urdf','--residual-checkpoint',weight,*common]
        identity=dict(start_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),command=cmd,gpu='local RTX4090',launcher_pid=os.getpid(),weight_sha256=hashlib.sha256((R/weight).read_bytes()).hexdigest(),estimate=estimate,source_sha256={file:hashlib.sha256((R/file).read_bytes()).hexdigest() for file in ['scripts/run_g2_robust_demo.py','scripts/g2_r800_policy.py','scripts/wuji_scheduled_thumb_reference.py']});(job/'identity.json').write_text(json.dumps(identity,indent=2));record('native_corner_development_job_started',evidence=str(job.relative_to(R)/'identity.json'),config=identity,next='Actual completepickup/hold/operation, allfailures counted, no endpointcriterion adjustment')
        start=time.monotonic()
        with (job/'output.log').open('w') as log:child=subprocess.run(cmd,cwd=R,env=env,stdout=log,stderr=subprocess.STDOUT)
        identity.update(exit_code=child.returncode,end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),wall_seconds=time.monotonic()-start);(job/'result.json').write_text(json.dumps(identity,indent=2));print(json.dumps(identity),flush=True)
        record('native_corner_development_job_closed',evidence=str(job.relative_to(R)/'result.json'),config=identity,next='Continue scoped four-condition comparison; broadjointtraining currentlyrunning')
        if child.returncode:raise RuntimeError(name+' subprocess failure; evidence retained')
