"""Exactly four new continuous checks, usable only after candidate freeze."""
import argparse,datetime,hashlib,json,os,pathlib,subprocess,time
p=argparse.ArgumentParser();p.add_argument('--case',type=int,choices=range(4),required=True);p.add_argument('--gpu',type=int,required=True);a=p.parse_args()
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';B=R/'runs/support-pressure-20261003'
freeze=json.loads((D/'freeze.json').read_text());definition=json.loads((D/'new-independent-definitions-v120-revision1.json').read_text())['entries'][a.case]
weight=R/freeze['checkpoint'];assert hashlib.sha256(weight.read_bytes()).hexdigest()==freeze['checkpoint_sha256']
name='independent-'+definition['label']+'-v134-retry1';job=B/'jobs'/name;job.mkdir(parents=True,exist_ok=False);estimate=job/'estimate.json';estimate.write_text(json.dumps(definition['estimate'],indent=2))
cmd=['/home/wangjiarui/artgym-runtime/bin/python','-m','scripts.run_wuji_support_demo','--estimate',str(estimate.relative_to(R)),'--checkpoint',freeze['checkpoint'],'--knife-asset',definition['directory']+'/mobility.urdf','--support-layout',freeze['support_layout'],'--takeover-seconds',str(freeze['takeover_seconds']),'--load',str(definition['load_N']),'--detent',str(definition['detent_N']),'--load-profile',definition['load_profile'],'--load-frequency',str(definition['load_frequency_rad_s']),'--hand-friction','.65','--knife-friction','1.8','--noise','.002','--bias','.006','--delay-frames',str(definition['actuation_delay_frames']),'--seed',str(definition['sensor_seed']),'--output','runs/support-pressure-20261003/independent-checks-v134-retry1/'+definition['label']]
env=dict(os.environ,PATH='/home/wangjiarui/artgym-runtime/bin:/usr/bin:/bin',LD_LIBRARY_PATH='/home/wangjiarui/artgym-runtime/lib',PYTHONUTF8='1',PYTHONNOUSERSITE='1',PYTHONPATH='.:rl_games',CUDA_VISIBLE_DEVICES=str(a.gpu),TORCH_EXTENSIONS_DIR='/tmp/wuji-width-torch-extensions',OMP_NUM_THREADS='4',MKL_NUM_THREADS='4',MAX_JOBS='2',PYTHONUNBUFFERED='1')
row=dict(start_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),launcher_pid=os.getpid(),gpu=a.gpu,command=cmd,weight_sha256=freeze['checkpoint_sha256'],freeze_sha256=hashlib.sha256((D/'freeze.json').read_bytes()).hexdigest(),independent_definition=definition,scope='New independent physical/input condition, never training or selection; all planning/pickup/operation failures retained; fourcases only',source_sha256={f:hashlib.sha256((R/f).read_bytes()).hexdigest() for f in ['scripts/run_wuji_support_demo.py','scripts/plan_wuji_initial_geometry.py','scripts/plan_wuji_braced_support.py','scripts/run_g2_robust_demo.py','scripts/g2_r800_policy.py']})
(job/'identity.json').write_text(json.dumps(row,indent=2));begin=time.monotonic()
with (job/'output.log').open('w') as log:
 child=subprocess.Popen(cmd,cwd=R,env=env,stdout=log,stderr=subprocess.STDOUT);row['child_pid']=child.pid;(job/'identity.json').write_text(json.dumps(row,indent=2));child.wait()
row.update(exit_code=child.returncode,end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),wall_seconds=time.monotonic()-begin);(job/'result.json').write_text(json.dumps(row,indent=2));print(json.dumps(row),flush=True)
