"""Useful joint-family pilots: common planner/weights, four scoped choices."""
import argparse,datetime,hashlib,json,os,pathlib,subprocess,time
p=argparse.ArgumentParser();p.add_argument('--gpu',type=int,required=True);p.add_argument('--variant',choices=['looser','pressure'],required=True);p.add_argument('--updates',type=int,default=150);a=p.parse_args()
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/support-pressure-20261003';name='joint-'+a.variant+'-v34';job=R/'runs/support-pressure-20261003/jobs'/name;job.mkdir(parents=True,exist_ok=False);py='/home/wangjiarui/artgym-runtime/bin/python'
env=dict(os.environ,PATH='/home/wangjiarui/artgym-runtime/bin:/usr/bin:/bin',LD_LIBRARY_PATH='/home/wangjiarui/artgym-runtime/lib',PYTHONUTF8='1',PYTHONNOUSERSITE='1',PYTHONPATH='.:rl_games',CUDA_VISIBLE_DEVICES=str(a.gpu),TORCH_EXTENSIONS_DIR='/tmp/wuji-width-torch-extensions',OMP_NUM_THREADS='4',MKL_NUM_THREADS='4',MAX_JOBS='2',PYTHONUNBUFFERED='1')
weight='runs/support-pressure-20261003/train/estimated-offset-takeover16-v23/update_000100.pth'
cmd=[py,'-m','scripts.train_wuji_robust_residual','--output','runs/support-pressure-20261003/train/'+name,'--scene','g2','--envs','256','--updates',str(a.updates),'--horizon','32','--seed','2026100378','--randomization-scale','1','--load-min','.1','--load-max','.5','--detent-min','.1','--detent-max','.5','--load-profile','mixed','--resistance-integration','solver-brake','--takeover-seconds','16','--base-mode','geometric','--thumb-reference','research/support-pressure-20261003/coordinated-thumb-reference-v11.json','--support-residual-scale','.025','--thumb-residual-scale','.12','--action-parameterization','bounded-motor-offset','--initialize-model-from',weight,'--training-geometry-schedule','research/support-pressure-20261003/joint-training-schedule256-v26.json','--training-asset-registry','research/support-pressure-20261003/joint-training-registry-v26.json','--initial-estimate-scene','research/support-pressure-20261003/joint-looser-estimate-scene256-v32.json','--functional-thumb-reward','--active-kl-stop','--bounded-actor-update']
if a.variant=='pressure':cmd+=['--proprioceptive-pressure-config','research/support-pressure-20261003/analytic-joint-pressure-v33.json']
identity=dict(start_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),command=cmd,gpu=a.gpu,launcher_pid=os.getpid(),initialize_checkpoint_sha256=hashlib.sha256((R/weight).read_bytes()).hexdigest(),configuration_sha256={name:hashlib.sha256((D/name).read_bytes()).hexdigest() for name in ['joint-training-registry-v26.json','joint-looser-estimate-scene256-v32.json']},source_sha256={name:hashlib.sha256((R/name).read_bytes()).hexdigest() for name in ['scripts/train_wuji_robust_residual.py','scripts/g2_continuous_scene.py','scripts/wuji_scheduled_thumb_reference.py']})
(job/'identity.json').write_text(json.dumps(identity,indent=2));start=time.monotonic()
with (job/'output.log').open('w') as log:
    child=subprocess.Popen(cmd,cwd=R,env=env,stdout=log,stderr=subprocess.STDOUT);identity['child_pid']=child.pid;(job/'identity.json').write_text(json.dumps(identity,indent=2));child.wait()
identity.update(end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),exit_code=child.returncode,wall_seconds=time.monotonic()-start);(job/'result.json').write_text(json.dumps(identity,indent=2));print(json.dumps(identity),flush=True)
