"""Matched freshAdam learned-state representation pilot, no forcecontroller."""
import argparse,json,pathlib,subprocess,os,hashlib,datetime,time
p=argparse.ArgumentParser();p.add_argument('--variant',choices=['joint','jointfrozen','normal','normalfrozen'],required=True);p.add_argument('--gpu',type=int,required=True);a=p.parse_args()
R=pathlib.Path(__file__).resolve().parents[2];B=R/'runs/support-pressure-20261003';name='strong750-'+a.variant+'-support-coordinates-v128';job=B/'jobs'/name;job.mkdir(parents=True,exist_ok=False)
cmd=json.loads((B/'jobs/joint-noisier-continuation-v31/identity.json').read_text())['command'].copy();cmd[cmd.index('--resume')]='--initialize-model-from';cmd[cmd.index('--initialize-model-from')+1]='runs/support-pressure-20261003/train/joint-noisier-continuation-v31/update_000750.pth';cmd[cmd.index('--output')+1]='runs/support-pressure-20261003/train/'+name;cmd[cmd.index('--updates')+1]='100'
cmd[cmd.index('--horizon')+1]='128'
cmd[cmd.index('--takeover-seconds')+1]='14.3';cmd[cmd.index('--envs')+1]='512';cmd[cmd.index('--training-geometry-schedule')+1]='research/support-pressure-20261003/joint-training-schedule512-v107.json';cmd[cmd.index('--initial-estimate-scene')+1]='research/support-pressure-20261003/staged-support-estimate-scene512-v107.json';cmd+=['--resample-initial-estimates','--fresh-sampling-seed','2026100470']
cmd+=['--support-delta-coordinates','joint' if a.variant.startswith('joint') else 'normal','--reset-support-logstd','-.7','--gae-lambda','.98']
if a.variant.endswith('frozen'):cmd+=['--freeze-thumb-prior']
env=dict(os.environ,PATH='/home/wangjiarui/artgym-runtime/bin:/usr/bin:/bin',LD_LIBRARY_PATH='/home/wangjiarui/artgym-runtime/lib',PYTHONUTF8='1',PYTHONNOUSERSITE='1',PYTHONPATH='.:rl_games',CUDA_VISIBLE_DEVICES=str(a.gpu),TORCH_EXTENSIONS_DIR='/tmp/wuji-width-torch-extensions',OMP_NUM_THREADS='4',MKL_NUM_THREADS='4',MAX_JOBS='2',PYTHONUNBUFFERED='1')
row=dict(start_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),command=cmd,launcher_pid=os.getpid(),gpu=a.gpu,reason='Lastphysicalquietpreparation pilotstillnominalbodyFAIL despite correctcontact/strokes. Compare boundedlearned support correction coordinates around the same frozen750 legal-input supportprior: joint vs initialestimatednormal/FK motorbasis. Bothzero correctionhead preserve originalactor actions exactly, samefreshAdam/sampling/bank512/horizon128/GAE.98/100updates/explorationreset/limits. Normalfrozen extraexploratory supportonly variant with frozen750 deterministicthumbmapping, not isolatedfactorclaim or forceguarantee.',optimizer='FreshAdam on both sides; inherited model/logstd only, not oldoptimizercontinuation',source_sha256={f:hashlib.sha256((R/f).read_bytes()).hexdigest() for f in ['scripts/train_wuji_robust_residual.py','scripts/g2_continuous_scene.py','scripts/wuji_support_delta_coordinates.py','scripts/g2_r800_policy.py']})
(job/'identity.json').write_text(json.dumps(row,indent=2));start=time.monotonic()
with (job/'output.log').open('w') as f:
 child=subprocess.Popen(cmd,cwd=R,env=env,stdout=f,stderr=subprocess.STDOUT);row['child_pid']=child.pid;(job/'identity.json').write_text(json.dumps(row,indent=2));child.wait()
row.update(exit_code=child.returncode,end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),wall_seconds=time.monotonic()-start);(job/'result.json').write_text(json.dumps(row,indent=2));print(json.dumps(row),flush=True)
