"""Closed fixed512 development comparison; no primary selection or control edits."""
import pathlib,json,collections,hashlib,numpy as np,tarfile
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';base=R/'runs/robust-knife-family-20261003';names=['highload-matched-reference-development-v1','highload-AR-final-development-v1','highload-AS-final-development-v1'];ref=np.load(base/'checks'/names[0]/'initial-snapshot.npz');reference=np.load(base/'checks'/names[0]/'trace.npz');rt=reference['target'][:480].copy();rq=reference['q'][:480].copy();out={'scope':'Three fixed512 training-family development checks seed0403,maxrun/detent.5/.5,mixedomega1.7,16s takeover. Matched initial serialized residualscale.75; P50 actor tensor mean/Adam/RNG unchanged. AR/AS same parent/seed/rebuilt physics and300newupdates each, directionalcontactreward0 vs.5. Notprimary independent score/modelpromotion/bitwisecontact orlearninggain proof.','results':[]}
for name in names:
 folder=base/'checks'/name;j=json.loads((folder/'report.json').read_text());rows=[json.loads(x) for x in (folder/'episodes.jsonl').read_text().splitlines()];snap=np.load(folder/'initial-snapshot.npz');trace=np.load(folder/'trace.npz');n=j['n'];thick=np.array([p['handle_size'][1] for p in j['physical_asset_parameters']])>=.013;complete=np.array([r['operation_complete'] for r in rows]);assert len(rows)==n==512;assert int(complete.sum())==j['completed'];bad=(trace['rotation'][480:]>.25)|(trace['drift'][480:]>.01);first=np.where(bad.any(0),480+bad.argmax(0),-1);result={'name':name,'checkpoint_sha256':j['checkpoint_sha256'],'complete':int(complete.sum()),'n':n,'T13_14_complete':int((complete&thick).sum()),'T13_14_n':int(thick.sum()),'failure_counts':dict(collections.Counter(r['failure'] for r in rows if r['failure'])),'initial_fields_exact_equal_to_reference':{k:bool(np.array_equal(snap[k],ref[k])) for k in ref.files},'prefix_issuedtarget_max_diff_rad':float(abs(trace['target'][:480]-rt).max()),'prefix_actualq_max_diff_rad':float(abs(trace['q'][:480]-rq).max()),'body_first_rotation_or_drift_breach_during_operation_count':int((first>=0).sum()),'body_first_breach_median_time_s':float(np.median(first[first>=0]/30)) if (first>=0).any() else None,'report_sha256':hashlib.sha256((folder/'report.json').read_bytes()).hexdigest(),'trace_sha256':hashlib.sha256((folder/'trace.npz').read_bytes()).hexdigest()};out['results'].append(result)
out['conclusion']='Reference178, AR181, AS183 of512; none resolveshighloadbodyinstability/thick-support deficiency. Counts differ too little amid numericalcontact variation to establish directionalreward advantage. Preserve actual final350 weights/Adam/RNG and allchecks, retain primary frozenP50.';p=D/'restored-highload-paired-development-summary.json';p.write_text(json.dumps(out,indent=2));record('restored_highload_fixed_paired_development_closed',evidence=str(p.relative_to(R)),conclusion=out['conclusion'],config={'original_criteria':True,'final_updates':350,'seed':2026100403},next='Package all three actualfulltraces andrecoverabletrainingweights; nofurthercandidatebranching');print(json.dumps(out,indent=2))
files=[f for name in names for f in (base/'checks'/name).iterdir() if f.is_file()]+[p,D/'completed-restored-highload-ARAS-training.json',D/'restored-high-load-paired-training-preregistration.json',D/'highload-pair-matched-pretraining-reference.json',pathlib.Path(__file__).resolve()];archive=base/'delivery/highload-paired-development-evidence.tar.gz';assert not archive.exists();record('highload_pair_fulltrace_package_started',evidence=str(archive.relative_to(R)),next='Verify actualclosed fulltracearchive');entries=[{'path':str(f.relative_to(R)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()} for f in files]
with tarfile.open(archive,'w:gz',compresslevel=1) as tar:
 for f in files:tar.add(f,arcname=str(f.relative_to(R)),recursive=False)
m={'archive':archive.name,'archive_bytes':archive.stat().st_size,'archive_sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'files':entries,'scope':out['scope']};mp=archive.with_suffix(archive.suffix+'.manifest.json');mp.write_text(json.dumps(m,indent=2));record('highload_pair_fulltrace_package_completed',evidence=str(mp.relative_to(R)),archive_sha256=m['archive_sha256'],next='Verifypublicdownloadarchive alongsidefinalmodels');print({k:v for k,v in m.items() if k!='files'})
