"""Compare predeclared actual downloaded reexecution to fixed primary; do not rescore primary."""
import pathlib,json,hashlib,collections,numpy as np
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';plan=json.loads((D/'final-downloaded-validation-recovery-preregistration.json').read_text());base=R/'runs/robust-knife-family-20261003';results=[]
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(1048576),b''):h.update(c)
 return h.hexdigest()
for row in plan['runs']:
 old=base/'checks'/row['original'];new=R/row['output'];a=json.loads((old/'report.json').read_text());b=json.loads((new/'report.json').read_text());assert a['n']==b['n']==row['envs'];assert a['checkpoint_sha256']==b['checkpoint_sha256'];assert a['physical_asset_parameters']==b['physical_asset_parameters'];ia=np.load(old/'initial-snapshot.npz');ib=np.load(new/'initial-snapshot.npz');ta=np.load(old/'trace.npz');tb=np.load(new/'trace.npz');assert tb['q'].shape[0]==1080;result={'original':row['original'],'recovered':row['output'],'n':b['n'],'original_completed':a['completed'],'recovered_completed':b['completed'],'recovered_failures':dict(collections.Counter(x['failure'] for x in b['episodes'] if x['failure'])),'initial_fields_exact_equal':{k:bool(np.array_equal(ia[k],ib[k])) for k in ia.files},'prefix_issuedtarget_max_diff_rad':float(abs(ta['target'][:480]-tb['target'][:480]).max()),'prefix_measuredq_max_diff_rad':float(abs(ta['q'][:480]-tb['q'][:480]).max()),'checkpoint_sha256':b['checkpoint_sha256'],'report_sha256':sha(new/'report.json'),'trace_sha256':sha(new/'trace.npz')};results.append(result)
j={'scope':'Actual five downloaded default archives restored to empty remote directory, all seven predeclared 332 full36s commands executed. Original primary 204/332 is unchanged; these are restoration repetitions, not additional independent bodies or selected replacement score.','original_completed':sum(x['original_completed'] for x in results),'recovered_completed':sum(x['recovered_completed'] for x in results),'n':sum(x['n'] for x in results),'results':results,'limitations':'Original validation used local4090 with graphics/video; restored repetitions use H200 headless. GPU and physics/rendering pipeline co-vary. Byte identity and matching initialization do not imply bitwise contact trajectories; no isolated GPU/source causal claim.','native_and_offline':json.loads((D/'final-downloaded-native-and-policy-recovery.json').read_text())};assert j['original_completed']==204 and j['n']==332;p=D/'final-downloaded-fixed-validation-comparison.json';p.write_text(json.dumps(j,indent=2));record('final_downloaded_fixed_validation_recovery_comparison_completed',evidence=str(p.relative_to(R)),conclusion={'original_primary_completed':204,'recovery_completed':j['recovered_completed'],'n':332,'scope':j['scope']},next='Package full actual recovery traces/videos/receipts; preserve original primary score');print(json.dumps(j,indent=2))
