"""One predeclared final512 paired prototype comparison; primaryscore unchanged."""
import pathlib,json,hashlib,collections,numpy as np
from isaacgym import gymapi
import torch
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';base=R/'runs/robust-knife-family-20261003';names=['closing-context-initial-development-v1','closing-context-AT-final-development-v1','closing-context-AU-final-development-v1'];ref=np.load(base/'checks'/names[0]/'initial-snapshot.npz');baseline=np.load(base/'checks'/names[0]/'trace.npz');target=baseline['target'][:480].copy();q=baseline['q'][:480].copy();results=[]
for name in names:
 folder=base/'checks'/name;j=json.loads((folder/'report.json').read_text());rows=[json.loads(line) for line in (folder/'episodes.jsonl').read_text().splitlines()];assert len(rows)==512;complete=np.array([row['operation_complete'] for row in rows]);assert int(complete.sum())==j['completed'];T=np.array([p['handle_size'][1]*1000 for p in j['physical_asset_parameters']]);initial=np.load(folder/'initial-snapshot.npz');trace=np.load(folder/'trace.npz');captures=json.loads((folder/'closing-context-captures.json').read_text());assert sum(row['capture_count'] for row in captures['captures'])==512;spec=json.loads((folder/'context-spec.json').read_text());checkpoint=R/j['args']['checkpoint'];saved=torch.load(checkpoint,map_location='cpu');first=saved['model']['actor.0.weight'];thick=T>=13;breach=(trace['rotation'][480:]>.25)|(trace['drift'][480:]>.01);first_breach=np.where(breach.any(0),480+breach.argmax(0),-1);result={'name':name,'conditioning':spec['conditioning'],'completed':int(complete.sum()),'n':512,'T13_14_complete':int((complete&thick).sum()),'T13_14_n':int(thick.sum()),'failure_counts':dict(collections.Counter(row['failure'] for row in rows if row['failure'])),'initial_fields_exact_equal_to_baseline':{k:bool(np.array_equal(initial[k],ref[k])) for k in ref.files},'prefix_issuedtarget_max_diff_rad':float(abs(trace['target'][:480]-target).max()),'prefix_actualq_max_diff_rad':float(abs(trace['q'][:480]-q).max()),'actual8s_context_captured':512,'actor_context_input_column_norm':float(first[:,-1].norm()),'checkpoint_sha256':hashlib.sha256(checkpoint.read_bytes()).hexdigest(),'trace_sha256':hashlib.sha256((folder/'trace.npz').read_bytes()).hexdigest(),'body_first_rotation_or_drift_breach_count':int((first_breach>=0).sum()),'body_first_breach_median_time_s':float(np.median(first_breach[first_breach>=0]/30)) if (first_breach>=0).any() else None};results.append(result)
j={'scope':'Registeredcachedclosingcontext155D prototype pairednew300updates vsconstantnominal andzero-column P50baseline. Fixedseed0503 full36s512 trainingfamilydevelopmentcases; not originalfrozen332/independentwholepolicy validation orhardware. Allattempts/criteria retained, nointermediate selection.','results':results,'comparison_limitations':'Contextprovided toactorandcritic, notactoronly causal isolation. GPUcontactreplays notbitwiseequal despiteexactinitialfields/issuedprefix. Priorgeometry-supervision heldout groups participated inRLtraining. Noforce/hardware claim fromcachedshapeproxy.','decision':'Preserveallresults/models; originalP50 and332primary outcomes remainfinalindependentreference. Interpretcountchanges withthick-support behavior, notfewcasesasalgorithmadvantage.'};p=D/'closing-context-paired-development-summary.json';p.write_text(json.dumps(j,indent=2));record('closing_context_registered_final_paired_development_closed',evidence=str(p.relative_to(R)),config={'fixedseed':2026100503,'n_each':512,'new_updates_each':300,'results':[{k:r[k] for k in ['name','completed','n','T13_14_complete','T13_14_n']} for r in results]},conclusion=j['decision'],next='Packageallactualfinal350 weights/Adam/RNG plusfixedfulltraces andportableDprototype; nofurtherbranching');print(json.dumps(j,indent=2))
