"""Locate recorded physical hand-q divergence before learned takeover; no simulation."""
import pathlib,json,hashlib,datetime
import numpy as np
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';comparison=json.loads((D/'final-downloaded-fixed-validation-comparison.json').read_text());outcome=json.loads((D/'final-downloaded-paired-episode-agreement.json').read_text());lookup={(x['group'],x['env']):x for x in outcome['cases']};groups=[];cases=[]
for row in comparison['results']:
 pa=R/'runs/robust-knife-family-20261003/checks'/row['original']/'trace.npz';pb=R/row['recovered']/'trace.npz'
 with np.load(pa) as a,np.load(pb) as b:
  assert a['q'].shape==b['q'].shape==(1080,row['n'],20);delta=np.abs(a['q'][:479]-b['q'][:479]).max(axis=2);issued=np.abs(a['target'][:479]-b['target'][:479]).max();assert issued==0
  for env in range(row['n']):
   ids=np.flatnonzero(delta[:,env]>1e-3);first=float((ids[0]+1)/30) if len(ids) else None;x=lookup[(row['original'],env)];cases.append({'group':row['original'],'env':env,'instance':x['instance'],'original':x['original'],'recovered':x['recovered'],'prefix_q_max_difference_rad':float(delta[:,env].max()),'first_recorded_1e_minus3_rad_difference_poststep_seconds':first})
  groups.append({'group':row['original'],'n':row['n'],'before_16s_hand_q_threshold_exceeded':int((delta.max(axis=0)>1e-3).sum()),'issued_targets_prefix_max_error_rad':float(issued)})
changed=[x for x in cases if (x['original']=='pass')!=(x['recovered']=='pass')];j={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'diagnostic_threshold_rad':.001,'strict_prefix_records':479,'last_prefix_poststep_time_seconds':479/30,'total_before_takeover_diverged':sum(x['first_recorded_1e_minus3_rad_difference_poststep_seconds'] is not None for x in cases),'different_binary_outcomes':len(changed),'different_outcome_with_prefix_divergence':sum(x['first_recorded_1e_minus3_rad_difference_poststep_seconds'] is not None for x in changed),'groups':groups,'cases':cases,'scope':'Saved post-step physical hand q, not measured actor q. First479 records strictlybefore16s learnedtakeover, allissued27Dtargetsexact. 1e-3rad is descriptive divergence threshold, not altered taskcriterion. GPU and graphics/physics pipeline jointly changed; no isolatedcause or solverstate diagnosis.'};p=D/'final-downloaded-before-takeover-divergence.json';p.write_text(json.dumps(j,indent=2));record('saved_restoration_prefix_physical_divergence_located',evidence=str(p.relative_to(R)),config={k:j[k] for k in ['total_before_takeover_diverged','different_binary_outcomes','different_outcome_with_prefix_divergence']},next='Publish final reproducibility limits; no addedphysics/tuning');print({k:j[k] for k in ['total_before_takeover_diverged','different_binary_outcomes','different_outcome_with_prefix_divergence','groups']})
