"""Pair all fixed original/recovery outcomes without fitting or redefining criteria."""
import pathlib,json,hashlib,collections,datetime
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';plan=json.loads((D/'final-downloaded-fixed-validation-comparison.json').read_text());tot=collections.Counter();matrix=collections.Counter();groups=[];cases=[]
for row in plan['results']:
 a=R/'runs/robust-knife-family-20261003/checks'/row['original']/'report.json';b=R/row['recovered']/'report.json';old=json.loads(a.read_text());new=json.loads(b.read_text());assert old['args']['seed']==new['args']['seed'];assert old['physical_asset_instances']==new['physical_asset_instances'];assert len(old['episodes'])==len(new['episodes'])==row['n'];count=collections.Counter()
 for x,y in zip(old['episodes'],new['episodes']):
  assert (x['env'],x['instance'],x['control_steps'])==(y['env'],y['instance'],y['control_steps']);u=bool(x['operation_complete']);v=bool(y['operation_complete']);key=('pass' if u else 'fail')+' -> '+('pass' if v else 'fail');count[key]+=1;tot[key]+=1;left='pass' if u else x['failure'];right='pass' if v else y['failure'];matrix[(left,right)]+=1;cases.append({'group':row['original'],'env':x['env'],'instance':x['instance'],'original':left,'recovered':right})
 groups.append({'group':row['original'],'n':row['n'],'outcomes':dict(count),'original_report_sha256':hashlib.sha256(a.read_bytes()).hexdigest(),'recovered_report_sha256':hashlib.sha256(b.read_bytes()).hexdigest()})
assert tot['pass -> pass']+tot['pass -> fail']==204;assert tot['pass -> pass']+tot['fail -> pass']==185;assert sum(tot.values())==332
j={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'n':332,'outcomes':dict(tot),'same_binary_outcome':tot['pass -> pass']+tot['fail -> fail'],'failure_category_transitions':[{'original':a,'recovered':b,'count':n} for (a,b),n in sorted(matrix.items())],'groups':groups,'cases':cases,'scope':'Paired repetition of same fixed full36s conditions, not added independent samples. GPU and graphics/physics pipeline co-vary. No controller/criteria change or causal inference. Some per-episode scope strings are inherited shared training-collector template; top-level check report, original freeze/registration and this paired role define actual validation/recovery status.'};p=D/'final-downloaded-paired-episode-agreement.json';p.write_text(json.dumps(j,ensure_ascii=False,indent=2));record('final_downloaded_fixed_episode_outcome_agreement_analyzed',evidence=str(p.relative_to(R)),config={'outcomes':dict(tot),'n':332},conclusion='Paired every original/recovered env/instance; sameinitialcriteria, preserve originalscore. No newphysics/modelselection.',next='Include portability disagreement in finalreport; complete publication');print({k:j[k] for k in ['n','outcomes','same_binary_outcome','failure_category_transitions']})
