"""Assemble explicit portable Release payload; excludes preparatory/superseded files."""
import pathlib,json,hashlib,datetime,subprocess
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';base=R/'runs/robust-knife-family-20261003/delivery'
archives=['wuji-g2-source-final.tar.gz','models-and-recovery-final.tar.gz','under-family-v1-assets-caches.tar.gz','height-sensitivity-assets-v1.tar.gz','fresh-validation-assets-v1.tar.gz','dense-family-v1-assets-caches.tar.gz','longside-family-v1-assets-caches.tar.gz','continuous-demos-and-failures.tar.gz','independent-validation-all332.tar.gz','restoration-execution-evidence.tar.gz','legal-support-estimator-data.tar.gz','frozen-development-evidence-final.tar.gz','execution-receipts-final.tar.gz','highload-paired-development-evidence.tar.gz','secondary-context-and-material-evidence.tar.gz','closing-context-adaptation-evidence.tar.gz','final-downloaded-recovery-evidence.tar.gz']
names=[n for a in archives for n in [a,a+'.manifest.json'] if (base/n).exists()];assert all((base/a).is_file() for a in archives);names+=[a+'.entries.manifest.json' for a in archives if (base/(a+'.entries.manifest.json')).exists()];names+=['continuous-demo-success-and-failure-v2.mp4','continuous-demo-success-and-failure-v2.manifest.json','restore_wuji_robust_delivery.py','FINAL-REPORT.md','RELEASE-NOTES.md']
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(1024*1024),b''):h.update(c)
 return h.hexdigest()
default=set(archives[:5]);items=[]
for name in names:
 p=base/name;assert p.is_file();items.append({'name':name,'bytes':p.stat().st_size,'sha256':sha(p),'kind':'tar.gz' if name.endswith('.tar.gz') else p.suffix.lstrip('.'),'restore_default':name in default})
source=json.loads((base/'wuji-g2-source-final.tar.gz.manifest.json').read_text());freeze=json.loads((D/'freeze.json').read_text());local_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip();mapping=json.loads((D/'github-commit-map.json').read_text());j={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'release_tag':'wuji-g2-continuous-knife-robust-20261003-v1','release_url':'https://github.com/Jr-kelly/artgym/releases/tag/wuji-g2-continuous-knife-robust-20261003-v1','source_archive_local_git_commit':source['source_commit'],'source_archive_github_commit':mapping.get(source['source_commit']),'source_archive_git_tree_sha1':source.get('source_tree'),'current_local_delivery_git_commit':local_commit,'current_github_delivery_commit':mapping.get(local_commit),'source_archive_scope':'TrackedGit source exceptold research/multigrasp-20260928/evidence/ only; SDK/privatehumanmedia/userFrankaexcluded. Original1258frozenruntime files identical. Sourcearchive can precede finalauditclosure-only Gitcommit.','primary_candidate':freeze['policy'],'primary_independent_validation':{'n':332,'completed':204,'failure_counts':{'body unstable/drop':83,'pickup/hold':44,'retraction':1},'scope':'Originalfrozen sameP50/criteria; laterconditional/developmentresearch separate'},'artifacts':items,'checksum_scope':'Alllistedactualartifacts plusrelease-manifest.json inSHA256SUMS; checksumfile cannot include itsownhash. Publication/tag verification recorded separately afterdraftrelease ispublished.','restore':'python3 restore_wuji_robust_delivery.py --artifacts ARTIFACTS --destination NEW_EMPTY_ROOT','environment':'Python3.8/PyTorch2.1.0+cu118/IsaacGymPreview4TacSL; SDKexternal. SeeRESTORE.md andexactpipfreezes.','no_real_robot_actions':True}
p=base/'release-manifest.json';p.write_text(json.dumps(j,ensure_ascii=False,indent=2));lines=[item['sha256']+'  '+item['name'] for item in items];lines.append(sha(p)+'  release-manifest.json');(base/'SHA256SUMS').write_text('\n'.join(lines)+'\n');record('final_release_flat_manifest_assembled',evidence=str(p.relative_to(R)),config={'artifacts':len(items),'bytes':sum(x['bytes'] for x in items),'default_restore_names':sorted(default),'source_archive_commit':source['source_commit']},next='Uploadactualmanifest/checksums, downloadthem, verifyallpayload andfreshdefaultrestore beforepublication');print({'artifacts':len(items),'bytes':sum(x['bytes'] for x in items),'manifest_sha256':sha(p)})
