import json,pathlib,datetime,hashlib,subprocess,collections
from scripts.record_wuji_robust_goal import record
from scripts.host_tool_environment import host_tool_environment
R=pathlib.Path.cwd();D=R/'research/robust-knife-family-20261003';now=datetime.datetime.now(datetime.timezone.utc);start=datetime.datetime.fromisoformat('2026-10-02T18:53:50+00:00');elapsed=(now-start).total_seconds();assert elapsed>=43200,elapsed
ssh=['ssh','-o','BatchMode=yes','-o','ConnectTimeout=10','-p','33024','wangjiarui@10.13.160.5'];p=subprocess.run(ssh+['nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used --format=csv,noheader,nounits; nvidia-smi --query-compute-apps=gpu_uuid,pid,process_name,used_memory --format=csv,noheader,nounits'],capture_output=True,text=True,timeout=25,env=host_tool_environment());assert p.returncode==0,p.stderr;lines=p.stdout.splitlines();assert len(lines)==4,lines
rows=[json.loads(x) for x in (D/'resources.jsonl').read_text().splitlines()];pts=sorted((datetime.datetime.fromisoformat(r['utc']).timestamp(),r['whole_machine_current_mean']) for r in rows if 'whole_machine_current_mean' in r); t=now.timestamp();low=t-14400;total=covered=0.;maxgap=0.
for (a,u),(b,_) in zip(pts,pts[1:]):
 if b<low or a>t:continue
 duration=max(0,min(b,t)-max(a,low));maxgap=max(maxgap,b-a);observed=duration if b-a<=45 else 0.;covered+=observed;total+=u*observed
bound=total/14400;assert bound>27,bound;assert t-pts[-1][0]<60
jobs=R/'runs/robust-knife-family-20261003/jobs';identities=list(jobs.glob('*/identity.json'));assert all((p.parent/'result.json').exists() for p in identities);results=[json.loads(p.read_text()) for p in jobs.glob('*/result.json')];assert not any(x.get('remote_status_unknown') for x in results)
def sha(path):
 h=hashlib.sha256()
 with path.open('rb') as f:
  for chunk in iter(lambda:f.read(1048576),b''):h.update(chunk)
 return h.hexdigest()
f=json.loads((D/'freeze.json').read_text());checks=dict(f['released_runtime_files_sha256']);checks.update(f['frozen_inputs_sha256']);checks.update(f['base_weights_sha256']);checks[f['policy']['checkpoint_path']]=f['policy']['sha256'];assert all(sha(R/n)==s for n,s in checks.items())
j={'utc':now.isoformat(),'round_start_utc':start.isoformat(),'round_elapsed_hours':elapsed/3600,'minimum_12h_met':True,'useful_work_scope':'Actual G2 compatibility, pickup/operation implementation, paired RL, frozen validation, failed attempts, actual archive downloads and executed recovery, contact diagnosis and GitHub delivery; no padding jobs. GPU training closed before delivery work.','remote_current_gpu_lines':lines,'remote_current_compute_processes':[],'rolling4h_conservative_lower_bound_percent':bound,'rolling4h_observed_seconds':covered,'rolling4h_missing_seconds_treated_as_zero':14400-covered,'max_sample_gap_seconds':maxgap,'first_full4h_evidence':'resources-first-full4h.json','exact_round_first4h':json.loads((D/'round-start-first4h-conservative-resource-audit.json').read_text()),'registered_jobs':len(results),'process_exit_codes':dict(collections.Counter(str(x['exit_code']) for x in results)),'all_jobs_have_final_results':True,'remote_status_unknown':False,'new_registered_job_allocated_gpu_hours':sum(x['gpu_hours'] for x in results),'gpu_hours_scope':'Wrapper allocation walltime only; direct native simulations excluded. Not an exhaustive GPU utilization integral and not task success counts. No GPU hour cap.','frozen_runtime_file_count':len(f['released_runtime_files_sha256']),'frozen_runtime_inputs_base_and_primary_exact':True,'primary_weights_sha256':f['policy']['sha256'],'no_real_robot_actions':True,'historical_missing_child_receipts':'historical-missing-child-receipt-explanations.json'}
p=D/'FINAL-RESOURCE-AUDIT.json';p.write_text(json.dumps(j,ensure_ascii=False,indent=2));record('minimum_12h_and_final_resource_source_gates_verified',evidence=str(p.relative_to(R)),conclusion=f'Conservative rolling4h {bound:.6f}% >27%; actual round {elapsed/3600:.6f}h; all285 jobs closed; frozen runtime/inputs/P50 unchanged',next='Publish prepared exact-tree Git snapshot, flat manifest and draft Release',state_updates={'minimum_12h_verified':True,'final_resource_verified':True,'full_demo_method':'Scripted G2 TABLEedge pickup + calibrated geometric thumb reference + actually trained bounded P50 residual; nominal continuous success, necessary generalization tested with unresolved thick/raised-slider/highload support'})
print(json.dumps(j,ensure_ascii=False))
