"""Plot recorded motor/contact/body diagnostics for actual downloaded success/failure only."""
import pathlib,json,hashlib,numpy as np
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';output=D/'contact-behavior-figure-v1';output.mkdir(exist_ok=True);fig,axes=plt.subplots(6,2,figsize=(13,14),sharex=True);rows=[]
for col,(name,label) in enumerate([('final-downloaded-P50-heavy-v68','Full success: .2/.2 N authored amplitudes'),('final-downloaded-P50-failure-v69','Failure: .5/.5 N authored amplitudes')]):
 folder=R/'runs/robust-knife-family-20261003/demo'/name;z=np.load(folder/'trace.npz');report=json.loads((folder/'report.json').read_text());physics=json.loads((folder/'physics.json').read_text());parameters=json.loads((R/pathlib.Path(report['physical_asset']).parent/'parameters.json').read_text());t=z['time'];op=t>=16;held=(t>=12)&(t<16);origin=z['object'][np.flatnonzero(held)[-1]];rotation=np.full(len(t),np.nan);rotation[op]=(Rotation.from_quat(origin[3:7]).inv()*Rotation.from_quat(z['object'][op,3:7])).magnitude();drift=np.full(len(t),np.nan);drift[op]=np.linalg.norm(z['object'][op,:3]-origin[:3],axis=1)*1000;assert abs(rotation[op].max()-report['operation_body_max_rotation_rad'])<1e-8;assert abs(drift[op].max()/1000-report['operation_body_max_drift_m'])<1e-8
 hand=np.array(physics['hand_indices']);thumb=hand[16:20];lag=abs(z['target'][:,thumb]-z['q'][:,16:20]).max(1);fraction=(abs(z['torque'][:,thumb])/np.array(physics['effort'])[thumb]).max(1);assert fraction.max()<1.00001;slider=z['finger_slider_contacts'][:,0]>0;body=z['finger_body_contacts'][:,0]>0;travel=(z['slider']-parameters['joint_lower'])*1000;issued_time=np.arange(len(t))/30.;goal=np.where(issued_time>=16,np.where(((np.maximum(issued_time-16,0))//5)%2==0,40,0),0)
 axes[0,col].plot(t,travel,color='#1976a3',label='Actual slider travel');axes[0,col].step(t,goal,where='post',color='#777',ls='--',lw=1,label='Known scheduled goal');axes[0,col].set_title(label,fontsize=11);axes[0,col].set_ylabel('Slider q - lower [mm]');axes[0,col].set_ylim(-2,53)
 axes[1,col].step(t,slider.astype(int),color='#1976a3',label='Thumb / slider contact');axes[1,col].step(t,body.astype(int)+1.3,color='#bd5e24',label='Thumb / body contact (+1.3)');axes[1,col].set_yticks([0,1,1.3,2.3]);axes[1,col].set_yticklabels(['no','yes','no','yes']);axes[1,col].set_ylim(-.15,2.5);axes[1,col].set_ylabel('Actual solver contact pair')
 axes[2,col].plot(t,lag,color='#1976a3',label='Max of 4 thumb joint lags');axes[2,col].set_ylabel('Issued q - physical q\nabsolute max [rad]')
 axes[3,col].plot(t,z['load'],color='#222',lw=1,label='Total authored joint force');axes[3,col].plot(t,z['dissipative_load'],color='#1976a3',lw=.8,alpha=.75,label='Dissipative part');axes[3,col].plot(t,z['passive_groove_load'],color='#bd5e24',lw=.8,alpha=.75,label='Startup + groove potential');axes[3,col].set_ylabel('Signed authored slider\njoint force [N]')
 axes[4,col].plot(t,fraction,color='#1976a3',label='Max thumb applied torque / effort');axes[4,col].axhline(1,color='#bd5e24',ls='--',lw=1,label='Original effort ceiling');axes[4,col].set_ylabel('Applied thumb torque fraction');axes[4,col].set_ylim(-.05,1.08)
 axes[5,col].plot(t,rotation,color='#1976a3',label='Rotation from hold reference');axes[5,col].axhline(.25,color='#1976a3',ls='--',lw=.8,label='Rotation criterion .25 rad');axes[5,col].set_ylabel('Body rotation [rad]');right=axes[5,col].twinx();right.plot(t,drift,color='#bd5e24',label='Body drift');right.axhline(10,color='#bd5e24',ls=':',lw=.8);right.set_ylabel('Body drift [mm]',color='#bd5e24');right.tick_params(axis='y',labelcolor='#bd5e24');axes[5,col].set_xlabel('Time from TABLE start [s]')
 for ax in axes[:,col]:
  ax.axvspan(0,16,color='#e5e8eb',alpha=.4);ax.axvline(16,color='#444',lw=.8);ax.set_xlim(0,36);ax.grid(alpha=.15);ax.legend(loc='upper left',fontsize=7)
 loss=report['failure_onsets_s']['sustained_thumb_slider_contact_loss']
 if loss is not None:
  for ax in axes[:,col]:ax.axvline(loss,color='#b21c36',lw=.8,ls=':')
  axes[0,col].text(loss+.4,8,'Sustained thumb/slider\ncontact loss: '+str(loss)+' s',color='#b21c36',fontsize=8)
 rows.append({'name':name,'trace_sha256':hashlib.sha256((folder/'trace.npz').read_bytes()).hexdigest(),'full_success':report['full_success'],'operation_samples':int(op.sum()),'thumb_slider_fraction':float(slider[op].mean()),'thumb_body_fraction':float(body[op].mean()),'max_authored_joint_force_abs_N':float(abs(z['load'][op]).max()),'max_thumb_lag_rad':float(lag[op].max()),'max_thumb_applied_effort_fraction':float(fraction[op].max()),'thumb_any_joint_at_effort_ceiling_fraction':float((fraction[op]>=.999).mean()),'body_rotation_rad':float(rotation[op].max()),'body_drift_mm':float(drift[op].max()),'failure_onsets_s':report['failure_onsets_s']})
fig.suptitle('Same frozen P50: effective slider contact, motor response and grip stability',fontsize=14);fig.text(.02,.015,'Two fixed actual36s recovery episodes, not a reliability estimate. Contacts/physical state are evaluation-only.\nJoint lag is not pressure; authored slider force is not real total resistance. Signed potential forces can assist on descent.\nApplied torque includes original gravity compensation and clipping. No policy/controller changes or added physics runs.',fontsize=9);fig.tight_layout(rect=(0,.07,1,.965));fig.savefig(output/'contact-behavior.png',dpi=150);fig.savefig(output/'contact-behavior.pdf');j={'results':rows,'scope':'Retrospective visualization of two fixed actual GitHubdownloaded emptyrestore native36s runs. No new episodes, candidate scores, hardware or causal force claim. qlag uses physical poststep DOF vs actualissued targets; not measured pressure. Force is lastsubstep authored passive slider joint actuation at30Hz snapshots, excludes engine material friction and hand traction.','reference':'Original runner held12–16s lastsample reference and same bodycriteria reused; goal40mm not moved; mechanical50mm approximate, not measuredrealtravel.'};(output/'data.json').write_text(json.dumps(j,indent=2));record('final_representative_contact_motor_body_behavior_visualized',evidence=str((output/'data.json').relative_to(R)),config={'runs':rows},next='Review scientificfigure and explain effectivecontact/force/wholegrip distinctions in final delivery');print(json.dumps(j,indent=2))
