"""Execute predeclared fixed332 commands after actual empty archive restoration."""
import pathlib,json,subprocess,os,concurrent.futures,hashlib,shlex
from scripts.record_wuji_robust_goal import record
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research/robust-knife-family-20261003';plan=json.loads((D/'final-downloaded-validation-recovery-preregistration.json').read_text());fresh=plan['destination'];py='/home/agiuser/miniconda3/envs/artgym/bin/python';remote='/home/wangjiarui/artgym-runtime/bin/python';ssh=['ssh','-o','BatchMode=yes','-p','33024','wangjiarui@10.13.160.5'];env=os.environ.copy();env['WUJI_WIDTH_SSH_ARGV']=json.dumps(ssh)
# A separately copied audit receipt must be created by the realrestore verifier.
receipt=json.loads((D/'final-downloaded-remote-empty-restore-audit.json').read_text());assert receipt['released_runtime_files_verified']==1258 and receipt['primary_checkpoint_sha256']=='73ccd0bd130364468d4ba02140f102384206ef9916a9d1633472590acac41714';assert receipt['destination']==fresh
record('final_downloaded_fixed_validation_recovery_started',evidence='research/robust-knife-family-20261003/final-downloaded-validation-recovery-preregistration.json',config={'actual_fresh_root':fresh,'fixed_episodes':332,'gpus':plan['gpus']},next='Execute allfixedfull36s commands onrestoredbytes; nofitting/candidatechange/newindependentobject claim')
def lane(index):
 gpu=plan['gpus'][index];results=[]
 for row in plan['runs'][index::2]:
  cmd=[remote,'-m','scripts.check_g2_continuous_scene','--output',row['output'],'--envs',str(row['envs']),'--seed',str(row['seed']),'--randomization-scale',str(row['randomization_scale']),'--load-profile',row['load_profile'],'--load-frequency',str(row['load_frequency']),'--load-max',str(row['load_max']),'--detent-max',str(row['detent_max']),'--checkpoint',row['checkpoint'],'--takeover-seconds',str(row['takeover_seconds']),'--compatibility-gate',row['compatibility_gate'],'--steps',str(row['steps']),'--instances',*row['instances']];name='release-recovery-'+row['original'];shell='cd '+shlex.quote(fresh)+' && exec '+shlex.join(cmd);args=[py,'-m','scripts.wuji_robust_jobs','--gpu',str(gpu),'--seconds','1800','--remote-root','/tmp/artgym-robust-20261003',name,'--','bash','-c',shell];code=subprocess.call(args,cwd=R,env=env);assert code==0,(name,code);results.append({'name':name,'gpu':gpu,'code':code,'fresh_output':fresh+'/'+row['output']});print(json.dumps(results[-1]),flush=True)
 return results
with concurrent.futures.ThreadPoolExecutor(2) as pool:results=[row for batch in pool.map(lane,[0,1]) for row in batch]
p=D/'final-downloaded-fixed-validation-job-execution.json';p.write_text(json.dumps({'results':results,'scope':'Actualrestoredprimary332 reexecution; comparison awaited, originalindependentscore remains204/332'},indent=2));record('final_downloaded_fixed_validation_recovery_jobs_completed',evidence=str(p.relative_to(R)),config={'commands':len(results)},next='Copyallclosedreports/fulltraces andcompareinitialfields/prefix/sourceconditions; noscoreselection')
