import sys,os,subprocess,pathlib,json,time,shutil,hashlib
R=pathlib.Path("/data/research/artgym-experiments-20260921/robust-knife-family-20261003");fresh=pathlib.Path("/tmp/wuji-final-release-restore-local-20261003");sys.path.insert(0,str(R));from scripts.record_wuji_robust_goal import record,D
py="/home/agiuser/miniconda3/envs/artgym/bin/python";env=dict(os.environ,CUDA_VISIBLE_DEVICES="0",LD_LIBRARY_PATH="/home/agiuser/miniconda3/envs/artgym/lib",PYTHONPATH=".:rl_games",PYTHONNOUSERSITE="1",PYTHONUTF8="1",PATH="/home/agiuser/miniconda3/envs/artgym/bin:/usr/bin:/bin",TORCH_EXTENSIONS_DIR="/tmp/wuji-width-torch-extensions",OMP_NUM_THREADS="4",MKL_NUM_THREADS="4",MAX_JOBS="2",PYTHONUNBUFFERED="1")
subprocess.run(["nvidia-smi","--query-compute-apps=process_name","--format=csv,noheader"],check=True)
name="runs/robust-knife-family-20261003/demo/final-downloaded-P50-failure-v69";checkpoint="runs/robust-knife-family-20261003/train/geometric-P1/update_000050.pth"
cmd=[py,"-m","scripts.run_g2_robust_demo","--output",name,"--video","--seconds","36","--dx=-.1985","--dy=.05","--yaw=0","--slider-face","up","--grasp-plan","research/robust-knife-family-20261003/functional-side-edge-under-support-equilibrium-v6/motor-plan.json","--table-calibration","research/robust-knife-family-20261003/functional-side-edge-under-support-v6/localization.json","--acquisition-path","research/robust-knife-family-20261003/functional-side-edge-under-support-lateral-v3/acquisition-path.json","--handover-calibration","research/robust-knife-family-20261003/handover-from-v25-v1.json","--residual-checkpoint",checkpoint,"--load",".5","--detent",".5","--load-profile","pulse","--load-frequency","2.9","--hand-friction",".8","--knife-friction","2.4","--observation-noise",".002","--observation-bias",".006","--seed","2026100358"]
record("final_downloaded_failure_native_full_demo_started",config={"root":str(fresh),"command":cmd,"parent_process":os.getpid()},next="Execute actual36s TABLEworkflow from actualGitHubdownloaded independently extracted source/models/assets; compare legalmotor replay")
log=D/"final-downloaded-failure-native-demo.log"
with log.open("w") as f:result=subprocess.run(cmd,cwd=fresh,env=env,stdout=f,stderr=subprocess.STDOUT)
assert result.returncode==0,result.returncode
shutil.copytree(fresh/name,R/name)
report=json.loads((R/name/"report.json").read_text());record("final_downloaded_failure_native_full_demo_completed",evidence=name+"/report.json",conclusion={"full_success":report["full_success"],"scope":"Actual actualGitHubdownloaded archiveexecution, not just fileverification; originalcriteria unchanged"},next="Verify600 actual measured operationframes through independently loaded completepolicy")
offline="runs/robust-knife-family-20261003/deploy/final-downloaded-P50-failure-offline-v4";cmd=[py,"-m","scripts.replay_g2_continuous_policy","--demo",name,"--checkpoint",checkpoint,"--output",offline]
record("final_downloaded_failure_complete_policy_offline_replay_started",config={"command":cmd},next="Read only measuredq/FK/realhistory/issuedtargets andoncecalibration; fileonlyoutput")
with (D/"final-downloaded-failure-offline-replay.log").open("w") as f:result=subprocess.run(cmd,cwd=fresh,env=env,stdout=f,stderr=subprocess.STDOUT)
assert result.returncode==0;shutil.copytree(fresh/offline,R/offline);j=json.loads((R/offline/"report.json").read_text());assert j["motor_parity_passed"];p=D/"final-downloaded-failure-native-and-policy-recovery.json";p.write_text(json.dumps({"native_report":name+"/report.json","full_success":report["full_success"],"offline_report":offline+"/report.json","offline":j,"scope":"Fresh portablearchive bytes execute actualcontinuousphysics and600framecompletelegalmotorreplay; not exactPhysX checkpointresume orhardwaredelivery"},indent=2));record("final_downloaded_failure_complete_policy_offline_replay_completed",evidence=str(p.relative_to(R)),conclusion={"samples":j["samples"],"maximum_motor_target_error_rad":j["maximum_motor_target_error_rad"],"motor_parity_passed":j["motor_parity_passed"]},next="Package freshexecution receipts/videos and finishGitHubdelivery")
print(json.dumps({"full_success":report["full_success"],"offline":j}),flush=True)
