"""Independent original mesh/limit/facing screen for both direction paths."""
import argparse,json,hashlib
from pathlib import Path
import numpy as np
from scipy.spatial import ConvexHull
from scripts.g2_contact_geometry import DigitGeometry

def main():
 p=argparse.ArgumentParser();p.add_argument('--reference',type=Path,required=True);p.add_argument('--motor-plan',type=Path,required=True);p.add_argument('--operation-plan',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();assert not a.output.exists();ref=json.loads(a.reference.read_text());assert ref['all_feasible'] and ref['reverse_motor_preload']['all_feasible'];plan=json.loads(a.motor_plan.read_text());op=json.loads(a.operation_plan.read_text());g=DigitGeometry(max_face_axes=10000);closed=np.array(plan.get('post_lift_close_q',plan['close_q']));shifts=np.array([r['shift_m'] for r in ref['rows']]);q=np.array([r['q_thumb'] for r in ref['rows']]);reverse=np.array([r['q_thumb'] for r in ref['reverse_rows']]);assert np.allclose(shifts,[r['shift_m'] for r in ref['reverse_rows']]);w=np.array(op['wrist_in_knife']);v=np.concatenate([p for p,_ in g.meshes['hand_r_thumb_pad_link']]);hull=ConvexHull(v);centers=v[hull.simplices].mean(1);normals=hull.equations[:,:3];rows=[]
 for shift in np.linspace(0,.04,81):
  forward=np.array([np.interp(shift,shifts,q[:,i]) for i in range(4)]);backward=np.array([np.interp(shift,shifts,reverse[:,i]) for i in range(4)])
  for weight in np.linspace(0,1,5):
   actual=closed.copy();actual[16:]+=forward*(1-weight)+backward*weight-q[0];gaps=g.self_gaps(actual,'thumb')+g.pair_gaps(actual,[('hand_r_thumb_pad_link','hand_r_base_link'),('hand_r_thumb_link4','hand_r_base_link')]);minimum=min(r['gap_lower_bound_m'] for r in gaps);margin=float(np.minimum(actual-g.w.lower,g.w.upper-actual).min());m=w@g.w.forward(actual)['hand_r_thumb_pad_link'];vertices=v@m[:3,:3].T+m[:3,3];fc=centers@m[:3,:3].T+m[:3,3];support=fc[:,1]<=vertices[:,1].min()+.0004;facing=float((normals@m[:3,:3].T@[0,-1,0])[support].max()) if support.any() else -1.;rows.append(dict(shift_m=float(shift),reverse_weight=float(weight),minimum_original_limit_margin_rad=margin,minimum_thumb_self_gap_m=minimum,supporting_facet_facing_cosine=facing,passed=margin>=.005-1e-7 and minimum>=.000015-1e-7 and facing>=.25))
 result=dict(all_passed=all(r['passed'] for r in rows),samples=len(rows),reference_sha256=hashlib.sha256(a.reference.read_bytes()).hexdigest(),motor_plan_sha256=hashlib.sha256(a.motor_plan.read_bytes()).hexdigest(),rows=rows,scope='Original motor self, jointmargin and actual supportinghull facing at81stroke positions/5known directionblends; no objectseparation/force or physicalsuccess claim. Original.025rad runtime limiter required.');a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(result,indent=2));print(json.dumps({k:v for k,v in result.items() if k!='rows'}),flush=True);assert result['all_passed'],'Do not execute invalid direction blend'
if __name__=='__main__':main()
