"""Browsable uncut simulation report, with original cameras and synchronized video."""
import argparse,hashlib,html,json,shutil,zipfile
from pathlib import Path

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);B=Path('runs/singlepush-20261005');D=Path('research/singlepush-20261005');records=[]
 cases=[('baseline','baseline/nominal-reference-v1','singlepush-synchronized.mp4','原基线 · 0.7355 N'),('reference','final/local-reference-video-v1','singlepush-reference.mp4','最终 · 0.7355 N'),('load125','final/local-125-video-v1','singlepush-load125.mp4','最终 · 1.25 N'),('load150-failed','final/local-150-video-v1','singlepush-load150-failed.mp4','最终 · 1.5 N · 失败')]
 for name,root,composite,title in cases:
  root=B/root;ev=json.loads((root/'simulation/extension-evaluation.json').read_text());meta=json.loads((root/composite).with_suffix('.json').read_text());assert meta['uncut'] and meta['frames']==660;copies=[(root/composite,'singlepush-'+name+'.mp4'),(root/'simulation/continuous.mp4',name+'-continuous.mp4'),(root/'simulation/hand-closeup.mp4',name+'-closeup.mp4')]
  for src,dst in copies:shutil.copy2(src,a.output/dst)
  records.append(dict(name=name,title=title,evaluation=ev,frames=meta['frames'],fps=meta['fps'],duration_s=meta['duration_s'],source_trial=str(root/'simulation'),videos={dst:hashlib.sha256((a.output/dst).read_bytes()).hexdigest() for src,dst in copies},weight_sha256='6e89a2bb86ec4b94eba8db39bab54cc841594955bd971311353f5c7d2aaf6a9e'))
 (D/'VIDEO-MANIFEST.json').write_text(json.dumps(records,indent=2));results=json.loads((D/'DELIVERY-RESULTS.json').read_text());table=''.join('<tr><td>'+html.escape(r['label'])+'</td><td>%.3f</td><td>%.3f</td><td>%s</td></tr>'%(r['evaluation']['active_forward_m']*1000,r['evaluation']['hold_range_m']*1000,'通过' if r['evaluation']['pass_all'] else '失败') for r in results['trials'])
 sections=[]
 for r in records:
  e=r['evaluation'];videos=list(r['videos']);sections.append('<section id="'+r['name']+'"><h2>'+r['title']+'</h2><p>'+('通过全部十项检查' if e['pass_all'] else '失败：有效推进未严格超过20 mm')+' · 主动位移 %.3f mm · 保持波动 %.3f mm · cap接触 %.1f%%</p>'%(e['active_forward_m']*1000,e['hold_range_m']*1000,e['effective_cap_contact_fraction']*100)+'<video controls preload="metadata" src="'+videos[0]+'"></video><details><summary>原始完整机位 · 同时刻 · 无剪切</summary><div class="raw">'+''.join('<video controls preload="metadata" src="'+v+'"></video>' for v in videos[1:])+'</div></details></section>')
 page='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>G2＋Wuji 单次推进交付</title><style>body{margin:auto;padding:24px;max-width:1200px;background:#111827;color:#e5e7eb;font:17px/1.7 system-ui}h1{font-size:30px}a{color:#93c5fd}nav{display:flex;gap:18px;flex-wrap:wrap}video{width:100%;background:#000}.raw{display:grid;grid-template-columns:1fr 1fr;gap:12px}table{border-collapse:collapse;width:100%}td,th{padding:8px;border-bottom:1px solid #374151;text-align:left}section{margin:32px 0}details{margin:12px 0}.notice{padding:12px;background:#23324a}@media(max-width:650px){.raw{grid-template-columns:1fr}}</style><h1>G2＋Wuji · 新刀连续取刀、单次推进和保持</h1><p class="notice">所有视频为完整22秒仿真，660帧，无剪切。真机未运行。通过是从主动推进前的滑块关节位置计算严格&gt;20 mm，并保持约1秒；不执行回收。</p><nav>'''+''.join('<a href="#'+r['name']+'">'+r['title']+'</a>' for r in records)+'''</nav><p>固定几何下，已验证可用被动容量下界由1.0 N提高至1.25 N；1.5 N仍失败。容量经过隔离夹具校准，不是实测机器人轴向总力。</p>'''+''.join(sections)+'''<h2>固定几何对照</h2><table><tr><th>运行</th><th>主动前移 mm</th><th>保持波动 mm</th><th>任务</th></tr>'''+table+'''</table><h2>必要泛化和硬件边界</h2><p>统一策略/初始估计适配：开发small/middle通过，large仍丢cap；三项新冻结联合条件near-large和shift-delay通过，near-small实际35 mm路径末端自碰撞证书拒绝执行。未覆盖所有尺寸组合。</p><p>A=仿真法向求解器读数；B=实际轴向总力缺测；C=校准容量和完整任务位移；D=关节负载/滑移/承托。硬件合成负载离线检查未超URDF力矩，thumb4达到位置边界；SDK驱动量A不是Nm。默认测力入口不运动，真实限位/固件/刚度/持续输出尚待实测。</p><p><a href="https://github.com/Jr-kelly/artgym/releases/tag/wuji-g2-singlepush-20261005-v1">GitHub Release</a> · <a href="https://github.com/Jr-kelly/artgym/tree/feat/wuji-singlepush-20261005/research/singlepush-20261005">报告、冻结配置和复现说明</a></p></html>'''
 (a.output/'report.html').write_text(page);zip_path=a.output.parent/'singlepush-video-report.zip'
 with zipfile.ZipFile(zip_path,'w',compression=zipfile.ZIP_STORED) as z:
  for f in a.output.iterdir():z.write(f,arcname=f.name)
 print(json.dumps(dict(report=str(a.output/'report.html'),bundle=str(zip_path),files=len(list(a.output.iterdir())),private_media=False)))
if __name__=='__main__':main()
