"""New uncut videos only; explicit task-pass vs safe deployment status."""
import argparse,json,hashlib,html,shutil,zipfile
from pathlib import Path
D=Path('research/contact-transfer-20261006')
p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);result=json.loads((D/'DELIVERY-RESULTS.json').read_text());records=[];sections=[]
for r in result['trials']:
 trial=Path(r['trial']);root=trial.parent;composites=list(root.glob('contact-transfer-*.mp4'));assert len(composites)==1,(root,composites);comp=composites[0];meta=json.loads(comp.with_suffix('.json').read_text());assert meta['uncut'] and meta['frames']==660 and meta['duration_s']==22
 copies=[(comp,r['name']+'-synchronized.mp4'),(trial/'continuous.mp4',r['name']+'-continuous.mp4'),(trial/'hand-closeup.mp4',r['name']+'-closeup.mp4')];videos={}
 for source,name in copies:shutil.copy2(source,a.output/name);videos[name]=hashlib.sha256((a.output/name).read_bytes()).hexdigest()
 e=r['evaluation'];notice='原始物理任务通过；真机未运行，输出几何／固件标定另列' if e['pass_all'] else '原始任务失败，保留完整过程'
 if r['name']=='near-small-prefix':notice='物理任务与实际姿态检查通过；预压目标凸包重叠不同于实际姿态，真机仍需固件／接触丢失响应标定'
 if r['name']=='large-normal-diagnostic':notice='32.4 mm与持续cap接触；滚转超标，而且路径需原始限速器处理跳变，仅作诊断'
 sections.append('<section id="'+r['name']+'"><h2>'+html.escape(r['label'])+'</h2><p class="notice">'+notice+'</p><p>主动前移 %.3f mm · 保持波动 %.3f mm · cap有效接触 %.2f%% · 刀体最大转动 %.3f rad</p>'%(e['active_forward_m']*1000,e['hold_range_m']*1000,e['effective_cap_contact_fraction']*100,e['body_max_rotation_rad'])+'<video controls preload="metadata" src="'+copies[0][1]+'"></video><details><summary>原始全景与近景：同时间、连续22秒、无剪切</summary><div class="raw">'+''.join('<video controls preload="metadata" src="'+name+'"></video>' for _,name in copies[1:])+'</div></details></section>')
 records.append(dict(name=r['name'],kind=r['kind'],label=r['label'],task_pass=e['pass_all'],hardware_ready=False,uncut=True,frames=660,fps=30,duration_s=22,source_trial=r['trial'],videos=videos,source_trace_sha256=e['trace_sha256'],actor_sha256=r['actor_sha256']))
page='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>G2＋Wuji 接触迁移交付 · 2026-10-06</title><style>body{margin:auto;padding:24px;max-width:1200px;background:#111827;color:#e5e7eb;font:17px/1.7 system-ui}a{color:#93c5fd}h1{font-size:30px}video{width:100%;background:#000}.raw{display:grid;grid-template-columns:1fr 1fr;gap:12px}section{margin:32px 0}.notice{padding:12px;background:#23324a}nav{display:flex;gap:16px;flex-wrap:wrap}@media(max-width:650px){.raw{grid-template-columns:1fr}}</style><h1>G2＋Wuji v1 · 具名映射、接触适配与迁移准备</h1><p class="notice">全部为本轮新录制的连续仿真；没有真实机器人视频。原1.25 N方案精确复现24.366 mm。新冻结中间尺寸＋1.25 N＋延迟／噪声22.123 mm通过；上沿尺寸＋变化阻力／摩擦3.488 mm失败。不声称连续范围全覆盖或测得最大轴向力。</p><p>已纠正SIM→SDK [4,0,1,3,2]具名转换；合成力矩采用惯性＋重力补偿−手上外力广义量，独立虚功校验通过。SDK1.8真实签名及只读适配入口已检查，未连接设备。</p><p>近小尺寸34 mm命令实际29.713 mm通过，实际姿态最小间隙11.78 mm；预压位置目标的凸包重叠不是实际相撞。严格限制这些抽象目标后14.557 mm失败，不能当作握姿能力上限。大尺寸着力点改动恢复cap接触，承托／滚转仍失败。没有改阈值追认成功。</p><nav>'''+''.join('<a href="#'+r['name']+'">'+html.escape(r['name'])+'</a>' for r in records)+'''</nav>'''+''.join(sections)+'''<p>A=法向求解器测量；B=轴向总接触力缺测；C=校准阻力容量与完整任务；D=实际有限力矩。真机effort为A驱动量，不是Nm。离线38.79%模型力矩上限比例不是硬件保证。仍须实机映射零位／限位、同握姿两方向持续测力、控制响应标定和可行承托路径。</p><p><a href="https://github.com/Jr-kelly/artgym/releases/tag/wuji-g2-contact-transfer-20261006-v1">GitHub Release</a> · <a href="https://github.com/Jr-kelly/artgym/tree/feat/wuji-contact-transfer-20261006/research/contact-transfer-20261006">源码、报告与复现</a></p></html>'''
(a.output/'report.html').write_text(page);(D/'VIDEO-MANIFEST.json').write_text(json.dumps(records,indent=2));bundle=a.output.parent/'contact-transfer-video-report.zip'
with zipfile.ZipFile(bundle,'w',compression=zipfile.ZIP_STORED) as z:
 for f in a.output.iterdir():z.write(f,arcname=f.name)
print(json.dumps(dict(report=str(a.output/'report.html'),bundle=str(bundle),new_full_videos=len(records)*3,private_media=False)))
