"""Saved-state diagnosis only; never online inputs or retuning labels."""
import argparse,json,numpy as np
from pathlib import Path
from scipy.spatial.transform import Rotation
from scripts.wuji_kinematics import WujiKinematics
p=argparse.ArgumentParser();p.add_argument('--trial',type=Path,required=True);p.add_argument('--operation',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();z=np.load(a.trial/'trace.npz');h=WujiKinematics();plan=json.loads((a.operation/'motor-plan.json').read_text());ref=json.loads((a.operation/'reference.json').read_text());rows=[];contacts=[json.loads(s) for s in (a.trial/'wrap-contact-physical-steps.jsonl').open()];params=json.loads(Path(json.loads((a.trial/'report.json').read_text())['physical_asset']).parent.joinpath('parameters.json').read_text());capwidth=params['slider_size'][0];pre=np.argmin(abs(z['time']-16));R0=Rotation.from_quat(z['object'][pre,3:7]);
for t in [15,15.8,16,16.5,17,17.5,18,19,20.1,21.5]:
 i=int(np.argmin(abs(z['time']-t)));q=z['q'][i];R=Rotation.from_quat(z['object'][i,3:7]);W=np.eye(4);W[:3,:3]=Rotation.from_quat(z['wrist'][i,3:7]).as_matrix();W[:3,3]=z['wrist'][i,:3];P=W@h.forward(q)['hand_r_thumb_pad_link'];normal=R.inv().apply(P[:3,0]);actual=[c for row in contacts if abs(row['time_s']-t)<.05 for c in row['contacts'] if 'thumb' in c['hand_link']];cap=[c for c in actual if c['knife_link']=='link_1'];fixed=[c for c in actual if c['knife_link']=='link_0'];points=np.array([c['position_knife_m'] for c in cap]);
 rows.append(dict(time_s=float(z['time'][i]),actual_slider_m=float(z['slider'][i]),body_rotation_from_push_start_rad=float((R0.inv()*R).magnitude()),thumb_normal_in_actual_knife=normal.tolist(),actual_front_cosine=float(-normal[1]),thumb_joint_margin_rad=np.minimum(q[16:]-h.lower[16:],h.upper[16:]-q[16:]).tolist(),cap_contact_rows=len(cap),cap_contact_point_mean_knife_m=points.mean(0).tolist() if len(cap) else None,cap_contact_edge_margin_x_min_m=float((capwidth/2-abs(points[:,0])).min()) if len(cap) else None,fixed_body_contact_rows=len(fixed),thumb_solver_normal_mean_N=float(np.mean([c['normal_magnitude_N'] for c in cap])) if cap else None))
a.output.write_text(json.dumps(dict(scope=__doc__,estimate=plan['initial_geometry_estimate'],estimated_initial_surface=ref['rows'][0].get('point_initial_estimate_m'),estimated_first_front_cosine=ref['rows'][0].get('authored_front_cosine'),estimated_last_front_cosine=ref['rows'][-1].get('authored_front_cosine'),rows=rows),indent=2))
print(json.dumps(rows))
