"""Independent predeclared extension-only evaluation; never controller input."""
import argparse,hashlib,json,xml.etree.ElementTree as ET
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
def evaluate(trial):
 z=np.load(trial/'trace.npz');t=z['time'];q=z['slider'];r=json.loads((trial/'report.json').read_text());c=json.loads(Path('research/singlepush-20261005/TASK-CRITERION-v1.json').read_text());start=c['push_start_s'];end=c['run_duration_s'];op=t>=start;hold=(t>c['hold_window_s'][0])&(t<=end+.001);pre=(t>start-.3)&(t<=start+.001);q0=float(np.median(q[pre]));active=q-q0;body=z['object'];origin=body[np.flatnonzero(pre)[-1]];drift=np.linalg.norm(body[op,:3]-origin[:3],axis=-1);rot=(Rotation.from_quat(origin[3:7]).inv()*Rotation.from_quat(body[op,3:7])).magnitude();asset=Path(r['physical_asset']);params=json.loads((asset.parent/'parameters.json').read_text());lim=ET.parse(asset).find('./joint/limit');effective=[];normal=[];rail=[]
 for line in (trial/'wrap-contact-physical-steps.jsonl').open():
  row=json.loads(line)
  if row['time_s']<start:continue
  cap=[x for x in row['contacts'] if 'thumb' in x['hand_link'] and x['knife_link']=='link_1' and x['position_knife_m'][1]>=params['handle_size'][1]/2-.0002 and abs(x['position_knife_m'][0])<=params['slider_size'][0]/2+.0002 and x['normal_magnitude_N']>1e-6];effective.append(bool(cap));normal.append(sum(x['normal_magnitude_N'] for x in cap));rail.append(sum(x['normal_magnitude_N'] for x in row['contacts'] if 'thumb' in x['hand_link'] and x['knife_link']=='link_0'))
 loss=longest=0
 for v in effective:loss=0 if v else loss+1;longest=max(longest,loss)
 hq=z['q'];p=json.loads((trial/'physics.json').read_text());hand=p['hand_indices'];eff=np.array(p['effort'])[hand];tau=z['torque'][op][:,hand];thumb=np.abs(tau[:,16:])/eff[16:]
 checks=dict(continuous_pickup=bool(r['lifted_clear'] and not r.get('held_diagnostic',False)),complete_duration=bool(t[-1]>=end-.01),active_forward=bool(np.median(active[hold])>c['active_displacement_strictly_greater_m']),hold_above_threshold=bool(active[hold].min()>c['hold_min_active_displacement_strictly_greater_m']),hold_stable=bool(np.ptp(q[hold])<=c['hold_range_max_m']),clear=bool(np.min(body[op,2])>r['table_height']+.03 if 'table_height' in r else np.min(body[op,2])>.78),body_supported=bool(drift.max()<=c['body_translation_envelope_m'] and rot.max()<=c['body_rotation_envelope_rad']),effective_cap_contact=bool(np.mean(effective)>=.9 and longest/240<=.5),no_endstop=bool(np.min(q[op]-float(lim.get('lower')))>.002 and np.min(float(lim.get('upper'))-q[op])>.002),extension_only_schedule=bool(r['extension_only']))
 result=dict(version=c['version'],checks=checks,pass_all=all(checks.values()),active_forward_m=float(np.median(active[hold])),prepush_slider_m=q0,relative_episode_initial_extension_m=float(np.median(q[hold])-r['initial_slider_q_m']),hold_range_m=float(np.ptp(q[hold])),hold_min_active_m=float(active[hold].min()),effective_cap_contact_fraction=float(np.mean(effective)),longest_cap_contact_loss_s=longest/240,body_max_translation_m=float(drift.max()),body_max_rotation_rad=float(rot.max()),cap_normal_mean_N=float(np.mean(normal)),cap_normal_p05_N=float(np.percentile(normal,5)),cap_normal_peak_N=float(np.max(normal)),fixed_body_normal_mean_N=float(np.mean(rail)),actual_total_axial_contact_force_N=None,brake_capacity_min_N=float(z['solver_brake_capacity_N'][op].min()),brake_capacity_max_N=float(z['solver_brake_capacity_N'][op].max()),thumb_torque_limit_fraction_max=thumb.max(axis=0).tolist(),thumb_torque_limit_fraction_p95=np.percentile(thumb,95,axis=0).tolist(),thumb_limit_saturation_fraction=(thumb>.99).mean(axis=0).tolist(),trace_sha256=hashlib.sha256((trial/'trace.npz').read_bytes()).hexdigest(),scope='Original continuous physical task, extension-only. A=normal solver measurement, B=axial total missing, C=brake model and demonstrated task, D=clipped simulation torque. No hardware force claim.')
 (trial/'extension-evaluation.json').write_text(json.dumps(result,indent=2));return result
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--trial',type=Path,required=True);a=p.parse_args();print(json.dumps(evaluate(a.trial)))
