"""Fixed acquired wrist/index/thumb support; middle establishes a real side-rail before thumb release."""
import json,numpy as np,time
from pathlib import Path
from scipy.optimize import least_squares
from scripts.g2_contact_geometry import DigitGeometry
from scripts.g2_kinematics import transform
out=Path('runs/flat-table-20261006/preparation/acquired-middle-link4-v107');out.mkdir();sp=out/'asset-spec.json';sp.write_text(json.dumps(dict(asset_urdf='assets/objects/knife_wuji_newknife_20261005/nominal-v5/mobility.urdf',file_sha256={})));g=DigitGeometry(max_face_axes=12,knife_spec=sp);z=np.load('runs/flat-table-20261006/development/clamped-extraction-v104/simulation/trace.npz');i=np.argmin(abs(z['time']+1));O=transform(z['object'][i,:3],z['object'][i,3:7]);W=transform(z['wrist'][i,:3],z['wrist'][i,3:7]);L=np.linalg.inv(O)@W;q=z['q'][i].astype(float);issued=z['applied_target'][i][-20:].astype(float);n='hand_r_middle_link4';V=np.concatenate([v for v,_ in g.meshes[n]]);F=g.w.forward(q);T=L@F[n];P=V@T[:3,:3].T+T[:3,3];N=np.array([0,-1,0]);pr=P@N;weights=np.exp(-(pr-pr.min())/.0003);m=weights@V/weights.sum();ln=T[:3,:3].T@N;x0=np.r_[q[4:8],-.045,0.];lo=np.r_[g.w.lower[4:8]+.006,-.070,-.0085];hi=np.r_[g.w.upper[4:8]-.006,.070,.0085]
def res(x):
 qq=q.copy();qq[4:8]=x[:4];T=L@g.w.forward(qq)[n];target=np.array([x[5],-.0044,x[4]]);r=list((T[:3,:3]@m+T[:3,3]-target)*180);r.extend((T[:3,:3]@ln-N)*1)
 r.extend(min(0,s['gap_lower_bound_m']-.0002)*80 for s in g.gaps(qq,L,0.,'middle') if s['hand_link']!=n);r.extend(min(0,s['gap_lower_bound_m']-.0001)*80 for s in g.self_gaps(qq,'middle',certify_clearance_m=.0001));r.extend((x-x0)*.003);return np.array(r)
b=time.time();f=least_squares(res,np.clip(x0,lo+1e-6,hi-1e-6),bounds=(lo,hi),max_nfev=100);qq=q.copy();qq[4:8]=f.x[:4];T=L@g.w.forward(qq)[n];point=T[:3,:3]@m+T[:3,3];r=dict(middle_q=qq[4:8].tolist(),target=[float(f.x[5]),-.0044,float(f.x[4])],point=point.tolist(),contact_error_m=float(np.linalg.norm(point-np.array([f.x[5],-.0044,f.x[4]]))),normal_error=float(np.linalg.norm(T[:3,:3]@ln-N)),material_point=m.tolist(),local_normal=ln.tolist(),wrist_in_knife=L.tolist(),object_world=O.tolist(),arm_q=z['arm_q'][i].tolist(),measured_hand_q=q.tolist(),issued_hand_q=issued.tolist(),scope=__doc__,elapsed_s=time.time()-b);(out/'candidate.json').write_text(json.dumps(r,indent=2));print(json.dumps({k:r[k] for k in ['target','point','contact_error_m','normal_error','elapsed_s']}),flush=True)
