"""Ideal entry diagnostic for the new pivot geometry; never reached-entry proof."""
import json,hashlib,argparse,shutil,subprocess,sys
from pathlib import Path
import isaacgym
import numpy as np
from scripts.wuji_cap_contact_pivot import CapContactPivot
from scripts.g2_kinematics import transform
from scripts.wuji_goal_common import configuration
from scripts.record_wuji_flat_table_event import record

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);source=Path('runs/flat-table-20261006/learning/fresh-operating-contact-functional-v853/actual_all_envs_round_061');z=np.load(source/'actual-regrasp-traces.npz');q=z['dof'][344,15,:27,0].astype(float);issued=z['issued'][344,15].astype(float);o=z['object'][344,15].astype(float);slider=float(z['dof'][344,15,27,0]);geometry=Path('runs/flat-table-20261006/direct/preparation/minimal-cap-pivot-null-preflight-v859r1/result.json');final=np.array(json.loads(geometry.read_text())['rows'][-1]['q']);O=transform(o[:3],o[3:7]);cfg=configuration('wuji_geometry',1,['object=knife_wuji_real_size_20261002','hand=wuji_paper_official_actuator','+task.env.geometryRound=real-size-student-adaptation-20261002'],train='wujiAcquisitionSAPG',seed=2026100301);pivot=CapContactPivot(cfg,dict(start_s=0.,end_s=6.,angle_deg=20.,thumb_joint3_reserve_rad=.15),a.output);pivot.command(0.,O,q,issued,slider);X=np.linalg.inv(O)@pivot.f.kin.forward(final[:7]);J=pivot.jacobian(final[7:],X);motor=issued.copy();motor[:7]=final[:7]+issued[:7]-q[:7];motor[23:]=final[23:]+np.clip(J.T@pivot.capture['force']/pivot.kp,-.2,.2);motor=np.clip(motor,np.r_[pivot.f.kin.lower,pivot.g.w.lower],np.r_[pivot.f.kin.upper,pivot.g.w.upper]);o[7:]=0;ideal=a.output/'ideal-initialization';ideal.mkdir();np.savez_compressed(ideal/'takeover.npz',object_state=o,robot_q=final,estimated_robot_velocity=np.zeros(27),slider_q=slider,slider_velocity=0.,issued_target=motor,issued_target_history=motor[None],elapsed_history_s=np.array([0.]));manifest=dict(initializer_category='ideal-diagnostic',source_actual_geometry=str(source),geometry=str(geometry),source_env=15,source_frame=344,scope='Ideal INITIALwholewrist20degreepivot andthumbnullpose; otherdigits/knife fromactualfresh6115. Velocitieszero, no cache/historyrestore. Capturedjointdeflectionwrenchproxy transported toendgeometry, notconstantforce. DoesNOT demonstratephysicalregrasp/reachedentry/fulltablegoal.');(ideal/'manifest.json').write_text(json.dumps(manifest,indent=2));support=dict(required_actual_source=str(ideal),rows=[dict(time_s=0.,arm_q=motor[:7].tolist(),hand_q=motor[7:].tolist())],development_abort_on_translation_m=.1,retained_push_skill=dict(start_s=0.,preparation_seconds=4.,knife_spec='assets/objects/knife_wuji_newknife_20261005/nominal-v5/spec.json',entry_reference_adaptation='measured-hold',task_stroke_m=.03,entry_pressure_coordinates='cartesian-normal'),scope=manifest['scope']);(a.output/'motor.json').write_text(json.dumps(support,indent=2));cmd=json.loads(Path('runs/flat-table-20261006/direct/development/ideal-tail-30mm-fullB-v773/command.json').read_text());cmd[0]=sys.executable
 for flag,value in [('--recorded-handoff',str(ideal)),('--recorded-support-command',str(a.output/'motor.json')),('--output',str(a.output/'simulation'))]:cmd[cmd.index(flag)+1]=value
 (a.output/'command.json').write_text(json.dumps(cmd,indent=2));runtime=a.output/'controller-source';runtime.mkdir()
 for name in ['prepare_wuji_ideal_cap_pivot_capacity.py','run_g2_flat_table_demo.py','wuji_cap_contact_pivot.py','wuji_retained_push_skill.py','wuji_measured_hold_reference.py']:shutil.copyfile(Path('scripts')/name,runtime/name)
 record('ideal_cap_pivot_original_fullB_capacity_started_v863',[str(a.output/'command.json'),str(ideal/'manifest.json')],dict(question='Doesnewcap-pivot geometry actuallycarryandaccept originalcompleteB>20mm? Yes: developphysicaltransfer; no: rejectnewgoal/stopgoal-directedtraining.',source_sha256=hashlib.sha256((source/'policy-before-update.pth').read_bytes()).hexdigest(),initializer=manifest,thumb_motor=motor[23:].tolist(),captured_wrench_proxy=pivot.capture['force'].tolist()),updates={'add_active_jobs':[str(a.output)]},next_step='Actual4spressureprep+complete180Bcalls andabsolute>20/1s/H decide; idealentry isnotcontinuousgoal')
 try:subprocess.run(cmd,check=True)
 finally:record('ideal_cap_pivot_original_fullB_capacity_terminal_v863',[str(a.output/'simulation')],updates={'remove_active_jobs':[str(a.output)]},next_step='Read actualcapacity/earliestfailure; rejectunprovennewgoalifB orloadfails')
if __name__=='__main__':main()
