"""Freeze deployable initial geometry and commands, never simulator state."""
import json,hashlib
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
R=Path(__file__).resolve().parents[1];D=R/'research/rear-sim2real-20261009'
def pose(v):
    t=np.eye(4);t[:3,:3]=Rotation.from_quat(v[3:7]).as_matrix();t[:3,3]=v[:3];return t
p=R/'runs/contact-transfer-20261006/regression/nominal-125-video-v1/simulation'
t=np.load(p/'trace.npz');i=np.argmin(abs(t['time']-15.7));physics=json.loads((p/'physics.json').read_text());names=physics['robot_dof_names'];hand=physics['hand_indices'];arm=physics['arm_indices'];w=pose(t['wrist'][i]);o=pose(t['object'][i]);hold=t['target'][i,hand]
# The start is empty, with a physically separate, temporary support for placement.
opened=t['q'][i].copy();opened[[2,6,10,14,18]]-=.20;opened[16]-=.1
from scripts.wuji_kinematics import WujiKinematics
h=WujiKinematics();opened=np.clip(opened,h.lower+.015,h.upper-.015)
ref=json.loads((R/'runs/newknife-20261005/preparation/center-tail-support-v2/reference.json').read_text());ref.update(json.loads((R/'runs/singlepush-20261005/configs/reference-path-drive.json').read_text()));(D/'reference.json').write_text(json.dumps(ref,indent=2))
regrasp=json.loads((R/'runs/newknife-20261005/preparation/center-tail-support-v2/postlift-transfer.json').read_text());plan=json.loads((R/'runs/newknife-20261005/preparation/capfront-v2/motor-plan.json').read_text());initial_est=plan['initial_geometry_estimate'];rel=np.asarray(regrasp['object_in_wrist']);srel=np.asarray(regrasp['slider_in_wrist']);delta=np.asarray(initial_est['slider_contact_shift_m'])+np.array([0,(initial_est['handle_size_WTL_m'][1]-.012)/2,0]);delta[1]-=(initial_est['slider_size_WTL_m'][1]-.003)/2;srel[:3,3]+=rel[:3,:3]@delta
spec=dict(format='wuji-rear-bundle-v1',control_hz=30,history_frames=50,issued_limit_reserve_rad=.015,stroke_m=.035,prepare_seconds=3.,release_seconds=3.,settle_seconds=2.,push_seconds=6.,reference='research/rear-sim2real-20261009/reference.json',pressure='runs/newknife-20261005/configs/pressure120.json',teacher='runs/artmanip-recovery-20260930/aggregation1-pair6400/aggregate/E/epoch_006100.pth',student='runs/real-size-student-adaptation-20261002/train/R800/step_055200.pth',residual='runs/newknife-20261005/train/center-tail-constant-motor-v1/update_000100.pth',asset='assets/objects/knife_wuji_newknife_20261005/nominal-v5/mobility.urdf',resistance='runs/singlepush-20261005/configs/resistance-0.73549875.json',runtime_joint_names=h.names,model_lower_rad=h.lower.tolist(),model_upper_rad=h.upper.tolist(),open_q_rad=opened.tolist(),hold_target_rad=hold.tolist(),arm_q_rad=t['target'][i,arm].tolist(),wrist_world=w.tolist(),placement_object_in_wrist=(np.linalg.inv(w)@o).tolist(),object_initial_estimate=rel.tolist(),slider_initial_estimate=srel.tolist(),geometry_estimate=initial_est['handle_size_WTL_m']+initial_est['slider_size_WTL_m'],placement_slider_q_m=float(t['slider'][i]),initialization_scope='Selected contact geometry from prior measured pose; NO saved velocities, targets/history/RNN/contact caches restored. Empty hand approaches, explicit manual-placement support withdrawn; free gravity settling and fifty new encoder frames.',firmware_axes_zeros_verified=False,real_robot_ran=False)
paths=[spec[k] for k in ['teacher','student','residual','reference','pressure','asset','resistance']]+['scripts/g2_r800_policy.py','scripts/wuji_joint_deflection_pressure.py','scripts/wuji_scheduled_thumb_reference.py','scripts/wuji_known_controller.py','scripts/g2_frozen_policy.py','scripts/wuji_student_interface.py','scripts/wuji_bounded_motor_residual.py','assets/hands/wuji_artbot/hand_config.yaml','isaacgymenvs/cfg/hand/wuji_paper_official_actuator.yaml','isaacgymenvs/cfg/task/wuji_geometry.yaml','isaacgymenvs/cfg/train/wujiAcquisitionSAPG.yaml','caches/initial_grasp/wuji/knife_wuji_demo_aligned/000/train/valid_grasps.npy',str((p/'trace.npz').relative_to(R))]
spec['required_sha256']={x:hashlib.sha256((R/x).read_bytes()).hexdigest() for x in paths};(D/'bundle.json').write_text(json.dumps(spec,indent=2));print('Frozen bundle, actual history is not part of initialization')
