"""One fresh actual table pickup, held flip, new bearing, then complete original B.

The new-bearing saved state is a read-only motor prior. Stage adapts to this
same episode's issued targets; there are no stage state/history assignments.
Original B and30mm reference are retained; capacity requires actual displacement.
"""
import argparse,json,hashlib,shutil,subprocess,sys
from pathlib import Path
from scripts.record_wuji_flat_table_event import record

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);base=Path('runs/flat-table-20261006/direct/development/balanced-pad-fresh-free-wrist-widthflip-v877');prefix=json.loads((base/'prefix.json').read_text());bearing=Path('runs/flat-table-20261006/direct/preparation/actual-static-primary-two-idle-bearing-motor-v924/motor.json');motor=json.loads(bearing.read_text());source=Path(motor['required_actual_source']);seconds=motor['rows'][-1]['time_s'];stage=dict(name='retained_primary_pinky_back_bearing',duration_s=seconds,source=str(source),motor=str(bearing),fixed_acquired_motor_reference=True,scope='Onlyreadmotorprior; actualepisode wrist andoriginalprimary issuedtargets retained, idleRing/Pinky coupledpath, no stage setters');prefix['direct_pickup']['continuous_stages'].append(stage);prefix['duration_s']+=seconds;start=prefix['duration_s'];prefix['retained_push_skill']=dict(start_s=start,preparation_seconds=4.,task_stroke_m=.03,knife_spec='assets/objects/knife_wuji_newknife_20261005/nominal-v5/spec.json',entry_reference_adaptation='measured-hold',entry_pressure_coordinates='cartesian-normal');prefix['development_abort_min_knife_height']=dict(after_elapsed_s=12.,minimum_whole_clearance_m=.002);prefix['scope']=__doc__;prefix['goal8_status']='Full original B sameepisode capacity attempt; success requiresactual>20mm+1s andallactualH';(a.output/'prefix.json').write_text(json.dumps(prefix,indent=2));cmd=json.loads((base/'command.json').read_text());cmd[0]=sys.executable
 for flag,value in [('--flat-table-prefix',str(a.output/'prefix.json')),('--output',str(a.output/'simulation')),('--seconds','11.1'),('--task-stroke-m','.03')]:cmd[cmd.index(flag)+1]=value
 (a.output/'command.json').write_text(json.dumps(cmd,indent=2));runtime=a.output/'controller-source';runtime.mkdir();hashes={}
 for name in ['run_wuji_fresh_static_primary_bearing.py','run_g2_flat_table_demo.py','wuji_direct_route.py','wuji_direct_pickup.py','wuji_whole_grip_gravity_transport.py','wuji_retained_push_skill.py','g2_r800_policy.py','wuji_measured_hold_reference.py','wuji_joint_deflection_pressure.py','wuji_pose_motion.py','wuji_functional_entry_affordance.py']:
  s=Path('scripts')/name;shutil.copyfile(s,runtime/name);hashes[name]=hashlib.sha256(s.read_bytes()).hexdigest()
 (runtime/'manifest.json').write_text(json.dumps(dict(sha256=hashes,motor_sha256=hashlib.sha256(bearing.read_bytes()).hexdigest(),scope='Exact executed source snapshot; prior only reads for motoradaptation; allphysicsfresh table, no stage setters'),indent=2));record('fresh_static_primary_new_bearing_full_originalB_started_v926',[str(a.output/'command.json'),str(a.output/'prefix.json'),str(runtime/'manifest.json')],dict(scope=__doc__,originalB_start_s=start,complete_B_preparation_s=4.,reference_request_m=.03,B_after_preparation_s=7.1,initialization='One freshflat table, originalasset/mass/actuators/frictions/gravity/brake; no restore',prior_science='Actual925312frames H0, continuousPinkyLink4 backnormal+.062N last1s, primarystillheld; not independentPinkyloadcapacity'),updates=dict(add_active_jobs=[str(a.output)]),next_step='Verify samefreshA+flip+Pinky actualcontacts/H ->fulloriginalB displacement and1shold; failure identifies remainingentry, no restart orfullgraspsearch')
 try:subprocess.run(cmd,check=True)
 finally:record('fresh_static_primary_new_bearing_full_originalB_terminal_v926',[str(a.output/'simulation')],updates=dict(remove_active_jobs=[str(a.output)]),next_step='Inspect actualsameepisode firstfailure ororiginalB>20/1s,H; ifBentryfailed developshortinhand fromnewback-bearing actualstate, no repeatwholefront untilimprovement')
if __name__=='__main__':main()
