"""Actual continuous pickup, one forward command, then clock-based hold."""
import argparse,hashlib,json,subprocess,sys
from pathlib import Path
def main():
 p=argparse.ArgumentParser();p.add_argument('--target-clearance-spec',type=Path);p.add_argument('--clearance-guard-version',choices=['full-v1','reduced-dev'],default='full-v1');p.add_argument('--output',type=Path,required=True);p.add_argument('--prepared',type=Path,default=Path('runs/newknife-20261005/preparation/capfront-v2'));p.add_argument('--operation-prepared',type=Path,default=Path('runs/newknife-20261005/preparation/center-tail-support-v2'));p.add_argument('--asset',type=Path,default=Path('assets/objects/knife_wuji_newknife_20261005/nominal-v5/mobility.urdf'));p.add_argument('--resistance',type=Path,default=Path('research/newknife-20261005/resistance-constant.json'));p.add_argument('--pressure',type=Path,default=Path('runs/newknife-20261005/configs/pressure120.json'));p.add_argument('--stroke-m',type=float,default=.035);p.add_argument('--checkpoint',type=Path,default=Path('runs/newknife-20261005/train/center-tail-constant-motor-v1/update_000100.pth'));p.add_argument('--reference-control-config',type=Path,help='Override only declared reference feedback parameters; immutable certified geometric rows');p.add_argument('--adaptive-hold',action='store_true',help='Keep joint-feedback tracking and pressure updates active after the forward ramp; goal stays forward');p.add_argument('--no-video',action='store_true');a,extra=p.parse_known_args();assert not a.output.exists();a.output.mkdir(parents=True)
 assert json.loads((a.prepared/'closure-audit.json').read_text()).get('passed',False)
 assert json.loads((a.prepared/'full-stroke-audit.json').read_text())['all_passed'];audit=json.loads((a.operation_prepared/'actual-transfer-stroke-audit.json').read_text());transfer=json.loads((a.operation_prepared/'postlift-transfer.json').read_text());assert audit['all_passed'] and not audit['rate_limit_required'] and transfer['preflight_passed'];assert audit['reference_sha256']==hashlib.sha256((a.operation_prepared/'reference.json').read_bytes()).hexdigest();assert max(r['max_active_point_error_m'] for r in transfer['contact_point_tracking'])<.001
 c=json.loads(Path('research/highload-20261005/FROZEN-ENGINEERING-CANDIDATE.json').read_text())['command'][3:]
 def setarg(flag,value):c[c.index(flag)+1]=str(value)
 for flag,v in [('--grasp-plan',a.prepared/'motor-plan.json'),('--table-calibration',a.prepared/'localization.json'),('--acquisition-path',a.prepared/'acquisition/acquisition-path.json'),('--thumb-reference-override',a.operation_prepared/'reference.json'),('--proprioceptive-pressure-config',a.pressure),('--residual-checkpoint',a.checkpoint),('--seconds',22),('--load',0),('--detent',0),('--output',a.output/'simulation')]:setarg(flag,v)
 for flag in ['--handover-calibration','--thumb-residual-scale-override']:
  i=c.index(flag);del c[i:i+2]
 loc=json.loads((a.prepared/'localization.json').read_text());c[c.index('--dx=-.1965')]='--dx='+str(loc['object_world_matrix'][0][3]-.5)
 if a.no_video:c.remove('--video')
 if a.reference_control_config:
  control=json.loads(a.reference_control_config.read_text());assert set(control)<= {'tangent_tracking','joint_lag_pacing','travel_seconds'}
  ref=json.loads((a.operation_prepared/'reference.json').read_text());ref.update(control);derived=a.output/'reference-control.json';derived.write_text(json.dumps(ref,indent=2));setarg('--thumb-reference-override',derived)
 c+=['--postlift-regrasp',str(a.operation_prepared/'postlift-transfer.json'),'--knife-asset',str(a.asset),'--newknife-resistance',str(a.resistance),'--task-stroke-m',str(a.stroke_m),'--extension-only']+([] if a.adaptive_hold else ['--scheduled-target-holds'])+extra
 if a.target_clearance_spec:c+=['--target-clearance-spec',str(a.target_clearance_spec),'--clearance-guard-version',a.clearance_guard_version]
 cmd=[sys.executable,'-m','scripts.run_g2_contact_transfer_demo' if a.target_clearance_spec else 'scripts.run_g2_flat_table_demo']+c;(a.output/'command.json').write_text(json.dumps(cmd,indent=2));files=[Path('scripts/run_wuji_flat_table.py'),Path('scripts/run_g2_flat_table_demo.py'),Path('scripts/wuji_flat_pose_adapter.py'),Path('scripts/run_wuji_contact_transfer.py'),Path('scripts/run_wuji_contact_transfer_selected.py'),Path('scripts/select_wuji_feasible_prefix.py'),Path('scripts/run_g2_robust_demo.py'),Path('scripts/run_wuji_singlepush.py'),Path('scripts/evaluate_wuji_singlepush.py'),Path('scripts/g2_r800_policy.py'),Path('scripts/wuji_joint_deflection_pressure.py'),a.checkpoint,a.pressure,a.asset,a.resistance,a.operation_prepared/'reference.json',a.operation_prepared/'postlift-transfer.json']+([a.reference_control_config] if a.reference_control_config else []);(a.output/'source-hashes.json').write_text(json.dumps({str(x):hashlib.sha256(x.read_bytes()).hexdigest() for x in files},indent=2))
 if '--partial-tail-regrasp' in extra:files.append(Path(extra[extra.index('--partial-tail-regrasp')+1]))
 if '--flat-table-prefix' in extra:
  files.append(Path(extra[extra.index('--flat-table-prefix')+1]));(a.output/'source-hashes.json').write_text(json.dumps({str(x):hashlib.sha256(x.read_bytes()).hexdigest() for x in files},indent=2))
 if a.target_clearance_spec:files+=[Path('scripts/run_g2_contact_transfer_demo.py'),Path('scripts/wuji_target_clearance_guard_v1.py'),a.target_clearance_spec];(a.output/'guard-source-hashes.json').write_text(json.dumps({str(x):hashlib.sha256(x.read_bytes()).hexdigest() for x in files},indent=2))
 subprocess.run(cmd,check=True);subprocess.run([sys.executable,'-m','scripts.evaluate_wuji_singlepush','--trial',str(a.output/'simulation')],check=True);subprocess.run([sys.executable,'-m','scripts.evaluate_wuji_flat_table','--trial',str(a.output/'simulation')],check=True)
if __name__=='__main__':main()
