"""One fresh table episode: partial held flip, true Pinky backing, conversion, full B.

Recorded states are read-only motor priors. The current episode supplies all
physical states and motor/controller history. Frozen sampled transition is a
development script/NN candidate, not a validated general policy. Original full
B uses its exact weights/modules and consistent30mm request; acceptance requires
actual>20mm plus~1s hold and original H. No stage physical setters or caches.
"""
import argparse,json,hashlib,shutil,subprocess,sys
from pathlib import Path
from scripts.record_wuji_flat_table_event import record

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);base=Path('runs/flat-table-20261006/direct/development/balanced-pad-fresh-free-wrist-widthflip-v877');prefix=json.loads((base/'prefix.json').read_text());prefix['direct_pickup']['continuous_stages'][1]['duration_s']=6.;bearing=Path('runs/flat-table-20261006/direct/preparation/partial-flip-cached-back-bearing-v975/motor.json');motion=json.loads(bearing.read_text());source=Path(motion['required_actual_source']);bearing_s=float(motion['rows'][-1]['time_s']);prefix['direct_pickup']['continuous_stages'].append(dict(name='actual_partial_flip_Pinky_back_PAD_bearing',duration_s=bearing_s,source=str(source),motor=str(bearing),fixed_acquired_motor_reference=True,scope='Actualepisode motors only; prior974 is never physically assigned'));start=18.+bearing_s;candidate=Path('runs/flat-table-20261006/direct/preparation/true-Pinky-sampled-frozen-candidate-v988');frozen=json.loads((candidate/'motor.json').read_text())['regrasp_policy'];length=float(frozen['end_s']);prefix['regrasp_policy']=dict(frozen,start_s=start,end_s=start+length);prefix['duration_s']=start+length+1.5;prefix['retained_push_skill']=dict(start_s=prefix['duration_s'],preparation_seconds=4.,task_stroke_m=.03,knife_spec='assets/objects/knife_wuji_newknife_20261005/nominal-v5/spec.json',entry_reference_adaptation='measured-hold',entry_pressure_coordinates='cartesian-normal');prefix['development_abort_min_knife_height']=dict(after_elapsed_s=12.,minimum_whole_clearance_m=.002);prefix['scope']=__doc__;prefix['goal8_status']='Samefresh continuous capacityattempt; failedentry may reject beforeBactor, no prerequisite successassumed';path=a.output/'prefix.json';path.write_text(json.dumps(prefix,indent=2));cmd=json.loads((base/'command.json').read_text());cmd[0]=sys.executable
 for flag,value in[('--flat-table-prefix',str(path)),('--output',str(a.output/'simulation')),('--seconds','11.1'),('--task-stroke-m','.03')]:cmd[cmd.index(flag)+1]=value
 (a.output/'command.json').write_text(json.dumps(cmd,indent=2));runtime=a.output/'controller-source';runtime.mkdir();hashes={}
 for name in['run_wuji_fresh_partial_backed_conversion.py','run_g2_flat_table_demo.py','wuji_direct_route.py','wuji_direct_pickup.py','wuji_whole_grip_gravity_transport.py','wuji_regrasp_reference_policy.py','train_wuji_regrasp.py','wuji_retained_push_skill.py','g2_r800_policy.py','wuji_measured_hold_reference.py','wuji_joint_deflection_pressure.py','wuji_functional_entry_affordance.py','wuji_regrasp_contract.py']:
  src=Path('scripts')/name;shutil.copyfile(src,runtime/name);hashes[name]=hashlib.sha256(src.read_bytes()).hexdigest()
 for key in['checkpoint','action_noise']:hashes[key]=hashlib.sha256(Path(frozen[key]).read_bytes()).hexdigest()
 (runtime/'manifest.json').write_text(json.dumps(dict(source_sha256=hashes,new_bearing_motor_sha256=hashlib.sha256(bearing.read_bytes()).hexdigest(),scope=__doc__),indent=2));record('fresh_partial_backed_conversion_full_originalB_started_v990',[str(a.output/'command.json'),str(path),str(runtime/'manifest.json')],dict(scope=__doc__,NN_start_s=start,NN_s=length,live_hold_s=1.5,B_start_s=prefix['duration_s'],B_preparation_s=4.,B_request_m=.03,front_baseline='868 actualnewPADpickup/877 heldflip retained',back_baseline='773 fullB standalone21.6mm retained',latest_short_evidence='989 all124H0/nativePinky+.145N all248physicalsteps last1s; relative15goal error14.855->min5.681/last1smax8.939, Thumbstillbodybackside, actualcap/fullgoalunvalidated'),updates=dict(add_active_jobs=[str(a.output)]),next_step='Actualsamefresh episode contacts/H ->originalcompleteB active displacement/hold; firstfailure/entry evidence choosesnextshortaction, nofullprefix repeatswithoutnewimprovement')
 try:subprocess.run(cmd,check=True)
 finally:record('fresh_partial_backed_conversion_full_originalB_terminal_v990',[str(a.output/'simulation')],updates=dict(remove_active_jobs=[str(a.output)]),next_step='Assess samefreshA/partialflip/backbearing/NN originalB; continueentrybottleneck fromactualsafe state, no stopatcheckpoint/report')
if __name__=='__main__':main()
