"""Finite actual loaded release coordination, physical flat placement and hand exit."""
from scripts.wuji_table_transfer_learning_env import TableTransferLearning
import json,numpy as np,torch,shutil
from pathlib import Path
from scipy.spatial.transform import Rotation
from scripts.record_wuji_flat_table_event import record
base=Path('runs/flat-table-20261006');out=base/'learning/mid-release-physical-v14';out.mkdir();data=out/'data';data.mkdir();old=base/'learning/b-compatible-transport-20261006/data';scene=json.load(open(old/'scene.json'));scene['learning_asset_directory']='assets/objects/knife_wuji_contact_transfer_20261006/frozen-v1/mid-high-delay';scene['newknife_resistance']['reference_N']=1.25;(data/'scene.json').write_text(json.dumps(scene));shutil.copy2(old/'prefix.npz',data/'prefix.npz');shutil.copy2(base/'recorded-mid-inset-23p9s/takeover.npz',data/'takeover.npz');s=np.load(data/'takeover.npz');q=s['issued_target'];path=np.tile(q,(150,1));np.savez_compressed(data/'learn-path.npz',targets=path)
e=TableTransferLearning(n=48,seed=610614,data=str(data));rng=np.random.default_rng(610614);normal=json.load(open(base/'preparation/mid-actual-normal-release-v10/support.json'))['rows'];last=np.r_[normal[-1]['arm_q'],normal[-1]['hand_q']];delta=last-q;parameters=rng.normal(0,.18,(48,20));parameters[0]=0;armparams=rng.normal(0,.04,(48,7));armparams[0]=0;best=None;records=[]
record('mid_actual_release_physical_batch_started',[str(data/'takeover.npz')],dict(uncertainty='Coordinated finite wrist/finger unload retains flatknife while allhandcontacts separate?',decision='Nativebest ifflatandhandfree; otherwise differentmaterialexitmechanism',episodes=48,seconds=5,scope='Actualrecordedloadedmidstate; nofullflowclaim'),updates=dict(active_jobs=['mid-release-physical-v14']),next_step='Read directphysicalflat/contact objective notjointdistance')
try:
 for i in range(150):
  u=np.clip(i/90,0,1);u=u*u*(3-2*u);motor=np.tile(q,(48,1));motor+=delta*u;motor[:,7:]+=parameters*u;motor[:,:7]+=armparams*u;e.servo(e.tensor(motor));records.append(dict(object=e.rb[:,e.object_index].cpu().numpy().copy(),target=e.command_target.cpu().numpy().copy(),q=e.dof[:,:27,0].cpu().numpy().copy()))
 obj=e.rb[:,e.object_index].cpu().numpy();rot=Rotation.from_quat(obj[:,3:7]).as_matrix();flat=np.abs(rot[:,2,1]);contact=e.contact[:,:e.object_index].norm(dim=-1).amax(-1).cpu().numpy();pos=np.linalg.norm(obj[:,:3]-s['object_state'][:3],axis=1);score=pos+.03*(1-flat);valid=(obj[:,2]>.75)&(obj[:,2]<.76)&(obj[:,0]>.30)&(obj[:,1]>-.63)&(flat>.98);score[~valid]+=10;ix=int(score.argmin());result=dict(index=ix,object_final=obj[ix].tolist(),flat_cos=float(flat[ix]),position_drift_m=float(pos[ix]),valid=bool(valid[ix]),parameters=parameters[ix].tolist(),arm_parameters=armparams[ix].tolist(),scope='Physicalbatchdevelopment, handnet includes robotgroundforces; nativecontact validation required');(out/'result.json').write_text(json.dumps(result,indent=2));np.savez_compressed(out/'best-rollout.npz',**{k:np.array([r[k][ix] for r in records]) for k in records[0]});print(result);record('mid_release_physical_batch_finished',[str(out/'result.json')],result,updates=dict(active_jobs=[]),next_step='One nativebest ifflatvalid, no repeatedsamebatch')
finally:e.close()
