task:
  name: artgrasp
  physics_engine: physx
  env:
    numEnvs: 100
    envSpacing: 0.75
    episodeLength: 30
    enableDebugVis: false
    aggregateMode: 0
    successHoldDurationSec: 1.5
    successHoldDurationRangeSec:
    - 0.0
    - 2.0
    maxConsecutiveSuccesses: 20
    goalSwitchTimeoutSec: 10.0
    jointNoise: 0.01
    dofSpeedScale: 1.0
    useRelativeControl: true
    graspSplit: train
    rewardWeightCurriculum:
      ObjPosDeviation: -5.0
      ObjRotDeviation: -0.2
      StableContact: 0.1
    rewardWeightCurriculumSchedule:
      warmupSteps: 200
      totalSteps: 2000
    binaryTactileThreshold: 0.05
    actionsMovingAverage: 0.01
    controlFrequencyInv: 4
    forceScale: 0
    forceProbRange:
    - 0.001
    - 0.1
    forceDecay: 0.99
    forceDecayInterval: 0.08
    policyObsDim: 111
    privilegedObsDim: 21
    studentInitObsDim: 55
    proprioHistoryLen: 50
    enableCameraSensors: false
    camera:
      height: 256
      width: 256
      horizontal_fov: 65
      use_collision_geometry: true
      cam_pos:
      - 0.0
      - 0.05
      - 0.75
      cam_target:
      - 0.0
      - -0.1
      - 0.5
  task:
    randomize: false
    randomization_params: {}
  sim:
    dt: 0.0083333
    substeps: 4
    up_axis: z
    use_gpu_pipeline: false
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: 4
      solver_type: 1
      use_gpu: true
      num_position_iterations: 16
      num_velocity_iterations: 4
      max_gpu_contact_pairs: 8388608
      num_subscenes: 0
      contact_offset: 0.002
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      contact_collection: 2
object:
  task:
    success_threshold: 0.002
    rot_devia_threshold: 1.57
    pos_devia_threshold: 0.05
    goals:
    - 0.04
    - 0.0
    contact_num: 5
  asset:
    type: knife
    asset_root: assets/objects/knife_wuji_lowgain_fresh_multigrasp2026092805
    instance_id_list:
    - '000'
    asset_file: mobility.urdf
    initDof: lower
    disgravity_part: []
    disfriction_part: []
    disrbforce_part: []
    dissimulate_part: []
  default_props:
    mass:
    - 0.029
    - 0.006
    friction: 3.0
    dof_stiffness: 0.0
    dof_damping: 0.3
  randomization:
    randomize: false
    dof_properties:
      damping:
        range:
        - 0.7
        - 1.3
        operation: scaling
        distribution: uniform
    rigid_body_properties:
      by_body:
        link_0:
          mass:
            range:
            - 1.0
            - 5.0
            operation: scaling
            distribution: uniform
        link_1:
          mass:
            range:
            - 1.0
            - 2.0
            operation: scaling
            distribution: uniform
    rigid_shape_properties:
      friction:
        num_buckets: 250
        range:
        - -1.0
        - 1.0
        operation: additive
        distribution: uniform
  reward:
    ObjPosDeviation: -0.5
    ObjRotDeviation: -0.02
    StableContact: 0.0
    HandQposDeviation: -0.001
    GoalDistance1: 1000.0
    GoalDistance2: 0.1
    Smooth: -1.0
    Drop: -25.0
    Success: 50.0
hand:
  type: wuji
  asset: assets/hands/wuji_artbot/right.urdf
  self_collisions: true
  force_links:
  - hand_r_thumb_pad_link
  - hand_r_index_pad_link
  - hand_r_middle_pad_link
  - hand_r_ring_pad_link
  - hand_r_pinky_pad_link
  track_links:
  - hand_r_thumb_pad_link
  - hand_r_index_pad_link
  - hand_r_middle_pad_link
  - hand_r_ring_pad_link
  - hand_r_pinky_pad_link
  dof_names:
  - hand_r_index_joint1
  - hand_r_index_joint2
  - hand_r_index_joint3
  - hand_r_index_joint4
  - hand_r_middle_joint1
  - hand_r_middle_joint2
  - hand_r_middle_joint3
  - hand_r_middle_joint4
  - hand_r_pinky_joint1
  - hand_r_pinky_joint2
  - hand_r_pinky_joint3
  - hand_r_pinky_joint4
  - hand_r_ring_joint1
  - hand_r_ring_joint2
  - hand_r_ring_joint3
  - hand_r_ring_joint4
  - hand_r_thumb_joint1
  - hand_r_thumb_joint2
  - hand_r_thumb_joint3
  - hand_r_thumb_joint4
  dof_props:
    stiffness:
    - 0.37352218155860073
    - 0.45592448909027794
    - 0.24368366649522863
    - 0.18026971340925335
    - 0.3687093483646485
    - 0.4164253443634641
    - 0.22218607502059182
    - 0.19427606072023446
    - 0.3655325975433942
    - 0.41393113081120425
    - 0.22729367621965954
    - 0.1964723550341816
    - 0.35718151495111794
    - 0.42977315313086895
    - 0.24930151196247122
    - 0.2285032688178066
    - 0.40844710645048043
    - 0.6858601063643346
    - 0.2391112196099482
    - 0.20736128319711747
    damping:
    - 0.01882274330029718
    - 0.019798167597016643
    - 0.010477031953162727
    - 0.008240212147903584
    - 0.01848622487024593
    - 0.018032947229953678
    - 0.009592200014076666
    - 0.009152994605972402
    - 0.018616960278988272
    - 0.018732177029667153
    - 0.00951005441616486
    - 0.009017295241756363
    - 0.018376606800780005
    - 0.01867700966212433
    - 0.01059512121009555
    - 0.009917602877441107
    - 0.020882010257063675
    - 0.030610939996373314
    - 0.010181475050560962
    - 0.00909698844675045
    friction:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    armature:
    - 0.0005
    - 0.0002
    - 0.0002
    - 0.0002
    - 0.0005
    - 0.0002
    - 0.0002
    - 0.0002
    - 0.0005
    - 0.0002
    - 0.0002
    - 0.0002
    - 0.0005
    - 0.0002
    - 0.0002
    - 0.0002
    - 0.0005
    - 0.0005
    - 0.0002
    - 0.0002
  task:
    numActions: 20
    propDim: 40
    policyObsDim: 111
    studentInitObsDim: 55
  randomization:
    randomize: false
  self_collision_mode: digit_filtered
train:
  params:
    seed: 20261018
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic_sapg_priv
      separate: true
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: const_initializer
            val: 0.0
          sigma_init:
            name: const_initializer
            val: -1.0
          fixed_sigma: coef_cond
      mlp:
        units:
        - 512
        - 256
        - 128
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
      rnn:
        name: lstm
        units: 512
        layers: 1
        before_mlp: true
        layer_norm: true
      sapg_priv:
        policy_obs_dim: 111
        privileged_obs_dim: 21
        critic_policy_contact_dim: 5
        expl_embedding_dim: 32
        encoder:
          units:
          - 256
          - 128
          - 16
          activation: elu
          initializer:
            name: default
        student_encoder:
          type: auto
          init_dim: 55
          proprio_encoder:
            units:
            - 128
            - 64
            activation: elu
            initializer:
              name: default
          init_encoder:
            units:
            - 128
            - 64
            activation: elu
            initializer:
              name: default
          temporal:
            type: tconv
            hidden_size: 192
            num_layers: 5
            kernel_size: 3
            dilation_growth: 2
            activation: elu
            dropout: 0.05
          latent_head:
            units:
            - 128
            activation: elu
            initializer:
              name: default
    load_checkpoint: false
    load_path: ''
    config:
      name: artmanipSAPGPrivLSTMPPO
      full_experiment_name: artmanipSAPGPrivLSTMPPO
      env_name: rlgpu
      multi_gpu: false
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      value_bootstrap: false
      num_actors: 100
      reward_shaper:
        scale_value: 1.0
      normalize_advantage: true
      gamma: 0.998
      tau: 0.95
      learning_rate: 0.0002
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.016
      score_to_win: 100000
      max_epochs: 50000
      save_best_after: 50
      save_frequency: 50
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 32
      minibatch_size: 16384
      mini_epochs: 4
      critic_coef: 4
      clip_value: true
      seq_length: 32
      bounds_loss_coef: 0.0001
      defer_summaries_sec: 5
      summaries_interval_sec_min: 5
      summaries_interval_sec_max: 100
      expl_type: mixed_expl_learn_param
      player:
        deterministic: true
        use_vecenv: true
        games_num: 1000000
        print_stats: false
      use_others_experience: lf
      off_policy_ratio: 1.0
      expl_reward_type: entropy
      expl_reward_coef_scale: 0.005
      expl_coef_block_size: 512
      managed_checkpoints: true
      checkpoint_first_epoch: 10
      checkpoint_keep_recent: 6
      checkpoint_milestone_frequency: 500
      evaluation_frequency: 50
pbt:
  enabled: false
task_name: artgrasp
experiment: ''
num_envs: 100
seed: 20261018
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: cpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: -1
num_threads: 4
solver_type: 1
num_subscenes: 0
test: false
checkpoint: ''
sigma: ''
multi_gpu: false
asset_dir: ''
capture_video: false
capture_video_freq: 1500
capture_video_len: 100
force_render: false
headless: true
